//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.FISCAL.CadConsultaCadastro4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", ConfigurationName="CadConsultaCadastro4.CadConsultaCadastro4Soap12")]
    public interface CadConsultaCadastro4Soap12 {
        
        // CODEGEN: Gerando contrato de mensagem porque a operação consultaCadastro não é RPC nem documento codificado.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COAD.FISCAL.CadConsultaCadastro4.consultaCadastroResponse consultaCadastro(COAD.FISCAL.CadConsultaCadastro4.consultaCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.CadConsultaCadastro4.consultaCadastroResponse> consultaCadastroAsync(COAD.FISCAL.CadConsultaCadastro4.consultaCadastroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCadastroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public consultaCadastroRequest() {
        }
        
        public consultaCadastroRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public consultaCadastroResponse() {
        }
        
        public consultaCadastroResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CadConsultaCadastro4Soap12Channel : COAD.FISCAL.CadConsultaCadastro4.CadConsultaCadastro4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CadConsultaCadastro4Soap12Client : System.ServiceModel.ClientBase<COAD.FISCAL.CadConsultaCadastro4.CadConsultaCadastro4Soap12>, COAD.FISCAL.CadConsultaCadastro4.CadConsultaCadastro4Soap12 {
        
        public CadConsultaCadastro4Soap12Client() {
        }
        
        public CadConsultaCadastro4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CadConsultaCadastro4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadConsultaCadastro4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadConsultaCadastro4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.CadConsultaCadastro4.consultaCadastroResponse COAD.FISCAL.CadConsultaCadastro4.CadConsultaCadastro4Soap12.consultaCadastro(COAD.FISCAL.CadConsultaCadastro4.consultaCadastroRequest request) {
            return base.Channel.consultaCadastro(request);
        }
        
        public System.Xml.XmlNode consultaCadastro(System.Xml.XmlNode nfeDadosMsg) {
            COAD.FISCAL.CadConsultaCadastro4.consultaCadastroRequest inValue = new COAD.FISCAL.CadConsultaCadastro4.consultaCadastroRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            COAD.FISCAL.CadConsultaCadastro4.consultaCadastroResponse retVal = ((COAD.FISCAL.CadConsultaCadastro4.CadConsultaCadastro4Soap12)(this)).consultaCadastro(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.CadConsultaCadastro4.consultaCadastroResponse> COAD.FISCAL.CadConsultaCadastro4.CadConsultaCadastro4Soap12.consultaCadastroAsync(COAD.FISCAL.CadConsultaCadastro4.consultaCadastroRequest request) {
            return base.Channel.consultaCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.CadConsultaCadastro4.consultaCadastroResponse> consultaCadastroAsync(System.Xml.XmlNode nfeDadosMsg) {
            COAD.FISCAL.CadConsultaCadastro4.consultaCadastroRequest inValue = new COAD.FISCAL.CadConsultaCadastro4.consultaCadastroRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((COAD.FISCAL.CadConsultaCadastro4.CadConsultaCadastro4Soap12)(this)).consultaCadastroAsync(inValue);
        }
    }
}
