//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.FISCAL.Nfse {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://notacarioca.rio.gov.br/", ConfigurationName="Nfse.NfseSoap")]
    public interface NfseSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfseRequest) da mensagem ConsultarNfseRequest não corresponde ao valor padrão (ConsultarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarNfse", ReplyAction="*")]
        COAD.FISCAL.Nfse.ConsultarNfseResponse ConsultarNfse(COAD.FISCAL.Nfse.ConsultarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarNfseResponse> ConsultarNfseAsync(COAD.FISCAL.Nfse.ConsultarNfseRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarNfsePorRpsRequest) da mensagem ConsultarNfsePorRpsRequest não corresponde ao valor padrão (ConsultarNfsePorRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarNfsePorRps", ReplyAction="*")]
        COAD.FISCAL.Nfse.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(COAD.FISCAL.Nfse.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(COAD.FISCAL.Nfse.ConsultarNfsePorRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarLoteRpsRequest) da mensagem ConsultarLoteRpsRequest não corresponde ao valor padrão (ConsultarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarLoteRps", ReplyAction="*")]
        COAD.FISCAL.Nfse.ConsultarLoteRpsResponse ConsultarLoteRps(COAD.FISCAL.Nfse.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(COAD.FISCAL.Nfse.ConsultarLoteRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (ConsultarSituacaoLoteRpsRequest) da mensagem ConsultarSituacaoLoteRpsRequest não corresponde ao valor padrão (ConsultarSituacaoLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps", ReplyAction="*")]
        COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsResponse ConsultarSituacaoLoteRps(COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/ConsultarSituacaoLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsResponse> ConsultarSituacaoLoteRpsAsync(COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (RecepcionarLoteRpsRequest) da mensagem RecepcionarLoteRpsRequest não corresponde ao valor padrão (RecepcionarLoteRps)
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/RecepcionarLoteRps", ReplyAction="*")]
        COAD.FISCAL.Nfse.RecepcionarLoteRpsResponse RecepcionarLoteRps(COAD.FISCAL.Nfse.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(COAD.FISCAL.Nfse.RecepcionarLoteRpsRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (CancelarNfseRequest) da mensagem CancelarNfseRequest não corresponde ao valor padrão (CancelarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/CancelarNfse", ReplyAction="*")]
        COAD.FISCAL.Nfse.CancelarNfseResponse CancelarNfse(COAD.FISCAL.Nfse.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.CancelarNfseResponse> CancelarNfseAsync(COAD.FISCAL.Nfse.CancelarNfseRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (GerarNfseRequest) da mensagem GerarNfseRequest não corresponde ao valor padrão (GerarNfse)
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/GerarNfse", ReplyAction="*")]
        COAD.FISCAL.Nfse.GerarNfseResponse GerarNfse(COAD.FISCAL.Nfse.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://notacarioca.rio.gov.br/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.GerarNfseResponse> GerarNfseAsync(COAD.FISCAL.Nfse.GerarNfseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseRequest", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class ConsultarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string inputXML;
        
        public ConsultarNfseRequest() {
        }
        
        public ConsultarNfseRequest(string inputXML) {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfseResponse", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class ConsultarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string outputXML;
        
        public ConsultarNfseResponse() {
        }
        
        public ConsultarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsRequest", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string inputXML;
        
        public ConsultarNfsePorRpsRequest() {
        }
        
        public ConsultarNfsePorRpsRequest(string inputXML) {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarNfsePorRpsResponse", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class ConsultarNfsePorRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponse() {
        }
        
        public ConsultarNfsePorRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsRequest", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class ConsultarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string inputXML;
        
        public ConsultarLoteRpsRequest() {
        }
        
        public ConsultarLoteRpsRequest(string inputXML) {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarLoteRpsResponse", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class ConsultarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponse() {
        }
        
        public ConsultarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSituacaoLoteRpsRequest", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class ConsultarSituacaoLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string inputXML;
        
        public ConsultarSituacaoLoteRpsRequest() {
        }
        
        public ConsultarSituacaoLoteRpsRequest(string inputXML) {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarSituacaoLoteRpsResponse", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class ConsultarSituacaoLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string outputXML;
        
        public ConsultarSituacaoLoteRpsResponse() {
        }
        
        public ConsultarSituacaoLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsRequest", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class RecepcionarLoteRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string inputXML;
        
        public RecepcionarLoteRpsRequest() {
        }
        
        public RecepcionarLoteRpsRequest(string inputXML) {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsResponse", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class RecepcionarLoteRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponse() {
        }
        
        public RecepcionarLoteRpsResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseRequest", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class CancelarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string inputXML;
        
        public CancelarNfseRequest() {
        }
        
        public CancelarNfseRequest(string inputXML) {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarNfseResponse", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class CancelarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string outputXML;
        
        public CancelarNfseResponse() {
        }
        
        public CancelarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseRequest", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class GerarNfseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string inputXML;
        
        public GerarNfseRequest() {
        }
        
        public GerarNfseRequest(string inputXML) {
            this.inputXML = inputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarNfseResponse", WrapperNamespace="http://notacarioca.rio.gov.br/", IsWrapped=true)]
    public partial class GerarNfseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://notacarioca.rio.gov.br/", Order=0)]
        public string outputXML;
        
        public GerarNfseResponse() {
        }
        
        public GerarNfseResponse(string outputXML) {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NfseSoapChannel : COAD.FISCAL.Nfse.NfseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NfseSoapClient : System.ServiceModel.ClientBase<COAD.FISCAL.Nfse.NfseSoap>, COAD.FISCAL.Nfse.NfseSoap {
        
        public NfseSoapClient() {
        }
        
        public NfseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NfseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NfseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.Nfse.ConsultarNfseResponse COAD.FISCAL.Nfse.NfseSoap.ConsultarNfse(COAD.FISCAL.Nfse.ConsultarNfseRequest request) {
            return base.Channel.ConsultarNfse(request);
        }
        
        public string ConsultarNfse(string inputXML) {
            COAD.FISCAL.Nfse.ConsultarNfseRequest inValue = new COAD.FISCAL.Nfse.ConsultarNfseRequest();
            inValue.inputXML = inputXML;
            COAD.FISCAL.Nfse.ConsultarNfseResponse retVal = ((COAD.FISCAL.Nfse.NfseSoap)(this)).ConsultarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarNfseResponse> COAD.FISCAL.Nfse.NfseSoap.ConsultarNfseAsync(COAD.FISCAL.Nfse.ConsultarNfseRequest request) {
            return base.Channel.ConsultarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarNfseResponse> ConsultarNfseAsync(string inputXML) {
            COAD.FISCAL.Nfse.ConsultarNfseRequest inValue = new COAD.FISCAL.Nfse.ConsultarNfseRequest();
            inValue.inputXML = inputXML;
            return ((COAD.FISCAL.Nfse.NfseSoap)(this)).ConsultarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.Nfse.ConsultarNfsePorRpsResponse COAD.FISCAL.Nfse.NfseSoap.ConsultarNfsePorRps(COAD.FISCAL.Nfse.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRps(request);
        }
        
        public string ConsultarNfsePorRps(string inputXML) {
            COAD.FISCAL.Nfse.ConsultarNfsePorRpsRequest inValue = new COAD.FISCAL.Nfse.ConsultarNfsePorRpsRequest();
            inValue.inputXML = inputXML;
            COAD.FISCAL.Nfse.ConsultarNfsePorRpsResponse retVal = ((COAD.FISCAL.Nfse.NfseSoap)(this)).ConsultarNfsePorRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarNfsePorRpsResponse> COAD.FISCAL.Nfse.NfseSoap.ConsultarNfsePorRpsAsync(COAD.FISCAL.Nfse.ConsultarNfsePorRpsRequest request) {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(string inputXML) {
            COAD.FISCAL.Nfse.ConsultarNfsePorRpsRequest inValue = new COAD.FISCAL.Nfse.ConsultarNfsePorRpsRequest();
            inValue.inputXML = inputXML;
            return ((COAD.FISCAL.Nfse.NfseSoap)(this)).ConsultarNfsePorRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.Nfse.ConsultarLoteRpsResponse COAD.FISCAL.Nfse.NfseSoap.ConsultarLoteRps(COAD.FISCAL.Nfse.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRps(request);
        }
        
        public string ConsultarLoteRps(string inputXML) {
            COAD.FISCAL.Nfse.ConsultarLoteRpsRequest inValue = new COAD.FISCAL.Nfse.ConsultarLoteRpsRequest();
            inValue.inputXML = inputXML;
            COAD.FISCAL.Nfse.ConsultarLoteRpsResponse retVal = ((COAD.FISCAL.Nfse.NfseSoap)(this)).ConsultarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarLoteRpsResponse> COAD.FISCAL.Nfse.NfseSoap.ConsultarLoteRpsAsync(COAD.FISCAL.Nfse.ConsultarLoteRpsRequest request) {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(string inputXML) {
            COAD.FISCAL.Nfse.ConsultarLoteRpsRequest inValue = new COAD.FISCAL.Nfse.ConsultarLoteRpsRequest();
            inValue.inputXML = inputXML;
            return ((COAD.FISCAL.Nfse.NfseSoap)(this)).ConsultarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsResponse COAD.FISCAL.Nfse.NfseSoap.ConsultarSituacaoLoteRps(COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsRequest request) {
            return base.Channel.ConsultarSituacaoLoteRps(request);
        }
        
        public string ConsultarSituacaoLoteRps(string inputXML) {
            COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsRequest inValue = new COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsRequest();
            inValue.inputXML = inputXML;
            COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsResponse retVal = ((COAD.FISCAL.Nfse.NfseSoap)(this)).ConsultarSituacaoLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsResponse> COAD.FISCAL.Nfse.NfseSoap.ConsultarSituacaoLoteRpsAsync(COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsRequest request) {
            return base.Channel.ConsultarSituacaoLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsResponse> ConsultarSituacaoLoteRpsAsync(string inputXML) {
            COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsRequest inValue = new COAD.FISCAL.Nfse.ConsultarSituacaoLoteRpsRequest();
            inValue.inputXML = inputXML;
            return ((COAD.FISCAL.Nfse.NfseSoap)(this)).ConsultarSituacaoLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.Nfse.RecepcionarLoteRpsResponse COAD.FISCAL.Nfse.NfseSoap.RecepcionarLoteRps(COAD.FISCAL.Nfse.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRps(request);
        }
        
        public string RecepcionarLoteRps(string inputXML) {
            COAD.FISCAL.Nfse.RecepcionarLoteRpsRequest inValue = new COAD.FISCAL.Nfse.RecepcionarLoteRpsRequest();
            inValue.inputXML = inputXML;
            COAD.FISCAL.Nfse.RecepcionarLoteRpsResponse retVal = ((COAD.FISCAL.Nfse.NfseSoap)(this)).RecepcionarLoteRps(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.RecepcionarLoteRpsResponse> COAD.FISCAL.Nfse.NfseSoap.RecepcionarLoteRpsAsync(COAD.FISCAL.Nfse.RecepcionarLoteRpsRequest request) {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.Nfse.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(string inputXML) {
            COAD.FISCAL.Nfse.RecepcionarLoteRpsRequest inValue = new COAD.FISCAL.Nfse.RecepcionarLoteRpsRequest();
            inValue.inputXML = inputXML;
            return ((COAD.FISCAL.Nfse.NfseSoap)(this)).RecepcionarLoteRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.Nfse.CancelarNfseResponse COAD.FISCAL.Nfse.NfseSoap.CancelarNfse(COAD.FISCAL.Nfse.CancelarNfseRequest request) {
            return base.Channel.CancelarNfse(request);
        }
        
        public string CancelarNfse(string inputXML) {
            COAD.FISCAL.Nfse.CancelarNfseRequest inValue = new COAD.FISCAL.Nfse.CancelarNfseRequest();
            inValue.inputXML = inputXML;
            COAD.FISCAL.Nfse.CancelarNfseResponse retVal = ((COAD.FISCAL.Nfse.NfseSoap)(this)).CancelarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.CancelarNfseResponse> COAD.FISCAL.Nfse.NfseSoap.CancelarNfseAsync(COAD.FISCAL.Nfse.CancelarNfseRequest request) {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.Nfse.CancelarNfseResponse> CancelarNfseAsync(string inputXML) {
            COAD.FISCAL.Nfse.CancelarNfseRequest inValue = new COAD.FISCAL.Nfse.CancelarNfseRequest();
            inValue.inputXML = inputXML;
            return ((COAD.FISCAL.Nfse.NfseSoap)(this)).CancelarNfseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.Nfse.GerarNfseResponse COAD.FISCAL.Nfse.NfseSoap.GerarNfse(COAD.FISCAL.Nfse.GerarNfseRequest request) {
            return base.Channel.GerarNfse(request);
        }
        
        public string GerarNfse(string inputXML) {
            COAD.FISCAL.Nfse.GerarNfseRequest inValue = new COAD.FISCAL.Nfse.GerarNfseRequest();
            inValue.inputXML = inputXML;
            COAD.FISCAL.Nfse.GerarNfseResponse retVal = ((COAD.FISCAL.Nfse.NfseSoap)(this)).GerarNfse(inValue);
            return retVal.outputXML;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.Nfse.GerarNfseResponse> COAD.FISCAL.Nfse.NfseSoap.GerarNfseAsync(COAD.FISCAL.Nfse.GerarNfseRequest request) {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.Nfse.GerarNfseResponse> GerarNfseAsync(string inputXML) {
            COAD.FISCAL.Nfse.GerarNfseRequest inValue = new COAD.FISCAL.Nfse.GerarNfseRequest();
            inValue.inputXML = inputXML;
            return ((COAD.FISCAL.Nfse.NfseSoap)(this)).GerarNfseAsync(inValue);
        }
    }
}
