//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_ITEM
    {
        public int EMP_ID { get; set; }
        public string PED_NUM_PEDIDO { get; set; }
        public int PRO_ID { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public Nullable<decimal> PIT_VLR_PEDIDO { get; set; }
        public Nullable<decimal> PIT_VLR_ENTRADA { get; set; }
        public Nullable<decimal> PIT_VLR_PARCELAS { get; set; }
        public int PIT_QTE_PARCELAS { get; set; }
        public int PED_TIPO { get; set; }
        public string PED_PERIODO_FAT { get; set; }
        public int PED_SEMANA_FAT { get; set; }
        public int PED_STATUS { get; set; }
        public int PED_MES_VIGENCIA { get; set; }
        public int PED_ENVIA_PASTA { get; set; }
        public int PED_ENVIA_BRINDE { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
