//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.SEGURANCA.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTABILISTA
    {
        public CONTABILISTA()
        {
            this.EMPRESA = new HashSet<EMPRESA>();
        }
    
        public int CNT_ID { get; set; }
        public string CNT_NOME { get; set; }
        public string CNT_CPF_CNPJ { get; set; }
        public string CNT_CRC_UF { get; set; }
        public string CTR_CRC_NUMERO { get; set; }
        public string CTR_CRC_DIGITO { get; set; }
        public string CTR_CEP { get; set; }
        public string CTR_LOGRADOURO { get; set; }
        public string CTR_NUMERO { get; set; }
        public string CTR_COMPLEMENTO { get; set; }
        public string CTR_BAIRRO { get; set; }
        public string CTR_TEL { get; set; }
        public string CTR_FAX { get; set; }
        public string CTR_CEL { get; set; }
        public string CTR_EMAIL { get; set; }
        public string IBGE_COD_COMPLETO { get; set; }
    
        public virtual ICollection<EMPRESA> EMPRESA { get; set; }
    }
}
