//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.SEGURANCA.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public DEPARTAMENTO()
        {
            this.PERFIL = new HashSet<PERFIL>();
        }
    
        public int DP_ID { get; set; }
        public string DP_NOME { get; set; }
        public Nullable<System.DateTime> DATA_DESATIVACAO { get; set; }
    
        public virtual ICollection<PERFIL> PERFIL { get; set; }
    }
}
