//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.SEGURANCA.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_MENU
    {
        public ITEM_MENU()
        {
            this.ITEM_MENU1 = new HashSet<ITEM_MENU>();
            this.ITEM_MENU_PERFIL = new HashSet<ITEM_MENU_PERFIL>();
        }
    
        public int ITM_ID { get; set; }
        public string ITM_DESCRICAO { get; set; }
        public string ITM_ARQUIVO { get; set; }
        public Nullable<int> ITM_NODE_ID { get; set; }
        public Nullable<int> ITM_MENU_SEQ { get; set; }
        public Nullable<int> ITM_MENU_NIVEL { get; set; }
        public Nullable<int> ITM_TIPO { get; set; }
        public Nullable<int> ITM_EXTERNO { get; set; }
        public Nullable<int> ITM_ATIVO { get; set; }
        public string ITM_RETORNO { get; set; }
        public string ITM_NOME_ARQUIVO { get; set; }
        public string SIS_ID { get; set; }
    
        public virtual ICollection<ITEM_MENU> ITEM_MENU1 { get; set; }
        public virtual ITEM_MENU ITEM_MENU2 { get; set; }
        public virtual ICollection<ITEM_MENU_PERFIL> ITEM_MENU_PERFIL { get; set; }
        public virtual SISTEMA SISTEMA { get; set; }
    }
}
