//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.SEGURANCA.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_MENU_PERFIL
    {
        public int EMP_ID { get; set; }
        public string PER_ID { get; set; }
        public int ITM_ID { get; set; }
        public Nullable<int> NIV_ACESSO { get; set; }
        public Nullable<int> NIV_INSERT { get; set; }
        public Nullable<int> NIV_EDIT { get; set; }
        public Nullable<int> NIV_DELETE { get; set; }
    
        public virtual ITEM_MENU ITEM_MENU { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
