//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.SEGURANCA.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_NOTIFICACAO_STATUS
    {
        public JOB_NOTIFICACAO_STATUS()
        {
            this.JOB_NOTIFICACAO = new HashSet<JOB_NOTIFICACAO>();
        }
    
        public int JNT_ID { get; set; }
        public string JNT_DESCRICAO { get; set; }
    
        public virtual ICollection<JOB_NOTIFICACAO> JOB_NOTIFICACAO { get; set; }
    }
}
