//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.SEGURANCA.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRO_GRUPO
    {
        public PARAMETRO_GRUPO()
        {
            this.PARAMETROS = new HashSet<PARAMETROS>();
        }
    
        public int PGR_ID { get; set; }
        public string PGR_DESCRICAO { get; set; }
    
        public virtual ICollection<PARAMETROS> PARAMETROS { get; set; }
    }
}
