//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.SEGURANCA.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATORIOS
    {
        public int REL_ID { get; set; }
        public string REL_DESCRICAO { get; set; }
        public string REL_PATH { get; set; }
        public string REL_TIPO { get; set; }
    }
}
