//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.SEGURANCA.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_NOTIFICACAO_SISTEMA
    {
        public TIPO_NOTIFICACAO_SISTEMA()
        {
            this.NOTIFICACAO_SISTEMA = new HashSet<NOTIFICACAO_SISTEMA>();
        }
    
        public int TNS_ID { get; set; }
        public string TNS_DESCRICAO { get; set; }
        public string TNS_COD_REF_DESC { get; set; }
        public string TNS_COD_REF_NOME_CAMPO { get; set; }
    
        public virtual ICollection<NOTIFICACAO_SISTEMA> NOTIFICACAO_SISTEMA { get; set; }
    }
}
