//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PROSPECTADOS.Repositorios.Contexto.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class prospectadosEntities : DbContext
    {
        public prospectadosEntities()
            : base("name=prospectadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ULTIMO_CODIGO> ULTIMO_CODIGO { get; set; }
        public DbSet<cart_coad> cart_coad { get; set; }
        public DbSet<EMAILS_PROSP> EMAILS_PROSP { get; set; }
        public DbSet<prospects> prospects { get; set; }
        public DbSet<TELEFONES_PROSP> TELEFONES_PROSP { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> INSERT_ULT_CODIGO(string vDV)
        {
            var vDVParameter = vDV != null ?
                new ObjectParameter("vDV", vDV) :
                new ObjectParameter("vDV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("INSERT_ULT_CODIGO", vDVParameter);
        }
    }
}
