//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PROSPECTADOS.Repositorios.Contexto.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ULTIMO_CODIGO
    {
        public int codigo { get; set; }
        public string dv { get; set; }
    }
}
