//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COADPAG.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICoadService")]
    public interface ICoadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/ValidarCliente", ReplyAction="http://tempuri.org/ICoadService/ValidarClienteResponse")]
        string ValidarCliente(string usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/ValidarCliente", ReplyAction="http://tempuri.org/ICoadService/ValidarClienteResponse")]
        System.Threading.Tasks.Task<string> ValidarClienteAsync(string usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/GerarPedido", ReplyAction="http://tempuri.org/ICoadService/GerarPedidoResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.DadosPedidoIntegracaoDTO GerarPedido(COAD.CORPORATIVO.Model.Dto.Custons.DadosPedidoIntegracaoDTO composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/GerarPedido", ReplyAction="http://tempuri.org/ICoadService/GerarPedidoResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.DadosPedidoIntegracaoDTO> GerarPedidoAsync(COAD.CORPORATIVO.Model.Dto.Custons.DadosPedidoIntegracaoDTO composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/LembrarSenha", ReplyAction="http://tempuri.org/ICoadService/LembrarSenhaResponse")]
        string LembrarSenha(string numAssinatura, int cliId, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/LembrarSenha", ReplyAction="http://tempuri.org/ICoadService/LembrarSenhaResponse")]
        System.Threading.Tasks.Task<string> LembrarSenhaAsync(string numAssinatura, int cliId, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/CheckoutPagamento", ReplyAction="http://tempuri.org/ICoadService/CheckoutPagamentoResponse")]
        string CheckoutPagamento(COAD.CORPORATIVO.Model.Dto.Custons.CartaoIntegracaoDTO dadospagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/CheckoutPagamento", ReplyAction="http://tempuri.org/ICoadService/CheckoutPagamentoResponse")]
        System.Threading.Tasks.Task<string> CheckoutPagamentoAsync(COAD.CORPORATIVO.Model.Dto.Custons.CartaoIntegracaoDTO dadospagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/EmitirPedidoRenovacaoDaMala", ReplyAction="http://tempuri.org/ICoadService/EmitirPedidoRenovacaoDaMalaResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.WebService.RenovacaoMalaResult EmitirPedidoRenovacaoDaMala(string numeroAssinatura, decimal valorPedido, int qtdParcelas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/EmitirPedidoRenovacaoDaMala", ReplyAction="http://tempuri.org/ICoadService/EmitirPedidoRenovacaoDaMalaResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.RenovacaoMalaResult> EmitirPedidoRenovacaoDaMalaAsync(string numeroAssinatura, decimal valorPedido, int qtdParcelas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/RealizarLogin", ReplyAction="http://tempuri.org/ICoadService/RealizarLoginResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.WebService.LoginUnicoResultDTO RealizarLogin(string code, string encodecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/RealizarLogin", ReplyAction="http://tempuri.org/ICoadService/RealizarLoginResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.LoginUnicoResultDTO> RealizarLoginAsync(string code, string encodecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/RetornarDadosDoCliente", ReplyAction="http://tempuri.org/ICoadService/RetornarDadosDoClienteResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.WebService.ClienteIntegracao.ClienteIntegrResult RetornarDadosDoCliente(string numeroAssinatura, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/RetornarDadosDoCliente", ReplyAction="http://tempuri.org/ICoadService/RetornarDadosDoClienteResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.ClienteIntegracao.ClienteIntegrResult> RetornarDadosDoClienteAsync(string numeroAssinatura, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/SalvarDadosDoCliente", ReplyAction="http://tempuri.org/ICoadService/SalvarDadosDoClienteResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.WebService.ValidatorWebServiceResult SalvarDadosDoCliente(COAD.CORPORATIVO.Model.Dto.Custons.WebService.ClienteIntegracao.ClienteIntegrDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/SalvarDadosDoCliente", ReplyAction="http://tempuri.org/ICoadService/SalvarDadosDoClienteResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.ValidatorWebServiceResult> SalvarDadosDoClienteAsync(COAD.CORPORATIVO.Model.Dto.Custons.WebService.ClienteIntegracao.ClienteIntegrDTO cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/BuscarCep", ReplyAction="http://tempuri.org/ICoadService/BuscarCepResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarCEPResult BuscarCep(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/BuscarCep", ReplyAction="http://tempuri.org/ICoadService/BuscarCepResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarCEPResult> BuscarCepAsync(string cep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/BuscarMunicipios", ReplyAction="http://tempuri.org/ICoadService/BuscarMunicipiosResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarMunicipioResult BuscarMunicipios(string uf, string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/BuscarMunicipios", ReplyAction="http://tempuri.org/ICoadService/BuscarMunicipiosResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarMunicipioResult> BuscarMunicipiosAsync(string uf, string descricao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/BuscarMunicipiosPorCodIBGE", ReplyAction="http://tempuri.org/ICoadService/BuscarMunicipiosPorCodIBGEResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarMunicipioResult BuscarMunicipiosPorCodIBGE(string codIBGE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/BuscarMunicipiosPorCodIBGE", ReplyAction="http://tempuri.org/ICoadService/BuscarMunicipiosPorCodIBGEResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarMunicipioResult> BuscarMunicipiosPorCodIBGEAsync(string codIBGE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/ListarTiposDeCliente", ReplyAction="http://tempuri.org/ICoadService/ListarTiposDeClienteResponse")]
        COAD.CORPORATIVO.Model.Dto.Custons.WebService.TipoClienteResult ListarTiposDeCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoadService/ListarTiposDeCliente", ReplyAction="http://tempuri.org/ICoadService/ListarTiposDeClienteResponse")]
        System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.TipoClienteResult> ListarTiposDeClienteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoadServiceChannel : COADPAG.ServiceReference1.ICoadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoadServiceClient : System.ServiceModel.ClientBase<COADPAG.ServiceReference1.ICoadService>, COADPAG.ServiceReference1.ICoadService {
        
        public CoadServiceClient() {
        }
        
        public CoadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidarCliente(string usuario, string senha) {
            return base.Channel.ValidarCliente(usuario, senha);
        }
        
        public System.Threading.Tasks.Task<string> ValidarClienteAsync(string usuario, string senha) {
            return base.Channel.ValidarClienteAsync(usuario, senha);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.DadosPedidoIntegracaoDTO GerarPedido(COAD.CORPORATIVO.Model.Dto.Custons.DadosPedidoIntegracaoDTO composite) {
            return base.Channel.GerarPedido(composite);
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.DadosPedidoIntegracaoDTO> GerarPedidoAsync(COAD.CORPORATIVO.Model.Dto.Custons.DadosPedidoIntegracaoDTO composite) {
            return base.Channel.GerarPedidoAsync(composite);
        }
        
        public string LembrarSenha(string numAssinatura, int cliId, string email) {
            return base.Channel.LembrarSenha(numAssinatura, cliId, email);
        }
        
        public System.Threading.Tasks.Task<string> LembrarSenhaAsync(string numAssinatura, int cliId, string email) {
            return base.Channel.LembrarSenhaAsync(numAssinatura, cliId, email);
        }
        
        public string CheckoutPagamento(COAD.CORPORATIVO.Model.Dto.Custons.CartaoIntegracaoDTO dadospagamento) {
            return base.Channel.CheckoutPagamento(dadospagamento);
        }
        
        public System.Threading.Tasks.Task<string> CheckoutPagamentoAsync(COAD.CORPORATIVO.Model.Dto.Custons.CartaoIntegracaoDTO dadospagamento) {
            return base.Channel.CheckoutPagamentoAsync(dadospagamento);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.WebService.RenovacaoMalaResult EmitirPedidoRenovacaoDaMala(string numeroAssinatura, decimal valorPedido, int qtdParcelas) {
            return base.Channel.EmitirPedidoRenovacaoDaMala(numeroAssinatura, valorPedido, qtdParcelas);
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.RenovacaoMalaResult> EmitirPedidoRenovacaoDaMalaAsync(string numeroAssinatura, decimal valorPedido, int qtdParcelas) {
            return base.Channel.EmitirPedidoRenovacaoDaMalaAsync(numeroAssinatura, valorPedido, qtdParcelas);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.WebService.LoginUnicoResultDTO RealizarLogin(string code, string encodecode) {
            return base.Channel.RealizarLogin(code, encodecode);
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.LoginUnicoResultDTO> RealizarLoginAsync(string code, string encodecode) {
            return base.Channel.RealizarLoginAsync(code, encodecode);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.WebService.ClienteIntegracao.ClienteIntegrResult RetornarDadosDoCliente(string numeroAssinatura, string senha) {
            return base.Channel.RetornarDadosDoCliente(numeroAssinatura, senha);
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.ClienteIntegracao.ClienteIntegrResult> RetornarDadosDoClienteAsync(string numeroAssinatura, string senha) {
            return base.Channel.RetornarDadosDoClienteAsync(numeroAssinatura, senha);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.WebService.ValidatorWebServiceResult SalvarDadosDoCliente(COAD.CORPORATIVO.Model.Dto.Custons.WebService.ClienteIntegracao.ClienteIntegrDTO cliente) {
            return base.Channel.SalvarDadosDoCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.ValidatorWebServiceResult> SalvarDadosDoClienteAsync(COAD.CORPORATIVO.Model.Dto.Custons.WebService.ClienteIntegracao.ClienteIntegrDTO cliente) {
            return base.Channel.SalvarDadosDoClienteAsync(cliente);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarCEPResult BuscarCep(string cep) {
            return base.Channel.BuscarCep(cep);
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarCEPResult> BuscarCepAsync(string cep) {
            return base.Channel.BuscarCepAsync(cep);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarMunicipioResult BuscarMunicipios(string uf, string descricao) {
            return base.Channel.BuscarMunicipios(uf, descricao);
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarMunicipioResult> BuscarMunicipiosAsync(string uf, string descricao) {
            return base.Channel.BuscarMunicipiosAsync(uf, descricao);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarMunicipioResult BuscarMunicipiosPorCodIBGE(string codIBGE) {
            return base.Channel.BuscarMunicipiosPorCodIBGE(codIBGE);
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.BuscarMunicipioResult> BuscarMunicipiosPorCodIBGEAsync(string codIBGE) {
            return base.Channel.BuscarMunicipiosPorCodIBGEAsync(codIBGE);
        }
        
        public COAD.CORPORATIVO.Model.Dto.Custons.WebService.TipoClienteResult ListarTiposDeCliente() {
            return base.Channel.ListarTiposDeCliente();
        }
        
        public System.Threading.Tasks.Task<COAD.CORPORATIVO.Model.Dto.Custons.WebService.TipoClienteResult> ListarTiposDeClienteAsync() {
            return base.Channel.ListarTiposDeClienteAsync();
        }
    }
}
