//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDAMENTO
    {
        public AGENDAMENTO()
        {
            this.HISTORICO_ATENDIMENTO = new HashSet<HISTORICO_ATENDIMENTO>();
            this.NOTIFICACOES = new HashSet<NOTIFICACOES>();
        }
    
        public int AGE_ID { get; set; }
        public Nullable<System.DateTime> AGE_DATA_REGISTRO { get; set; }
        public Nullable<System.DateTime> AGE_DATA_AGENDAMENTO { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public string CAR_ID { get; set; }
        public Nullable<int> REP_ID { get; set; }
        public string AGE_DESCRICAO { get; set; }
        public Nullable<System.DateTime> AGE_DATA_CONFIRMACAO { get; set; }
        public Nullable<System.DateTime> AGE_DATA_REAGENDAMENTO { get; set; }
        public Nullable<int> RG_ID { get; set; }
        public string USU_LOGIN { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public string PAR_NUM_PARCELA { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual CARTEIRA CARTEIRA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual REGIAO REGIAO { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
        public virtual ICollection<HISTORICO_ATENDIMENTO> HISTORICO_ATENDIMENTO { get; set; }
        public virtual ICollection<NOTIFICACOES> NOTIFICACOES { get; set; }
    }
}
