//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENDA_COBRANCA
    {
        public int AGC_ID { get; set; }
        public Nullable<System.DateTime> AGC_DATA_REGISTRO { get; set; }
        public Nullable<System.DateTime> AGC_DATA_ATENDIMENTO { get; set; }
        public Nullable<System.DateTime> AGC_DATA_AGENDA { get; set; }
        public string AGC_HORA_AGENDA { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public string PAR_NUM_PARCELA { get; set; }
        public string USU_LOGIN { get; set; }
        public string AGC_ASSUNTO { get; set; }
        public string AGC_RESUMO { get; set; }
        public Nullable<int> AGC_REAGENDAMENTO { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual PARCELAS PARCELAS { get; set; }
    }
}
