//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA_CONSULTORIA_CURSO
    {
        public int CMP_ID { get; set; }
        public int ARE_CONS_ID { get; set; }
        public int TIT_ID { get; set; }
    
        public virtual COLECIONADOR_REF COLECIONADOR_REF { get; set; }
        public virtual PRODUTO_COMPOSICAO PRODUTO_COMPOSICAO { get; set; }
        public virtual TITULACAO_REF TITULACAO_REF { get; set; }
    }
}
