//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSINATURA_TRANSFERENCIA
    {
        public ASSINATURA_TRANSFERENCIA()
        {
            this.HISTORICO_ATENDIMENTO = new HashSet<HISTORICO_ATENDIMENTO>();
            this.HISTORICO_PEDIDO = new HashSet<HISTORICO_PEDIDO>();
        }
    
        public string ASN_NUM_ASSINATURA_ANT { get; set; }
        public string ASN_NUM_ASSINATURA_ATU { get; set; }
        public int CLI_ID { get; set; }
        public string ASN_TRANSF_SOLICITANTE { get; set; }
        public Nullable<System.DateTime> ASN_DATA_TRANSF { get; set; }
        public string USU_LOGIN { get; set; }
        public string ASN_TRANSF_MOTIVO { get; set; }
        public string ASN_TRANSF_CONTRATO_ORIGEM { get; set; }
        public string ASN_TRANSF_CONTRATO_GERADO { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual CONTRATOS CONTRATOS1 { get; set; }
        public virtual ICollection<HISTORICO_ATENDIMENTO> HISTORICO_ATENDIMENTO { get; set; }
        public virtual ICollection<HISTORICO_PEDIDO> HISTORICO_PEDIDO { get; set; }
    }
}
