//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA
    {
        public int AUD_ID { get; set; }
        public Nullable<System.DateTime> AUD_DATA_ALTERA { get; set; }
        public Nullable<int> AUD_CAMPO_ALTERA { get; set; }
        public string AUD_VALOR_ANT_ALTERA { get; set; }
        public string AUD_TABELA_ALTERA { get; set; }
        public Nullable<int> FOR_ID { get; set; }
        public Nullable<int> CLI_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
    }
}
