//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRINHO_COMPRAS
    {
        public CARRINHO_COMPRAS()
        {
            this.CARRINHO_COMPRAS_ITEM = new HashSet<CARRINHO_COMPRAS_ITEM>();
        }
    
        public int CRC_ID { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public Nullable<System.DateTime> DATA_CRIACAO { get; set; }
        public Nullable<decimal> CRC_VALOR_BRUTO { get; set; }
        public Nullable<decimal> CRC_VALOR_FRETE { get; set; }
        public Nullable<decimal> CRC_VALOR_DESCONTO { get; set; }
        public Nullable<decimal> CRC_VALOR_LIQUIDO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual ICollection<CARRINHO_COMPRAS_ITEM> CARRINHO_COMPRAS_ITEM { get; set; }
    }
}
