//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTEIRA
    {
        public CARTEIRA()
        {
            this.AGENDAMENTO = new HashSet<AGENDAMENTO>();
            this.CARTEIRA_ASSINATURA = new HashSet<CARTEIRA_ASSINATURA>();
            this.CARTEIRA_CLIENTE = new HashSet<CARTEIRA_CLIENTE>();
            this.CARTEIRA_REPRESENTANTE = new HashSet<CARTEIRA_REPRESENTANTE>();
            this.PEDIDO_CRM = new HashSet<PEDIDO_CRM>();
            this.PROPOSTA = new HashSet<PROPOSTA>();
        }
    
        public string CAR_ID { get; set; }
        public string REGIAO_ID { get; set; }
        public string SEQ_REG { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public string REGIAO_UF { get; set; }
        public int CAR_VARIOS_REPRESENTANTES { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> UEN_ID { get; set; }
        public Nullable<int> REP_REF { get; set; }
        public Nullable<int> RG_ID { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
    
        public virtual ICollection<AGENDAMENTO> AGENDAMENTO { get; set; }
        public virtual ICollection<CARTEIRA_ASSINATURA> CARTEIRA_ASSINATURA { get; set; }
        public virtual ICollection<CARTEIRA_CLIENTE> CARTEIRA_CLIENTE { get; set; }
        public virtual EMPRESA_REF EMPRESA_REF { get; set; }
        public virtual REGIAO REGIAO { get; set; }
        public virtual ICollection<CARTEIRA_REPRESENTANTE> CARTEIRA_REPRESENTANTE { get; set; }
        public virtual UEN UEN { get; set; }
        public virtual UF UF { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
    }
}
