//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTEIRA_TRANSF
    {
        public CARTEIRA_TRANSF()
        {
            this.CARTEIRA_TRANSF_ITEM = new HashSet<CARTEIRA_TRANSF_ITEM>();
        }
    
        public int CAT_ID { get; set; }
        public Nullable<System.DateTime> CAT_DATA { get; set; }
        public Nullable<System.DateTime> CAT_DATA_TRANSF { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<int> CAT_QTDE_CLIENTES { get; set; }
    
        public virtual ICollection<CARTEIRA_TRANSF_ITEM> CARTEIRA_TRANSF_ITEM { get; set; }
    }
}
