//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTEIRA_REPRESENTANTE
    {
        public string CAR_ID { get; set; }
        public int REP_ID { get; set; }
        public Nullable<System.DateTime> DATA_ASSOCIACAO { get; set; }
        public string REP_OPER_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
    
        public virtual CARTEIRA CARTEIRA { get; set; }
        public virtual EMPRESA_REF EMPRESA_REF { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
    }
}
