//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTEIRA_ASSINATURA_TST2
    {
        public string CAR_ID { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public Nullable<int> UEN_ID { get; set; }
    }
}
