//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTEIRA_CLIENTE
    {
        public string CAR_ID { get; set; }
        public int CLI_ID { get; set; }
        public System.DateTime DATA_ASSOCIACAO { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public bool CCL_ORIGEM_PROSPECT { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual CARTEIRA CARTEIRA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
