//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFOP_REFERENCIA
    {
        public string CFOP_ENT { get; set; }
        public string CFOP_SAI { get; set; }
        public Nullable<int> CFOP_ATIVO { get; set; }
    
        public virtual CFOP_TABLE CFOP_TABLE { get; set; }
        public virtual CFOP_TABLE CFOP_TABLE1 { get; set; }
    }
}
