//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFOP_TABLE
    {
        public CFOP_TABLE()
        {
            this.CFOP_ICMS = new HashSet<CFOP_ICMS>();
            this.CFOP_REFERENCIA = new HashSet<CFOP_REFERENCIA>();
            this.CFOP_REFERENCIA1 = new HashSet<CFOP_REFERENCIA>();
            this.NOTA_FISCAL = new HashSet<NOTA_FISCAL>();
            this.NOTA_FISCAL_ITEM = new HashSet<NOTA_FISCAL_ITEM>();
        }
    
        public string CFOP { get; set; }
        public string CFOP_DESCRICAO { get; set; }
        public string CFOP_TIPO { get; set; }
    
        public virtual ICollection<CFOP_ICMS> CFOP_ICMS { get; set; }
        public virtual ICollection<CFOP_REFERENCIA> CFOP_REFERENCIA { get; set; }
        public virtual ICollection<CFOP_REFERENCIA> CFOP_REFERENCIA1 { get; set; }
        public virtual ICollection<NOTA_FISCAL> NOTA_FISCAL { get; set; }
        public virtual ICollection<NOTA_FISCAL_ITEM> NOTA_FISCAL_ITEM { get; set; }
    }
}
