//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE_DEVOLVIDO
    {
        public string ASN_NUM_ASSINATURA { get; set; }
        public string BAN_ID { get; set; }
        public string AGE_ID { get; set; }
        public string CHD_NUM_CHEQUE { get; set; }
        public string CHD_REF { get; set; }
        public Nullable<decimal> CHD_VALOR_CHEQUE { get; set; }
        public Nullable<System.DateTime> CHD_DATA_CHEQUE { get; set; }
        public string CHD_SOLICITANTE { get; set; }
        public Nullable<System.DateTime> CHD_DATA_LANCTO { get; set; }
        public Nullable<System.DateTime> CHD_DATA_IMP_FICHA { get; set; }
        public string CHD_CANCELADO { get; set; }
        public string CHD_EMITENTE { get; set; }
        public Nullable<System.DateTime> CHD_DATA_SUBST_REAP { get; set; }
        public Nullable<System.DateTime> CHD_DATA_1DEVOL { get; set; }
        public Nullable<System.DateTime> CHD_DATA_2DEVOL { get; set; }
        public string CHD_ATRIB_OPER_EM { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual ASSINATURA ASSINATURA1 { get; set; }
        public virtual BANCOS BANCOS { get; set; }
    }
}
