//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSIFICACAO_ATENDIMENTO
    {
        public CLASSIFICACAO_ATENDIMENTO()
        {
            this.TIPO_ATENDIMENTO = new HashSet<TIPO_ATENDIMENTO>();
        }
    
        public int CLA_ATEND_ID { get; set; }
        public string CLA_ATEND_DESCRICAO { get; set; }
    
        public virtual ICollection<TIPO_ATENDIMENTO> TIPO_ATENDIMENTO { get; set; }
    }
}
