//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public CLIENTES()
        {
            this.AGENDAMENTO = new HashSet<AGENDAMENTO>();
            this.ASSINATURA = new HashSet<ASSINATURA>();
            this.ASSINATURA_EMAIL = new HashSet<ASSINATURA_EMAIL>();
            this.ASSINATURA_TELEFONE = new HashSet<ASSINATURA_TELEFONE>();
            this.ASSINATURA_TRANSFERENCIA = new HashSet<ASSINATURA_TRANSFERENCIA>();
            this.AUDITORIA = new HashSet<AUDITORIA>();
            this.CARRINHO_COMPRAS = new HashSet<CARRINHO_COMPRAS>();
            this.CARTEIRA_CLIENTE = new HashSet<CARTEIRA_CLIENTE>();
            this.CLIENTE_USUARIO = new HashSet<CLIENTE_USUARIO>();
            this.CLIENTES_ENDERECO = new HashSet<CLIENTES_ENDERECO>();
            this.CLIENTES_HISTORICO = new HashSet<CLIENTES_HISTORICO>();
            this.CLIENTES_TELEFONE = new HashSet<CLIENTES_TELEFONE>();
            this.CONTATOS = new HashSet<CONTATOS>();
            this.ENDERECO_VENDA = new HashSet<ENDERECO_VENDA>();
            this.HISTORICO_ATENDIMENTO = new HashSet<HISTORICO_ATENDIMENTO>();
            this.MUNDIPAGG_CLIENTE = new HashSet<MUNDIPAGG_CLIENTE>();
            this.NOTA_FISCAL = new HashSet<NOTA_FISCAL>();
            this.NOTA_FISCAL_LOTE_ITEM = new HashSet<NOTA_FISCAL_LOTE_ITEM>();
            this.NOTIFICACOES = new HashSet<NOTIFICACOES>();
            this.PEDIDO_PARTICIPANTE = new HashSet<PEDIDO_PARTICIPANTE>();
            this.PEDIDO_CRM = new HashSet<PEDIDO_CRM>();
            this.PRIORIDADE_ATENDIMENTO = new HashSet<PRIORIDADE_ATENDIMENTO>();
            this.PROPOSTA = new HashSet<PROPOSTA>();
            this.REGISTRO_LIBERACAO = new HashSet<REGISTRO_LIBERACAO>();
        }
    
        public int CLI_ID { get; set; }
        public string CLI_NOME { get; set; }
        public string CLI_A_C { get; set; }
        public string CLI_TP_PESSOA { get; set; }
        public string CLI_CPF_CNPJ { get; set; }
        public string CLI_INSCRICAO { get; set; }
        public Nullable<bool> CLI_ISENTO_INSCRICAO { get; set; }
        public string MXM_CODIGO { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<int> CLA_ID { get; set; }
        public Nullable<int> TIPO_CLI_ID { get; set; }
        public string CLI_SUFRAMA { get; set; }
        public string CLI_COD_PAIS { get; set; }
        public Nullable<int> CLA_CLI_ID { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<int> CODIGO_ANTIGO { get; set; }
        public string CLI_EMAIL { get; set; }
        public Nullable<System.DateTime> DATA_ULTIMO_HISTORICO { get; set; }
        public Nullable<bool> CLI_FLAG_VALIDO { get; set; }
        public Nullable<int> SUS_ID_REF { get; set; }
        public Nullable<int> PROSP_ID { get; set; }
        public string CLI_SENHA { get; set; }
        public string CLI_LOGIN { get; set; }
        public string CLI_NOME_RESPONSAVEL_EMPRESA { get; set; }
        public string CLI_CPF_RESPONSAVEL_EMPRESA { get; set; }
        public Nullable<bool> CLI_IMPORTADO { get; set; }
        public Nullable<bool> CLI_EXCLUIDO_VALIDACAO { get; set; }
        public string CLI_CAR_ID_PROSPECT { get; set; }
        public Nullable<int> IPS_ID { get; set; }
    
        public virtual ICollection<AGENDAMENTO> AGENDAMENTO { get; set; }
        public virtual ICollection<ASSINATURA> ASSINATURA { get; set; }
        public virtual ICollection<ASSINATURA_EMAIL> ASSINATURA_EMAIL { get; set; }
        public virtual ICollection<ASSINATURA_TELEFONE> ASSINATURA_TELEFONE { get; set; }
        public virtual ICollection<ASSINATURA_TRANSFERENCIA> ASSINATURA_TRANSFERENCIA { get; set; }
        public virtual ICollection<AUDITORIA> AUDITORIA { get; set; }
        public virtual ICollection<CARRINHO_COMPRAS> CARRINHO_COMPRAS { get; set; }
        public virtual ICollection<CARTEIRA_CLIENTE> CARTEIRA_CLIENTE { get; set; }
        public virtual CLASSIFICACAO CLASSIFICACAO { get; set; }
        public virtual CLASSIFICACAO_CLIENTE CLASSIFICACAO_CLIENTE { get; set; }
        public virtual ICollection<CLIENTE_USUARIO> CLIENTE_USUARIO { get; set; }
        public virtual ICollection<CLIENTES_ENDERECO> CLIENTES_ENDERECO { get; set; }
        public virtual ICollection<CLIENTES_HISTORICO> CLIENTES_HISTORICO { get; set; }
        public virtual IMPORTACAO_SUSPECT IMPORTACAO_SUSPECT { get; set; }
        public virtual ICollection<CLIENTES_TELEFONE> CLIENTES_TELEFONE { get; set; }
        public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }
        public virtual ICollection<CONTATOS> CONTATOS { get; set; }
        public virtual ICollection<ENDERECO_VENDA> ENDERECO_VENDA { get; set; }
        public virtual ICollection<HISTORICO_ATENDIMENTO> HISTORICO_ATENDIMENTO { get; set; }
        public virtual INFO_MARKETING INFO_MARKETING { get; set; }
        public virtual ICollection<MUNDIPAGG_CLIENTE> MUNDIPAGG_CLIENTE { get; set; }
        public virtual ICollection<NOTA_FISCAL> NOTA_FISCAL { get; set; }
        public virtual ICollection<NOTA_FISCAL_LOTE_ITEM> NOTA_FISCAL_LOTE_ITEM { get; set; }
        public virtual ICollection<NOTIFICACOES> NOTIFICACOES { get; set; }
        public virtual ICollection<PEDIDO_PARTICIPANTE> PEDIDO_PARTICIPANTE { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM { get; set; }
        public virtual ICollection<PRIORIDADE_ATENDIMENTO> PRIORIDADE_ATENDIMENTO { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
        public virtual ICollection<REGISTRO_LIBERACAO> REGISTRO_LIBERACAO { get; set; }
    }
}
