//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES_ENDERECO
    {
        public CLIENTES_ENDERECO()
        {
            this.CLIENTES_ENDERECO_HISTORICO = new HashSet<CLIENTES_ENDERECO_HISTORICO>();
        }
    
        public int CLI_ID { get; set; }
        public int END_TIPO { get; set; }
        public string END_LOGRADOURO { get; set; }
        public string END_COMPLEMENTO { get; set; }
        public string END_NUMERO { get; set; }
        public string END_BAIRRO { get; set; }
        public string END_CEP { get; set; }
        public string IBGE_COD_COMPLETO { get; set; }
        public string END_MUNICIPIO { get; set; }
        public Nullable<int> MUN_ID { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string USU_LOGIN { get; set; }
        public string END_UF { get; set; }
        public string TIPO_COMP_ID { get; set; }
        public string TIPO_LOGRADOURO { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual ICollection<CLIENTES_ENDERECO_HISTORICO> CLIENTES_ENDERECO_HISTORICO { get; set; }
        public virtual IBGE_MUNICIPIO IBGE_MUNICIPIO { get; set; }
        public virtual MUNICIPIO MUNICIPIO { get; set; }
        public virtual TIPO_ENDERECO TIPO_ENDERECO { get; set; }
    }
}
