//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNAB_ARQUIVOS_ITEM_ERRO
    {
        public int CNE_ID { get; set; }
        public string CNE_LINHA_ERRO { get; set; }
        public Nullable<int> CNQ_ID { get; set; }
        public string CNE_NUM_LINHA { get; set; }
        public string CNE_NUM_PARCELA { get; set; }
        public string CNE_ERRO { get; set; }
    
        public virtual CNAB_ARQUIVOS CNAB_ARQUIVOS { get; set; }
    }
}
