//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNAB_CONFIG
    {
        public CNAB_CONFIG()
        {
            this.CNAB = new HashSet<CNAB>();
            this.CNAB_CONFIG_ARQUIVO = new HashSet<CNAB_CONFIG_ARQUIVO>();
        }
    
        public int CNC_ID { get; set; }
        public string CNC_CODIGO_CNAB { get; set; }
        public string CNC_ARQUIVO { get; set; }
        public Nullable<int> CNC_TIPO_REGISTRO { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string BAN_ID { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
    
        public virtual BANCOS BANCOS { get; set; }
        public virtual ICollection<CNAB> CNAB { get; set; }
        public virtual ICollection<CNAB_CONFIG_ARQUIVO> CNAB_CONFIG_ARQUIVO { get; set; }
    }
}
