//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_ALOCACAO_CONTA
    {
        public int CFA_ID { get; set; }
        public int CTA_ID { get; set; }
        public int TCC_ID { get; set; }
    
        public virtual CONFIG_ALOCACAO CONFIG_ALOCACAO { get; set; }
        public virtual CONTA_REF CONTA_REF { get; set; }
        public virtual TIPO_CONFIG_CONTA TIPO_CONFIG_CONTA { get; set; }
    }
}
