//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_IMPOSTO_REGIAO
    {
        public int CFI_ID { get; set; }
        public int RG_ID { get; set; }
        public Nullable<System.DateTime> DATA_ASSOCIACAO { get; set; }
    
        public virtual CONFIG_IMPOSTO CONFIG_IMPOSTO { get; set; }
        public virtual REGIAO REGIAO { get; set; }
    }
}
