//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_LIQUIDACAO
    {
        public DOC_LIQUIDACAO()
        {
            this.PARCELA_LIQUIDACAO = new HashSet<PARCELA_LIQUIDACAO>();
            this.TIPO_PAGAMENTO = new HashSet<TIPO_PAGAMENTO>();
        }
    
        public string DLI_SIGLA { get; set; }
        public string DLI_DESCRICAO { get; set; }
        public System.DateTime DLI_DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DLI_DATA_EXCLUSAO { get; set; }
    
        public virtual ICollection<PARCELA_LIQUIDACAO> PARCELA_LIQUIDACAO { get; set; }
        public virtual ICollection<TIPO_PAGAMENTO> TIPO_PAGAMENTO { get; set; }
    }
}
