//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_ATEND
    {
        public EMAIL_ATEND()
        {
            this.EMAIL_ATEND_ANEXO = new HashSet<EMAIL_ATEND_ANEXO>();
        }
    
        public int EAT_ID { get; set; }
        public string EAT_ASSUNTO { get; set; }
        public Nullable<int> HAE_ID { get; set; }
        public Nullable<System.DateTime> EAT_DATA { get; set; }
        public string EAT_FROM_NOME { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<System.DateTime> EAT_DATA_ENVIO { get; set; }
        public string EAT_EMAIL_CC { get; set; }
        public string EAT_EMAIL_BCC { get; set; }
        public string EAT_TEXTO_EMAIL { get; set; }
        public string EAT_EMAIL_FROM { get; set; }
    
        public virtual ICollection<EMAIL_ATEND_ANEXO> EMAIL_ATEND_ANEXO { get; set; }
        public virtual HIST_ATEND_EMAIL HIST_ATEND_EMAIL { get; set; }
    }
}
