//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA_REF
    {
        public EMPRESA_REF()
        {
            this.CARTEIRA = new HashSet<CARTEIRA>();
            this.CARTEIRA_REPRESENTANTE = new HashSet<CARTEIRA_REPRESENTANTE>();
            this.CNAB = new HashSet<CNAB>();
            this.CNAB_ARQUIVOS = new HashSet<CNAB_ARQUIVOS>();
            this.CONFIG_ALOCACAO = new HashSet<CONFIG_ALOCACAO>();
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.PEDIDO_CRM = new HashSet<PEDIDO_CRM>();
            this.PROPOSTA = new HashSet<PROPOSTA>();
            this.REPRESENTANTE = new HashSet<REPRESENTANTE>();
            this.NOTA_FISCAL = new HashSet<NOTA_FISCAL>();
            this.PARCELAS = new HashSet<PARCELAS>();
            this.PARCELAS_REMESSA = new HashSet<PARCELAS_REMESSA>();
            this.REGIAO = new HashSet<REGIAO>();
            this.REGISTRO_FATURAMENTO = new HashSet<REGISTRO_FATURAMENTO>();
            this.SEQUENCIAL_NOSSO_NUMERO = new HashSet<SEQUENCIAL_NOSSO_NUMERO>();
            this.SPED_ARQUIVO = new HashSet<SPED_ARQUIVO>();
            this.TOTAL_VENDAS_CARTAO = new HashSet<TOTAL_VENDAS_CARTAO>();
        }
    
        public int EMP_ID { get; set; }
    
        public virtual ICollection<CARTEIRA> CARTEIRA { get; set; }
        public virtual ICollection<CARTEIRA_REPRESENTANTE> CARTEIRA_REPRESENTANTE { get; set; }
        public virtual ICollection<CNAB> CNAB { get; set; }
        public virtual ICollection<CNAB_ARQUIVOS> CNAB_ARQUIVOS { get; set; }
        public virtual ICollection<CONFIG_ALOCACAO> CONFIG_ALOCACAO { get; set; }
        public virtual CONFIG_SPED_FISCAL CONFIG_SPED_FISCAL { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
        public virtual ICollection<REPRESENTANTE> REPRESENTANTE { get; set; }
        public virtual ICollection<NOTA_FISCAL> NOTA_FISCAL { get; set; }
        public virtual ICollection<PARCELAS> PARCELAS { get; set; }
        public virtual ICollection<PARCELAS_REMESSA> PARCELAS_REMESSA { get; set; }
        public virtual ICollection<REGIAO> REGIAO { get; set; }
        public virtual ICollection<REGISTRO_FATURAMENTO> REGISTRO_FATURAMENTO { get; set; }
        public virtual ICollection<SEQUENCIAL_NOSSO_NUMERO> SEQUENCIAL_NOSSO_NUMERO { get; set; }
        public virtual ICollection<SPED_ARQUIVO> SPED_ARQUIVO { get; set; }
        public virtual ICollection<TOTAL_VENDAS_CARTAO> TOTAL_VENDAS_CARTAO { get; set; }
    }
}
