//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILA_CADASTRO
    {
        public int FLC_ID { get; set; }
        public Nullable<int> REP_ID { get; set; }
        public int FLC_ORDEM { get; set; }
        public Nullable<System.DateTime> FLC_DATA { get; set; }
        public Nullable<int> RG_ID { get; set; }
        public Nullable<bool> FLC_IMPORTACAO { get; set; }
    
        public virtual REGIAO REGIAO { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
    }
}
