//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        public GRUPO()
        {
            this.PRODUTOS = new HashSet<PRODUTOS>();
        }
    
        public int GRUPO_ID { get; set; }
        public string GRU_DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public string USU_LOGIN_EXCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
    
        public virtual ICollection<PRODUTOS> PRODUTOS { get; set; }
    }
}
