//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_PEDIDO
    {
        public int HIP_ID { get; set; }
        public string HIP_DESCRICAO { get; set; }
        public Nullable<System.DateTime> HIP_DATA { get; set; }
        public Nullable<int> PST_ID { get; set; }
        public Nullable<int> IPE_ID { get; set; }
        public Nullable<int> REP_ID { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<int> PPI_ID { get; set; }
        public string ASN_NUM_ASSINATURA_ANT { get; set; }
        public string ASN_NUM_ASSINATURA_ATU { get; set; }
    
        public virtual ASSINATURA_TRANSFERENCIA ASSINATURA_TRANSFERENCIA { get; set; }
        public virtual ITEM_PEDIDO ITEM_PEDIDO { get; set; }
        public virtual PEDIDO_STATUS PEDIDO_STATUS { get; set; }
        public virtual PROPOSTA_ITEM PROPOSTA_ITEM { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
    }
}
