//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIST_ATEND_EMAIL
    {
        public HIST_ATEND_EMAIL()
        {
            this.EMAIL_ATEND = new HashSet<EMAIL_ATEND>();
        }
    
        public int HAE_ID { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public int CON_ID { get; set; }
        public int CON_ID_SUPERVISOR { get; set; }
        public int HAE_COD_CQ { get; set; }
        public string HAE_EMAIL { get; set; }
        public string HAE_UF { get; set; }
        public string HAE_PERGUNTA { get; set; }
        public string HAE_RESPOSTA_CONSULTOR { get; set; }
        public string HAE_RESPOSTA_SUPERVISOR { get; set; }
        public string HAE_RESPOSTA_CQ { get; set; }
        public string HAE_STATUS { get; set; }
        public System.DateTime HAE_DTCADASTRO { get; set; }
        public Nullable<System.DateTime> HAE_DTRESP_CONSULTOR { get; set; }
        public Nullable<System.DateTime> HAE_DTRESP_SUPERVISOR { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual CONSULTOR CONSULTOR { get; set; }
        public virtual CONSULTOR CONSULTOR1 { get; set; }
        public virtual ICollection<EMAIL_ATEND> EMAIL_ATEND { get; set; }
    }
}
