//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_ATENDIMENTO
    {
        public int HAT_ID { get; set; }
        public System.DateTime HAT_DATA_HIST { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public Nullable<int> ACA_ID { get; set; }
        public Nullable<System.DateTime> HAT_DATA_RESOLUCAO { get; set; }
        public Nullable<int> TIP_ATEND_ID { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<bool> HAT_IMP_ETIQUETA { get; set; }
        public string HAT_DESCRICAO { get; set; }
        public Nullable<int> UEN_ID { get; set; }
        public Nullable<int> AGE_ID { get; set; }
        public Nullable<int> REP_ID { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public string HAT_ORIGEM_ATEND { get; set; }
        public string HAT_SOLICITANTE { get; set; }
        public Nullable<int> PED_CRM_ID { get; set; }
        public Nullable<int> IPE_ID { get; set; }
        public Nullable<int> PPI_ID { get; set; }
        public string ASN_NUM_ASSINATURA_ANT { get; set; }
        public string ASN_NUM_ASSINATURA_ATU { get; set; }
    
        public virtual ACAO_ATENDIMENTO ACAO_ATENDIMENTO { get; set; }
        public virtual AGENDAMENTO AGENDAMENTO { get; set; }
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual ASSINATURA_TRANSFERENCIA ASSINATURA_TRANSFERENCIA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual PEDIDO_CRM PEDIDO_CRM { get; set; }
        public virtual PROPOSTA_ITEM PROPOSTA_ITEM { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
        public virtual TIPO_ATENDIMENTO TIPO_ATENDIMENTO { get; set; }
        public virtual UEN UEN { get; set; }
        public virtual ITEM_PEDIDO ITEM_PEDIDO { get; set; }
    }
}
