//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIST_ATEND_URA
    {
        public string URA_ID { get; set; }
        public string HAU_ID { get; set; }
        public System.DateTime HAU_DATA_CADASTRO { get; set; }
        public Nullable<int> HAU_RAMAL { get; set; }
        public string HAU_TELEFONE { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public string HAU_ATENDIDO { get; set; }
        public string HAU_ATENDIDO_SISTEMA { get; set; }
        public Nullable<System.DateTime> HAU_DATA_LOG { get; set; }
        public Nullable<int> HAU_USUARIO_ID { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual URA URA { get; set; }
    }
}
