//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTACAO_HISTORICO
    {
        public int IMH_ID { get; set; }
        public string IMH_DESCRICAO { get; set; }
        public Nullable<int> IPS_ID { get; set; }
        public Nullable<int> IMP_ID { get; set; }
        public Nullable<int> IMS_ID { get; set; }
        public Nullable<bool> IMH_ERRO { get; set; }
        public Nullable<bool> IMH_HISTORICO_DA_IMPORTACAO { get; set; }
        public Nullable<int> IMH_TOTAL_SUSPECTS { get; set; }
        public Nullable<int> IMH_TOTAL_DUPLICADO { get; set; }
        public Nullable<int> IMH_TOTAL_PROCESSADO { get; set; }
        public Nullable<int> IMH_TOTAL_SUCESSO { get; set; }
        public Nullable<int> IMH_TOTAL_FALHA { get; set; }
        public Nullable<System.DateTime> IMH_DATA { get; set; }
        public Nullable<int> REP_ID { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual IMPORTACAO IMPORTACAO { get; set; }
        public virtual IMPORTACAO_STATUS IMPORTACAO_STATUS { get; set; }
        public virtual IMPORTACAO_SUSPECT IMPORTACAO_SUSPECT { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
    }
}
