//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPOSTO_INFO_FATURA
    {
        public int IMP_ID { get; set; }
        public int IFF_ID { get; set; }
        public Nullable<System.DateTime> DATA_ASSOCIACAO { get; set; }
        public Nullable<decimal> IIF_VALOR_DESCONTO { get; set; }
        public Nullable<decimal> IIF_PERCENTUAL_DESCONTO { get; set; }
    
        public virtual IMPOSTO IMPOSTO { get; set; }
        public virtual INFO_FATURA INFO_FATURA { get; set; }
    }
}
