//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPOSTO_INFO_FATURA_ITEM
    {
        public int IMP_ID { get; set; }
        public int IFI_ID { get; set; }
        public Nullable<decimal> IFI_PERCENTUAL_DESCONTO { get; set; }
        public Nullable<decimal> IFI_VALOR_DESCONTADO { get; set; }
    
        public virtual IMPOSTO IMPOSTO { get; set; }
        public virtual INFO_FATURA_ITEM INFO_FATURA_ITEM { get; set; }
    }
}
