//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTACAO_RESULTADO_RODIZIO
    {
        public int IRR_ID { get; set; }
        public string IRR_NOME_REPRESENTANTE { get; set; }
        public Nullable<int> REP_ID { get; set; }
        public Nullable<int> RG_ID { get; set; }
        public Nullable<int> IMP_ID { get; set; }
        public Nullable<int> IRR_QTD_PRIORIDADES { get; set; }
        public Nullable<int> IRR_QTD { get; set; }
    
        public virtual IMPORTACAO IMPORTACAO { get; set; }
        public virtual REGIAO REGIAO { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
    }
}
