//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMATIVO_SEMANAL_ANALITICO
    {
        public string INF_ANO { get; set; }
        public string INF_REMESSA { get; set; }
        public int INF_ENVIO { get; set; }
        public int INF_PRO_ID { get; set; }
        public bool INF_PROTOCOLADA { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public string END_UF { get; set; }
        public string USU_LOGIN { get; set; }
    }
}
