//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_PEDIDO
    {
        public ITEM_PEDIDO()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.HISTORICO_ATENDIMENTO = new HashSet<HISTORICO_ATENDIMENTO>();
            this.HISTORICO_PEDIDO = new HashSet<HISTORICO_PEDIDO>();
            this.ITEM_PEDIDO_PEDIDO_PAGAMENTO = new HashSet<ITEM_PEDIDO_PEDIDO_PAGAMENTO>();
            this.PROPOSTA_ITEM_COMPROVANTE = new HashSet<PROPOSTA_ITEM_COMPROVANTE>();
            this.NFE_XML = new HashSet<NFE_XML>();
            this.NOTA_FISCAL_LOTE_ITEM = new HashSet<NOTA_FISCAL_LOTE_ITEM>();
            this.NOTA_FISCAL = new HashSet<NOTA_FISCAL>();
            this.PARCELAS = new HashSet<PARCELAS>();
            this.PEDIDO_PARTICIPANTE = new HashSet<PEDIDO_PARTICIPANTE>();
            this.REGISTRO_FATURAMENTO = new HashSet<REGISTRO_FATURAMENTO>();
            this.RETORNO_TRANSACAO = new HashSet<RETORNO_TRANSACAO>();
        }
    
        public int IPE_ID { get; set; }
        public Nullable<int> PED_CRM_ID { get; set; }
        public Nullable<int> CMP_ID { get; set; }
        public Nullable<int> IPE_QTD { get; set; }
        public Nullable<decimal> IPE_VALOR_PRODUTO { get; set; }
        public Nullable<decimal> IPE_DESCONTO { get; set; }
        public Nullable<int> TP_ID { get; set; }
        public Nullable<int> RG_ID { get; set; }
        public string IPE_COD { get; set; }
        public Nullable<int> IPE_PARCELA { get; set; }
        public Nullable<decimal> IPE_VALOR_PARCELA { get; set; }
        public Nullable<decimal> IPE_TOTAL { get; set; }
        public Nullable<decimal> IPE_PRECO_UNITARIO { get; set; }
        public Nullable<int> PROSP_ID { get; set; }
        public Nullable<int> PST_ID { get; set; }
        public Nullable<decimal> IPE_TOTAL_SEM_IMPOSTO { get; set; }
        public string IPE_LOGIN_APROVOU_DESCONTO { get; set; }
        public string IPE_LOGIN_ALTEROU_STATUS { get; set; }
        public Nullable<int> TTP_ID { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public string IPE_COD_LEGADO { get; set; }
        public Nullable<int> IFF_ID { get; set; }
        public string IPE_PATH_NFE { get; set; }
        public string ORDER_KEY { get; set; }
        public Nullable<bool> IPE_PRIMEIRA_PARCELA_CORTERIA { get; set; }
        public string IPE_OBSERVACAO { get; set; }
        public Nullable<short> IPE_DIA_VENCIMENTO_VENDA_RECORRENTE { get; set; }
        public Nullable<bool> IPE_PAGAMENTO_GATEWAY { get; set; }
        public string AUTHORIZATION_CODE { get; set; }
        public string ORDER_KEY_REF { get; set; }
        public Nullable<int> PPI_ID { get; set; }
        public Nullable<bool> IPE_POSSUI_ENTRADA { get; set; }
        public Nullable<decimal> IPE_VALOR_ENTRADA { get; set; }
        public Nullable<bool> IPE_ACESSOS_CONCEDIDOS { get; set; }
        public Nullable<int> IPE_QTD_CONSULTA { get; set; }
        public Nullable<System.DateTime> IPE_DATA_VALIDADE { get; set; }
        public Nullable<bool> IPE_CORTESIA { get; set; }
        public Nullable<System.DateTime> IPE_DATA_FATURAMENTO { get; set; }
        public Nullable<System.DateTime> IPE_DATA_FATURAMENTO_SEMANA_FAT { get; set; }
        public string IPE_PERIODO_FAT { get; set; }
        public string IPE_SEMANA_FAT { get; set; }
        public Nullable<System.DateTime> IPE_DATA_FATURAMENTO_ALTERADA { get; set; }
        public Nullable<int> IPE_PERIODO_MES_BONUS { get; set; }
        public Nullable<System.DateTime> IPE_DATA_PRODUCAO { get; set; }
        public string IPE_ASN_NUM_ASS_CANC { get; set; }
        public Nullable<int> TPG_ID { get; set; }
        public Nullable<bool> IPE_GERA_NOTA { get; set; }
        public Nullable<int> IFF_ID_ENTRADA { get; set; }
        public Nullable<decimal> IPE_VALOR_BRUTO_ENTRADA { get; set; }
        public Nullable<int> LOC_ID { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual ASSINATURA ASSINATURA1 { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<HISTORICO_ATENDIMENTO> HISTORICO_ATENDIMENTO { get; set; }
        public virtual ICollection<HISTORICO_PEDIDO> HISTORICO_PEDIDO { get; set; }
        public virtual INFO_FATURA INFO_FATURA { get; set; }
        public virtual INFO_FATURA INFO_FATURA1 { get; set; }
        public virtual ICollection<ITEM_PEDIDO_PEDIDO_PAGAMENTO> ITEM_PEDIDO_PEDIDO_PAGAMENTO { get; set; }
        public virtual PEDIDO_CRM PEDIDO_CRM { get; set; }
        public virtual PEDIDO_STATUS PEDIDO_STATUS { get; set; }
        public virtual PRODUTO_COMPOSICAO PRODUTO_COMPOSICAO { get; set; }
        public virtual PROPOSTA_ITEM PROPOSTA_ITEM { get; set; }
        public virtual REGIAO_TABELA_PRECO REGIAO_TABELA_PRECO { get; set; }
        public virtual TIPO_PAGAMENTO TIPO_PAGAMENTO { get; set; }
        public virtual LOCALIZACAO_CURSO LOCALIZACAO_CURSO { get; set; }
        public virtual ICollection<PROPOSTA_ITEM_COMPROVANTE> PROPOSTA_ITEM_COMPROVANTE { get; set; }
        public virtual ICollection<NFE_XML> NFE_XML { get; set; }
        public virtual ICollection<NOTA_FISCAL_LOTE_ITEM> NOTA_FISCAL_LOTE_ITEM { get; set; }
        public virtual ICollection<NOTA_FISCAL> NOTA_FISCAL { get; set; }
        public virtual ICollection<PARCELAS> PARCELAS { get; set; }
        public virtual ICollection<PEDIDO_PARTICIPANTE> PEDIDO_PARTICIPANTE { get; set; }
        public virtual ICollection<REGISTRO_FATURAMENTO> REGISTRO_FATURAMENTO { get; set; }
        public virtual ICollection<RETORNO_TRANSACAO> RETORNO_TRANSACAO { get; set; }
        public virtual TIPO_PERIODO TIPO_PERIODO { get; set; }
    }
}
