//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINHA_PRODUTO_INFORMATIVO
    {
        public int INF_ID { get; set; }
        public string INF_DECRICAO { get; set; }
        public string INF_PERIODICIDADE { get; set; }
        public string INF_TIPO { get; set; }
        public Nullable<int> LIN_PRO_ID { get; set; }
        public string INF_ABREV { get; set; }
    
        public virtual LINHA_PRODUTO LINHA_PRODUTO { get; set; }
    }
}
