//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINHA_PRODUTO
    {
        public LINHA_PRODUTO()
        {
            this.LINHA_PRODUTO_INFORMATIVO = new HashSet<LINHA_PRODUTO_INFORMATIVO>();
            this.ORIGEM_ACESSO = new HashSet<ORIGEM_ACESSO>();
            this.PRODUTO_COMPOSICAO = new HashSet<PRODUTO_COMPOSICAO>();
            this.PRODUTOS = new HashSet<PRODUTOS>();
        }
    
        public int LIN_PRO_ID { get; set; }
        public string LIN_PRO_DESCRICAO { get; set; }
    
        public virtual ICollection<LINHA_PRODUTO_INFORMATIVO> LINHA_PRODUTO_INFORMATIVO { get; set; }
        public virtual ICollection<ORIGEM_ACESSO> ORIGEM_ACESSO { get; set; }
        public virtual ICollection<PRODUTO_COMPOSICAO> PRODUTO_COMPOSICAO { get; set; }
        public virtual ICollection<PRODUTOS> PRODUTOS { get; set; }
    }
}
