//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ATUALIZACAO_URA
    {
        public int LOG_ATU_URA { get; set; }
        public string LOG_URA_ID { get; set; }
        public Nullable<System.DateTime> LOG_URA_DATA { get; set; }
        public string LOG_URA_TIPO { get; set; }
        public Nullable<decimal> LOG_URA_ROWS { get; set; }
    }
}
