//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTIVO_CANCELAMENTO
    {
        public int MCA_ID { get; set; }
        public string MCA_DESCRICAO { get; set; }
        public string TIP_CANC_ID { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public string CTR_NUM_CONTRATO { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual TIPO_CANCELAMENTO TIPO_CANCELAMENTO { get; set; }
    }
}
