//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNDIPAGG_CLIENTE
    {
        public MUNDIPAGG_CLIENTE()
        {
            this.MUNDIPAGG_ASSINATURA = new HashSet<MUNDIPAGG_ASSINATURA>();
        }
    
        public int MPG_CLI_ID { get; set; }
        public string MPG_CLI_CUS_ID { get; set; }
        public string MPG_CLI_NAME { get; set; }
        public string MPG_CLI_CODE { get; set; }
        public string MPG_CLI_DOCUMENT { get; set; }
        public string MPG_CLI_TYPE { get; set; }
        public int CLI_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual ICollection<MUNDIPAGG_ASSINATURA> MUNDIPAGG_ASSINATURA { get; set; }
    }
}
