//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNDIPAGG_ASSINATURA
    {
        public MUNDIPAGG_ASSINATURA()
        {
            this.PROPOSTA = new HashSet<PROPOSTA>();
        }
    
        public int MPG_ASN_ID { get; set; }
        public string MPG_ASN_SUB_ID { get; set; }
        public int MPG_CLI_ID { get; set; }
    
        public virtual MUNDIPAGG_CLIENTE MUNDIPAGG_CLIENTE { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
    }
}
