//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVEL_REPRESENTANTE
    {
        public NIVEL_REPRESENTANTE()
        {
            this.REPRESENTANTE = new HashSet<REPRESENTANTE>();
        }
    
        public int NRP_ID { get; set; }
        public string NRP_DESCRICAO { get; set; }
        public Nullable<int> NRP_NIVEL { get; set; }
        public string PER_ID { get; set; }
        public bool FRANQUIA { get; set; }
    
        public virtual ICollection<REPRESENTANTE> REPRESENTANTE { get; set; }
    }
}
