//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_FISCAL
    {
        public NOTA_FISCAL()
        {
            this.NOTA_FISCAL_EVENTO = new HashSet<NOTA_FISCAL_EVENTO>();
            this.NOTA_FISCAL_ITEM = new HashSet<NOTA_FISCAL_ITEM>();
            this.NOTA_FISCAL_LOTE_ITEM = new HashSet<NOTA_FISCAL_LOTE_ITEM>();
            this.NOTA_FISCAL_REFERENCIADA = new HashSet<NOTA_FISCAL_REFERENCIADA>();
        }
    
        public int NF_ID { get; set; }
        public int NF_TIPO { get; set; }
        public int NF_NUMERO { get; set; }
        public string NF_SERIE { get; set; }
        public Nullable<System.DateTime> NF_DATA_EMISSAO { get; set; }
        public Nullable<System.DateTime> NF_DATA_SAIDA { get; set; }
        public Nullable<decimal> NF_BASE_CALC_ICMS { get; set; }
        public Nullable<decimal> NF_VLR_ICMS { get; set; }
        public Nullable<decimal> NF_BASE_CALC_ST { get; set; }
        public Nullable<decimal> NF_VLR_ST { get; set; }
        public Nullable<decimal> NF_VLR_FRETE { get; set; }
        public Nullable<decimal> NF_VLR_SEGURO { get; set; }
        public Nullable<decimal> NF_VLR_OUTRAS { get; set; }
        public Nullable<decimal> NF_VLR_IPI { get; set; }
        public Nullable<decimal> NF_VLR_PROD { get; set; }
        public Nullable<decimal> NF_VLR_NOTA { get; set; }
        public Nullable<decimal> NF_VLR_DESCONTO { get; set; }
        public string NF_CHAVE { get; set; }
        public string NF_NOTA_XML { get; set; }
        public Nullable<int> FOR_ID { get; set; }
        public string CFOP { get; set; }
        public Nullable<int> NF_FRETE_TIPO { get; set; }
        public string NF_RNTRC { get; set; }
        public string NF_PLACA { get; set; }
        public Nullable<decimal> NF_QTDE { get; set; }
        public string NF_ESPECIE { get; set; }
        public string NF_MARCA { get; set; }
        public Nullable<decimal> NF_PESO_BRUTO { get; set; }
        public Nullable<decimal> NF_PESO_LIQUIDO { get; set; }
        public Nullable<int> TRA_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string PED_NUM_PEDIDO { get; set; }
        public string NF_PLACA_UF { get; set; }
        public string NF_NUMERACAO { get; set; }
        public Nullable<System.DateTime> NF_DATA_ENTRADA { get; set; }
        public string NF_PROTOCOLO_AUT { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public string CFOPENT { get; set; }
        public Nullable<decimal> NF_VLR_PIS { get; set; }
        public Nullable<decimal> NF_VLR_COFINS { get; set; }
        public Nullable<int> NF_TIPO_LIGACAO { get; set; }
        public Nullable<int> NF_COD_GRUPO_TENSAO { get; set; }
        public string NF_COD_CONSUMO { get; set; }
        public string NF_HORA_SAIDA { get; set; }
        public string NF_STATUS { get; set; }
        public string NF_INF_COMPLEMENTAR { get; set; }
        public Nullable<System.DateTime> NF_DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> NF_DATA_ALTERACAO { get; set; }
        public string NF_COD_SIT { get; set; }
        public Nullable<decimal> NF_VLR_SERVICO { get; set; }
        public Nullable<decimal> NF_BASE_CALC_ISSQN { get; set; }
        public Nullable<decimal> NF_VLR_ISSQN { get; set; }
        public string TDF_ID { get; set; }
        public string NF_PATH_ARQUIVO { get; set; }
        public Nullable<decimal> NF_ALIQ_ICMS_SERV { get; set; }
        public string CST_ID_SERV { get; set; }
        public byte[] NF_ARQUIVO { get; set; }
        public string NF_EMAIL { get; set; }
        public string NF_NOME_ARQUIVO { get; set; }
        public byte[] NF_BINARIO_ARQUIVO { get; set; }
        public string CTR_NUM_CONTRATO { get; set; }
        public Nullable<int> IPE_ID { get; set; }
        public string NF_NUMERO_PROTOCOLO { get; set; }
        public string NF_NOME_ARQ_EVENTO { get; set; }
        public byte[] NF_ARQ_EVENTO { get; set; }
        public Nullable<int> NST_ID { get; set; }
        public Nullable<bool> NF_EVENTO_ANEXADO { get; set; }
        public Nullable<decimal> NF_VLR_FCP { get; set; }
        public Nullable<decimal> NF_VLR_FCP_ST { get; set; }
        public Nullable<decimal> NF_VLR_FCP_ST_RETIDO { get; set; }
        public Nullable<decimal> NF_VLR_IPE_DEVOLVIDO { get; set; }
        public Nullable<int> PPI_ID { get; set; }
        public Nullable<bool> NF_NOTA_ANTECIPADA { get; set; }
        public Nullable<decimal> NF_VLR_INSS { get; set; }
        public Nullable<decimal> NF_VLR_IR { get; set; }
        public Nullable<decimal> NF_VLR_CSLL { get; set; }
        public Nullable<decimal> NF_VLR_ISS { get; set; }
        public Nullable<decimal> NF_VLR_ISS_RETIDO { get; set; }
        public Nullable<decimal> NF_ALIQUODA { get; set; }
        public Nullable<bool> NF_AVULSA { get; set; }
        public string NF_COD_VERIFICACAO { get; set; }
    
        public virtual CFOP_TABLE CFOP_TABLE { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual CST CST { get; set; }
        public virtual EMPRESA_REF EMPRESA_REF { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual ITEM_PEDIDO ITEM_PEDIDO { get; set; }
        public virtual ICollection<NOTA_FISCAL_EVENTO> NOTA_FISCAL_EVENTO { get; set; }
        public virtual ICollection<NOTA_FISCAL_ITEM> NOTA_FISCAL_ITEM { get; set; }
        public virtual ICollection<NOTA_FISCAL_LOTE_ITEM> NOTA_FISCAL_LOTE_ITEM { get; set; }
        public virtual NOTA_FISCAL_SITUACAO NOTA_FISCAL_SITUACAO { get; set; }
        public virtual ICollection<NOTA_FISCAL_REFERENCIADA> NOTA_FISCAL_REFERENCIADA { get; set; }
        public virtual TIPO_DOC_FISCAL TIPO_DOC_FISCAL { get; set; }
        public virtual TRANSPORTADOR TRANSPORTADOR { get; set; }
        public virtual UF UF { get; set; }
        public virtual NOTA_FISCAL_STATUS NOTA_FISCAL_STATUS { get; set; }
        public virtual NOTA_FISCAL_TIPO NOTA_FISCAL_TIPO { get; set; }
        public virtual PROPOSTA_ITEM PROPOSTA_ITEM { get; set; }
    }
}
