//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_FISCAL_EVENTO
    {
        public int NEV_ID { get; set; }
        public Nullable<int> NIT_ID { get; set; }
        public Nullable<int> NF_ID { get; set; }
        public string NEV_NUMERO_PROTOCOLO { get; set; }
        public string NEV_JUSTIFICATIVA { get; set; }
        public string NEV_ID_EVENTO { get; set; }
        public Nullable<System.DateTime> NEV_DATA { get; set; }
        public string NEV_CNPJ { get; set; }
        public string NEV_DESC_CARTA_CORRECAO { get; set; }
        public string NEV_COND_USO { get; set; }
        public Nullable<int> NEV_COD_RETORNO { get; set; }
        public string NEV_COD_DESCRICAO_RETORNO { get; set; }
        public string NEV_ARQUIVO_NOME { get; set; }
        public byte[] NEV_ARQUIVO { get; set; }
    
        public virtual NOTA_FISCAL NOTA_FISCAL { get; set; }
        public virtual NOTA_FISCAL_LOTE_ITEM_TIPO NOTA_FISCAL_LOTE_ITEM_TIPO { get; set; }
    }
}
