//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_FISCAL_LOTE_TIPO
    {
        public NOTA_FISCAL_LOTE_TIPO()
        {
            this.NOTA_FISCAL_LOTE = new HashSet<NOTA_FISCAL_LOTE>();
        }
    
        public int NLT_ID { get; set; }
        public string NLT_DESCRICAO { get; set; }
    
        public virtual ICollection<NOTA_FISCAL_LOTE> NOTA_FISCAL_LOTE { get; set; }
    }
}
