//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_FISCAL_LOTE_ITEM_MSG
    {
        public int NLM_ID { get; set; }
        public Nullable<int> NLI_ID { get; set; }
        public string NLM_COD { get; set; }
        public string NLM_MSG { get; set; }
        public string NLM_CORRECAO { get; set; }
    
        public virtual NOTA_FISCAL_LOTE_ITEM NOTA_FISCAL_LOTE_ITEM { get; set; }
    }
}
