//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class OCORRENCIA_REMESSA
    {
        public OCORRENCIA_REMESSA()
        {
            this.PARCELA_ALOCADA = new HashSet<PARCELA_ALOCADA>();
        }
    
        public string BAN_ID { get; set; }
        public string OCM_CODIGO { get; set; }
        public string OCM_DESCRICAO { get; set; }
    
        public virtual BANCOS BANCOS { get; set; }
        public virtual ICollection<PARCELA_ALOCADA> PARCELA_ALOCADA { get; set; }
    }
}
