//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCELAS
    {
        public PARCELAS()
        {
            this.AGENDA_COBRANCA = new HashSet<AGENDA_COBRANCA>();
            this.CNAB_ARQUIVOS_ITEM = new HashSet<CNAB_ARQUIVOS_ITEM>();
            this.PARCELA_ALOCADA = new HashSet<PARCELA_ALOCADA>();
            this.PARCELA_LIQUIDACAO = new HashSet<PARCELA_LIQUIDACAO>();
            this.PROPOSTA = new HashSet<PROPOSTA>();
        }
    
        public string PAR_NUM_PARCELA { get; set; }
        public string CTR_NUM_CONTRATO { get; set; }
        public int EMP_ID { get; set; }
        public System.DateTime PAR_DATA_VENCTO { get; set; }
        public Nullable<decimal> PAR_VLR_PARCELA { get; set; }
        public Nullable<decimal> PAR_MORA_MES { get; set; }
        public string PAR_CART_ALOC { get; set; }
        public Nullable<System.DateTime> PAR_DATA_ALOC { get; set; }
        public Nullable<System.DateTime> PAR_DATA_REIMPRESSAO { get; set; }
        public Nullable<decimal> PAR_VLR_PAGO { get; set; }
        public Nullable<System.DateTime> PAR_DATA_PAGTO { get; set; }
        public string PAR_NOSSO_NUMERO { get; set; }
        public string PAR_CEDENTE { get; set; }
        public string PAR_SITUACAO { get; set; }
        public string BAN_ID { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string USU_LOGIN { get; set; }
        public string USU_LOGIN_PRORROGACAO { get; set; }
        public Nullable<System.DateTime> DATA_PRORROGACAO { get; set; }
        public Nullable<int> CTA_ID { get; set; }
        public string PAR_REMESSA { get; set; }
        public Nullable<int> PGT_ID { get; set; }
        public string PAR_TRANSMITIDO { get; set; }
        public string PAR_CHAVE_TRANSACAO { get; set; }
        public string PAR_URL_BOLETO { get; set; }
        public string PAR_CODIGO_DE_BARRAS { get; set; }
        public Nullable<int> TPG_ID { get; set; }
        public string PAR_STATUS_TRANSACAO { get; set; }
        public Nullable<int> IPE_ID { get; set; }
        public Nullable<bool> PAR_PARCELA_DO_PEDIDO { get; set; }
        public string PAR_COD_LEGADO { get; set; }
        public string ORDER_KEY { get; set; }
        public string ORDER_KEY_REF { get; set; }
        public Nullable<int> PAR_SEQ_PARCELA { get; set; }
        public bool PAR_PODE_ALOCAR { get; set; }
        public Nullable<int> REM_ID { get; set; }
        public string AUTHORIZATION_CODE { get; set; }
        public Nullable<int> PAR_TIPO_ALOC { get; set; }
        public Nullable<int> PPI_ID { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<bool> PAR_ALOC_AUTOMATICA { get; set; }
        public Nullable<decimal> PAR_VLR_BOLETO { get; set; }
        public Nullable<System.DateTime> PAR_VENC_BOLETO { get; set; }
        public Nullable<int> CNQ_ID { get; set; }
        public Nullable<bool> PAR_BAIXA_MANUAL { get; set; }
        public Nullable<int> AGC_ID { get; set; }
        public Nullable<bool> PAR_SEG_VIA { get; set; }
        public Nullable<int> IFF_ID { get; set; }
        public Nullable<decimal> PAR_VLR_BRUTO { get; set; }
        public Nullable<System.DateTime> PAR_DATA_AGEN_ENVIO { get; set; }
        public Nullable<System.DateTime> PAR_DATA_ENVIO { get; set; }
        public Nullable<bool> PAR_BOLETO_AVULSO { get; set; }
        public Nullable<bool> PAR_PRIMEIRA_PARCELA { get; set; }
    
        public virtual ICollection<AGENDA_COBRANCA> AGENDA_COBRANCA { get; set; }
        public virtual BANCOS BANCOS { get; set; }
        public virtual CNAB_ARQUIVOS CNAB_ARQUIVOS { get; set; }
        public virtual ICollection<CNAB_ARQUIVOS_ITEM> CNAB_ARQUIVOS_ITEM { get; set; }
        public virtual CONTA_REF CONTA_REF { get; set; }
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual EMPRESA_REF EMPRESA_REF { get; set; }
        public virtual INFO_FATURA INFO_FATURA { get; set; }
        public virtual ITEM_PEDIDO ITEM_PEDIDO { get; set; }
        public virtual ICollection<PARCELA_ALOCADA> PARCELA_ALOCADA { get; set; }
        public virtual ICollection<PARCELA_LIQUIDACAO> PARCELA_LIQUIDACAO { get; set; }
        public virtual PARCELAS_REMESSA PARCELAS_REMESSA { get; set; }
        public virtual PEDIDO_PAGAMENTO PEDIDO_PAGAMENTO { get; set; }
        public virtual PROPOSTA_ITEM PROPOSTA_ITEM { get; set; }
        public virtual TIPO_PAGAMENTO TIPO_PAGAMENTO { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
    }
}
