//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCELA_ALOCADA
    {
        public int ALO_NOSSO_NUMERO { get; set; }
        public string PAR_NUM_PARCELA { get; set; }
        public string PAR_REMESSA { get; set; }
        public int CTA_ID { get; set; }
        public string OCM_CODIGO { get; set; }
        public Nullable<System.DateTime> ALO_REM_DATA_OCORRENCIA { get; set; }
        public string OCT_CODIGO { get; set; }
        public Nullable<System.DateTime> ALO_RET_DATA_OCORRENCIA { get; set; }
        public string OCE_CODIGO { get; set; }
        public string BAN_ID { get; set; }
        public Nullable<System.DateTime> ALO_DATA_ALOCACAO { get; set; }
        public Nullable<System.DateTime> ALO_DATA_TRANSMISSAO { get; set; }
        public Nullable<System.DateTime> ALO_DATA_DESALOCACAO { get; set; }
        public int REM_ID { get; set; }
    
        public virtual CONTA_REF CONTA_REF { get; set; }
        public virtual OCORRENCIA_ERRO OCORRENCIA_ERRO { get; set; }
        public virtual OCORRENCIA_REMESSA OCORRENCIA_REMESSA { get; set; }
        public virtual OCORRENCIA_RETORNO OCORRENCIA_RETORNO { get; set; }
        public virtual PARCELAS PARCELAS { get; set; }
        public virtual PARCELAS_REMESSA PARCELAS_REMESSA { get; set; }
    }
}
