//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PAGAMENTO
    {
        public PEDIDO_PAGAMENTO()
        {
            this.ITEM_PEDIDO_PEDIDO_PAGAMENTO = new HashSet<ITEM_PEDIDO_PEDIDO_PAGAMENTO>();
            this.PARCELAS = new HashSet<PARCELAS>();
        }
    
        public int PGT_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> PED_CRM_ID { get; set; }
        public Nullable<int> TPG_ID { get; set; }
        public Nullable<decimal> PGT_VLR_TOTAL { get; set; }
        public Nullable<int> PGT_QTDE_PARCELAS { get; set; }
        public Nullable<decimal> PGT_VLR_ENTRADA { get; set; }
        public Nullable<decimal> PGT_VLR_PARCELA { get; set; }
        public Nullable<System.DateTime> PGT_SEGUNDO_VENCTO { get; set; }
        public Nullable<int> PGT_TIPO_DOCUMENTO { get; set; }
        public string PGT_NUMERO_DOCUMENTO { get; set; }
        public string PGT_BANCO { get; set; }
        public Nullable<System.DateTime> PGT_CHEQUE_BOM_PARA { get; set; }
        public string PGT_OBS { get; set; }
        public string PGT_CODIGO_CARTAO { get; set; }
        public Nullable<System.DateTime> PGT_VENCIMENTO_CARTAO { get; set; }
        public Nullable<bool> PGT_ENTRADA { get; set; }
        public Nullable<System.DateTime> PGT_DATA_PAGAMENTO { get; set; }
        public Nullable<bool> PGT_PAGO { get; set; }
        public Nullable<System.DateTime> PGT_DATA_VENCIMENTO { get; set; }
        public string PGT_CHAVE_TRANSACAO { get; set; }
        public string PGT_URL_BOLETO { get; set; }
        public string PGT_CODIGO_DE_BARRAS { get; set; }
        public string PGT_STATUS_TRANSACAO { get; set; }
        public string ORDER_KEY { get; set; }
        public string ORDER_KEY_REF { get; set; }
    
        public virtual ICollection<ITEM_PEDIDO_PEDIDO_PAGAMENTO> ITEM_PEDIDO_PEDIDO_PAGAMENTO { get; set; }
        public virtual ICollection<PARCELAS> PARCELAS { get; set; }
        public virtual PEDIDO_CRM PEDIDO_CRM { get; set; }
        public virtual TIPO_PAGAMENTO TIPO_PAGAMENTO { get; set; }
    }
}
