//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTOS
    {
        public PRODUTOS()
        {
            this.ASSINATURA = new HashSet<ASSINATURA>();
            this.NOTA_FISCAL_ITEM = new HashSet<NOTA_FISCAL_ITEM>();
            this.PRODUTO_COMPOSICAO_ITEM = new HashSet<PRODUTO_COMPOSICAO_ITEM>();
            this.PRODUTO_EAN = new HashSet<PRODUTO_EAN>();
            this.PRODUTO_FORNECEDOR = new HashSet<PRODUTO_FORNECEDOR>();
            this.PRODUTO_HISTORICO = new HashSet<PRODUTO_HISTORICO>();
            this.PRODUTO_PERFIL = new HashSet<PRODUTO_PERFIL>();
            this.URA_PRODUTO = new HashSet<URA_PRODUTO>();
            this.AREA_CONSULTORIA = new HashSet<AREA_CONSULTORIA>();
        }
    
        public int PRO_ID { get; set; }
        public string PRO_SIGLA { get; set; }
        public Nullable<int> PRO_ID_DERVADO { get; set; }
        public string PRO_MOD_CARTA_URA { get; set; }
        public Nullable<int> PRO_TIPO_REMESSA { get; set; }
        public Nullable<int> PRO_RECEBE_MALA { get; set; }
        public Nullable<int> PRO_RECEBE_PASTA_SN { get; set; }
        public Nullable<int> PRO_PRODUTO_ACABADO { get; set; }
        public Nullable<int> PRO_STATUS { get; set; }
        public string PRO_EMITE_NF { get; set; }
        public string NCM_ID { get; set; }
        public int GRUPO_ID { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string PRO_UN_COMPRA { get; set; }
        public string PRO_UN_VEND { get; set; }
        public Nullable<decimal> PRO_PRECO_COMPRA { get; set; }
        public Nullable<decimal> PRO_PRECO_CUSTO { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<decimal> PRO_PRECO_VENDA { get; set; }
        public Nullable<int> TIPO_PRO { get; set; }
        public string PRO_NOME { get; set; }
        public Nullable<int> TPC_ID { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public string USU_LOGIN_EXCLUSAO { get; set; }
        public bool PRO_URA { get; set; }
        public bool PRO_PORTAL { get; set; }
        public bool PRO_PORTAL_ST { get; set; }
        public bool PRO_VENDA { get; set; }
        public Nullable<int> FAM_ID { get; set; }
        public Nullable<bool> PRO_IMPRESSO { get; set; }
        public Nullable<int> LIN_PRO_ID { get; set; }
        public Nullable<int> OAC_ID { get; set; }
        public Nullable<int> PRO_QTD_CONSULTA_PADRAO { get; set; }
        public Nullable<int> PRO_CODIGO_CORREIO { get; set; }
        public string PRO_SIGLA_CORREIO { get; set; }
        public bool PRO_REMESSA_SEMANAL { get; set; }
    
        public virtual AREAS AREAS { get; set; }
        public virtual ICollection<ASSINATURA> ASSINATURA { get; set; }
        public virtual GRUPO GRUPO { get; set; }
        public virtual LINHA_PRODUTO LINHA_PRODUTO { get; set; }
        public virtual ICollection<NOTA_FISCAL_ITEM> NOTA_FISCAL_ITEM { get; set; }
        public virtual ORIGEM_ACESSO ORIGEM_ACESSO { get; set; }
        public virtual ICollection<PRODUTO_COMPOSICAO_ITEM> PRODUTO_COMPOSICAO_ITEM { get; set; }
        public virtual ICollection<PRODUTO_EAN> PRODUTO_EAN { get; set; }
        public virtual PRODUTO_FAMILIA PRODUTO_FAMILIA { get; set; }
        public virtual ICollection<PRODUTO_FORNECEDOR> PRODUTO_FORNECEDOR { get; set; }
        public virtual ICollection<PRODUTO_HISTORICO> PRODUTO_HISTORICO { get; set; }
        public virtual ICollection<PRODUTO_PERFIL> PRODUTO_PERFIL { get; set; }
        public virtual TIPO_PROD_COMPORTAMENTO TIPO_PROD_COMPORTAMENTO { get; set; }
        public virtual TIPO_PRODUTO TIPO_PRODUTO { get; set; }
        public virtual UNIDADE_MEDIDA UNIDADE_MEDIDA { get; set; }
        public virtual UNIDADE_MEDIDA UNIDADE_MEDIDA1 { get; set; }
        public virtual ICollection<URA_PRODUTO> URA_PRODUTO { get; set; }
        public virtual ICollection<AREA_CONSULTORIA> AREA_CONSULTORIA { get; set; }
    }
}
