//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_COMPOSICAO
    {
        public PRODUTO_COMPOSICAO()
        {
            this.AREA_CONSULTORIA_CURSO = new HashSet<AREA_CONSULTORIA_CURSO>();
            this.ASSINATURA = new HashSet<ASSINATURA>();
            this.CAMPANHA_VENDAS_PRODUTO_COMPOSICAO = new HashSet<CAMPANHA_VENDAS_PRODUTO_COMPOSICAO>();
            this.CARRINHO_COMPRAS_ITEM = new HashSet<CARRINHO_COMPRAS_ITEM>();
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.IMPORTACAO_SUSPECT = new HashSet<IMPORTACAO_SUSPECT>();
            this.ITEM_PEDIDO = new HashSet<ITEM_PEDIDO>();
            this.NOTA_FISCAL_CONFIG = new HashSet<NOTA_FISCAL_CONFIG>();
            this.NOTA_FISCAL_ITEM = new HashSet<NOTA_FISCAL_ITEM>();
            this.PEDIDO_CRM = new HashSet<PEDIDO_CRM>();
            this.PRODUTO_COMPOSICAO_INFO_MARKETING = new HashSet<PRODUTO_COMPOSICAO_INFO_MARKETING>();
            this.PRODUTO_COMPOSICAO_ITEM = new HashSet<PRODUTO_COMPOSICAO_ITEM>();
            this.PRODUTO_COMPOSICAO1 = new HashSet<PRODUTO_COMPOSICAO>();
            this.PRODUTO_COMPOSICAO_TIPO_PERIODO = new HashSet<PRODUTO_COMPOSICAO_TIPO_PERIODO>();
            this.PROPOSTA_ITEM = new HashSet<PROPOSTA_ITEM>();
            this.PROPOSTA = new HashSet<PROPOSTA>();
            this.TABELA_PRECO = new HashSet<TABELA_PRECO>();
        }
    
        public int CMP_ID { get; set; }
        public string CMP_DESCRICAO { get; set; }
        public string CMP_NOME_ESTRANGEIRO { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public int TIPO_PRO_ID { get; set; }
        public Nullable<decimal> CMP_VLR_VENDA { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public string USU_LOGIN_EXCLUSAO { get; set; }
        public bool CMP_PRO_INTERESSE { get; set; }
        public Nullable<int> CMP_ID_TRANSF { get; set; }
        public string UEN_ID { get; set; }
        public Nullable<int> TIPO_ENVIO_ID { get; set; }
        public Nullable<int> LIN_PRO_ID { get; set; }
        public Nullable<int> TPV_ID { get; set; }
        public Nullable<int> CMP_ID_ORIGEM { get; set; }
        public Nullable<int> TIPO_VENDA_ID { get; set; }
        public Nullable<bool> CMP_RENOVACAO { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<bool> CMP_EXIBIR_VITRINE { get; set; }
        public string CMP_DESCRICAO_VITRINE { get; set; }
        public string CMP_MUNDIPAGG_PLANO_ID { get; set; }
    
        public virtual ICollection<AREA_CONSULTORIA_CURSO> AREA_CONSULTORIA_CURSO { get; set; }
        public virtual ICollection<ASSINATURA> ASSINATURA { get; set; }
        public virtual ICollection<CAMPANHA_VENDAS_PRODUTO_COMPOSICAO> CAMPANHA_VENDAS_PRODUTO_COMPOSICAO { get; set; }
        public virtual ICollection<CARRINHO_COMPRAS_ITEM> CARRINHO_COMPRAS_ITEM { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<IMPORTACAO_SUSPECT> IMPORTACAO_SUSPECT { get; set; }
        public virtual ICollection<ITEM_PEDIDO> ITEM_PEDIDO { get; set; }
        public virtual LINHA_PRODUTO LINHA_PRODUTO { get; set; }
        public virtual ICollection<NOTA_FISCAL_CONFIG> NOTA_FISCAL_CONFIG { get; set; }
        public virtual ICollection<NOTA_FISCAL_ITEM> NOTA_FISCAL_ITEM { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM { get; set; }
        public virtual ICollection<PRODUTO_COMPOSICAO_INFO_MARKETING> PRODUTO_COMPOSICAO_INFO_MARKETING { get; set; }
        public virtual ICollection<PRODUTO_COMPOSICAO_ITEM> PRODUTO_COMPOSICAO_ITEM { get; set; }
        public virtual ICollection<PRODUTO_COMPOSICAO> PRODUTO_COMPOSICAO1 { get; set; }
        public virtual PRODUTO_COMPOSICAO PRODUTO_COMPOSICAO2 { get; set; }
        public virtual ICollection<PRODUTO_COMPOSICAO_TIPO_PERIODO> PRODUTO_COMPOSICAO_TIPO_PERIODO { get; set; }
        public virtual TIPO_PRODUTO_COMPOSICAO TIPO_PRODUTO_COMPOSICAO { get; set; }
        public virtual TIPO_VENDA TIPO_VENDA { get; set; }
        public virtual ICollection<PROPOSTA_ITEM> PROPOSTA_ITEM { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
        public virtual ICollection<TABELA_PRECO> TABELA_PRECO { get; set; }
    }
}
