//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSTA
    {
        public PROPOSTA()
        {
            this.PEDIDO_CRM = new HashSet<PEDIDO_CRM>();
            this.PEDIDO_PARTICIPANTE = new HashSet<PEDIDO_PARTICIPANTE>();
            this.PROPOSTA_ITEM = new HashSet<PROPOSTA_ITEM>();
        }
    
        public int PRT_ID { get; set; }
        public Nullable<int> TPP_ID { get; set; }
        public Nullable<int> CMP_ID { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public Nullable<int> PST_ID { get; set; }
        public string PAR_NUM_PARCELA { get; set; }
        public Nullable<int> RG_ID { get; set; }
        public Nullable<int> REP_ID { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_CONFIRMACAO_PAGAMENTO { get; set; }
        public Nullable<decimal> PRT_VALOR_UNITARIO { get; set; }
        public Nullable<int> PRT_QTD { get; set; }
        public Nullable<int> PRT_QTD_PARCELAS { get; set; }
        public Nullable<decimal> PRT_VALOR_ENTRADA { get; set; }
        public Nullable<decimal> PRT_VALOR_PARCELA { get; set; }
        public Nullable<decimal> PRT_VALOR_TOTAL { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string PRT_OBSERVACOES { get; set; }
        public Nullable<int> PRT_QTD_CONSULTAS { get; set; }
        public Nullable<System.DateTime> PRT_DATA_FATURAMENTO_AGENDADA { get; set; }
        public Nullable<int> REP_ID_EMITENTE { get; set; }
        public string CAR_ID { get; set; }
        public Nullable<int> RLI_ID { get; set; }
        public Nullable<int> CVE_ID { get; set; }
        public string PRT_EMAIL_CONTATO { get; set; }
        public string PRT_EMAIL_NOTA_FISCAL { get; set; }
        public Nullable<int> UEN_ID { get; set; }
        public Nullable<bool> PRT_EMPRESA_DO_SIMPLES { get; set; }
        public Nullable<bool> PRT_POR_CENTO_FATURADO { get; set; }
        public string PRT_OBSERVACOES_NOTA_FISCAL { get; set; }
        public Nullable<int> TNE_ID { get; set; }
        public Nullable<int> ENV_ID { get; set; }
        public Nullable<int> MPG_ASN_ID { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual CARTEIRA CARTEIRA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPRESA_REF EMPRESA_REF { get; set; }
        public virtual ENDERECO_VENDA ENDERECO_VENDA { get; set; }
        public virtual MUNDIPAGG_ASSINATURA MUNDIPAGG_ASSINATURA { get; set; }
        public virtual PARCELAS PARCELAS { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM { get; set; }
        public virtual ICollection<PEDIDO_PARTICIPANTE> PEDIDO_PARTICIPANTE { get; set; }
        public virtual PEDIDO_STATUS PEDIDO_STATUS { get; set; }
        public virtual PRODUTO_COMPOSICAO PRODUTO_COMPOSICAO { get; set; }
        public virtual ICollection<PROPOSTA_ITEM> PROPOSTA_ITEM { get; set; }
        public virtual REGIAO REGIAO { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE { get; set; }
        public virtual REPRESENTANTE REPRESENTANTE1 { get; set; }
        public virtual TIPO_PROPOSTA TIPO_PROPOSTA { get; set; }
        public virtual UEN UEN { get; set; }
        public virtual REGISTRO_LIBERACAO REGISTRO_LIBERACAO { get; set; }
        public virtual TIPO_NEGOCIACAO TIPO_NEGOCIACAO { get; set; }
    }
}
