//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSTA_ITEM
    {
        public PROPOSTA_ITEM()
        {
            this.HISTORICO_ATENDIMENTO = new HashSet<HISTORICO_ATENDIMENTO>();
            this.HISTORICO_PEDIDO = new HashSet<HISTORICO_PEDIDO>();
            this.ITEM_PEDIDO = new HashSet<ITEM_PEDIDO>();
            this.NOTA_FISCAL = new HashSet<NOTA_FISCAL>();
            this.NOTA_FISCAL_LOTE_ITEM = new HashSet<NOTA_FISCAL_LOTE_ITEM>();
            this.PARCELAS = new HashSet<PARCELAS>();
            this.PEDIDO_PARTICIPANTE = new HashSet<PEDIDO_PARTICIPANTE>();
            this.PROPOSTA_ITEM_COMPROVANTE = new HashSet<PROPOSTA_ITEM_COMPROVANTE>();
        }
    
        public int PPI_ID { get; set; }
        public Nullable<int> PRT_ID { get; set; }
        public Nullable<decimal> PPI_VALOR_UNITARIO { get; set; }
        public Nullable<int> PPI_QTD { get; set; }
        public Nullable<decimal> PPI_TOTAL { get; set; }
        public Nullable<int> CMP_ID { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public Nullable<decimal> PPI_DESCONTO { get; set; }
        public Nullable<int> CMP_ID_1 { get; set; }
        public Nullable<int> TPG_ID { get; set; }
        public Nullable<int> PPI_QTD_PARCELAS { get; set; }
        public Nullable<decimal> PPI_VALOR_ENTRADA { get; set; }
        public Nullable<decimal> PPI_VALOR_PARCELA { get; set; }
        public Nullable<System.DateTime> PPI_DATA_VENCIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public Nullable<int> PST_ID { get; set; }
        public string COD_LEGADO { get; set; }
        public string PAR_OBSERVACOES { get; set; }
        public Nullable<bool> PPI_ACESSOS_CONCEDIDOS { get; set; }
        public Nullable<System.DateTime> PPI_DATA_VENCIMENTO_SEG_PARCELA { get; set; }
        public string ASN_NUM_ASSINATURA { get; set; }
        public Nullable<int> PPI_QTD_CONSULTA { get; set; }
        public Nullable<bool> PPI_CORTESIA { get; set; }
        public Nullable<System.DateTime> PPI_DATA_PARA_FATURAMENTO { get; set; }
        public string PPI_PERIODO_FAT { get; set; }
        public string PPI_SEMANA_FAT { get; set; }
        public Nullable<int> PPI_PERIODO_MES_BONUS { get; set; }
        public string PPI_ASN_NUM_ASS_CANC { get; set; }
        public Nullable<bool> PPI_GERA_NOTA { get; set; }
        public Nullable<int> RLI_ID { get; set; }
        public Nullable<int> RIT_ID { get; set; }
        public Nullable<int> CVE_ID { get; set; }
        public Nullable<decimal> PPI_VALOR_UNITARIO_PRODUTO { get; set; }
        public Nullable<int> IFF_ID { get; set; }
        public Nullable<decimal> PPI_VALOR_BRUTO_PARCELA { get; set; }
        public Nullable<int> IFF_ID_ENTRADA { get; set; }
        public Nullable<decimal> PPI_VALOR_BRUTO_ENTRADA { get; set; }
        public Nullable<int> LOC_ID { get; set; }
        public string PRT_IDENTIFICACAO_TURMA { get; set; }
    
        public virtual ASSINATURA ASSINATURA { get; set; }
        public virtual ASSINATURA ASSINATURA1 { get; set; }
        public virtual CAMPANHA_VENDA CAMPANHA_VENDA { get; set; }
        public virtual ICollection<HISTORICO_ATENDIMENTO> HISTORICO_ATENDIMENTO { get; set; }
        public virtual ICollection<HISTORICO_PEDIDO> HISTORICO_PEDIDO { get; set; }
        public virtual INFO_FATURA INFO_FATURA { get; set; }
        public virtual INFO_FATURA INFO_FATURA1 { get; set; }
        public virtual ICollection<ITEM_PEDIDO> ITEM_PEDIDO { get; set; }
        public virtual LOCALIZACAO_CURSO LOCALIZACAO_CURSO { get; set; }
        public virtual ICollection<NOTA_FISCAL> NOTA_FISCAL { get; set; }
        public virtual ICollection<NOTA_FISCAL_LOTE_ITEM> NOTA_FISCAL_LOTE_ITEM { get; set; }
        public virtual ICollection<PARCELAS> PARCELAS { get; set; }
        public virtual ICollection<PEDIDO_PARTICIPANTE> PEDIDO_PARTICIPANTE { get; set; }
        public virtual PEDIDO_STATUS PEDIDO_STATUS { get; set; }
        public virtual PRODUTO_COMPOSICAO PRODUTO_COMPOSICAO { get; set; }
        public virtual PRODUTO_COMPOSICAO_ITEM PRODUTO_COMPOSICAO_ITEM { get; set; }
        public virtual PROPOSTA PROPOSTA { get; set; }
        public virtual ICollection<PROPOSTA_ITEM_COMPROVANTE> PROPOSTA_ITEM_COMPROVANTE { get; set; }
        public virtual REGISTRO_LIBERACAO REGISTRO_LIBERACAO { get; set; }
        public virtual REGISTRO_LIBERACAO_ITEM REGISTRO_LIBERACAO_ITEM { get; set; }
        public virtual TIPO_PAGAMENTO TIPO_PAGAMENTO { get; set; }
    }
}
