//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_LIBERACAO_TIPO
    {
        public REGISTRO_LIBERACAO_TIPO()
        {
            this.REGISTRO_LIBERACAO = new HashSet<REGISTRO_LIBERACAO>();
        }
    
        public int RLT_ID { get; set; }
        public string RLT_DESCRICAO { get; set; }
    
        public virtual ICollection<REGISTRO_LIBERACAO> REGISTRO_LIBERACAO { get; set; }
    }
}
