//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGIAO
    {
        public REGIAO()
        {
            this.AGENDAMENTO = new HashSet<AGENDAMENTO>();
            this.CARTEIRA = new HashSet<CARTEIRA>();
            this.CONFIG_ALOCACAO = new HashSet<CONFIG_ALOCACAO>();
            this.CONFIG_IMPOSTO_REGIAO = new HashSet<CONFIG_IMPOSTO_REGIAO>();
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.FILA_CADASTRO = new HashSet<FILA_CADASTRO>();
            this.FRANQUIA = new HashSet<FRANQUIA>();
            this.IMPORTACAO_RESULTADO_RODIZIO = new HashSet<IMPORTACAO_RESULTADO_RODIZIO>();
            this.IMPORTACAO_SUSPECT = new HashSet<IMPORTACAO_SUSPECT>();
            this.MUNICIPIO = new HashSet<MUNICIPIO>();
            this.PEDIDO_CRM = new HashSet<PEDIDO_CRM>();
            this.PRIORIDADE_ATENDIMENTO = new HashSet<PRIORIDADE_ATENDIMENTO>();
            this.PROPOSTA = new HashSet<PROPOSTA>();
            this.REGIAO_TABELA_PRECO = new HashSet<REGIAO_TABELA_PRECO>();
            this.REPRESENTANTE = new HashSet<REPRESENTANTE>();
            this.UF = new HashSet<UF>();
        }
    
        public int RG_ID { get; set; }
        public string RG_DESCRICAO { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<bool> RG_FRANQUIA { get; set; }
        public Nullable<int> UEN_ID { get; set; }
    
        public virtual ICollection<AGENDAMENTO> AGENDAMENTO { get; set; }
        public virtual ICollection<CARTEIRA> CARTEIRA { get; set; }
        public virtual ICollection<CONFIG_ALOCACAO> CONFIG_ALOCACAO { get; set; }
        public virtual ICollection<CONFIG_IMPOSTO_REGIAO> CONFIG_IMPOSTO_REGIAO { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual EMPRESA_REF EMPRESA_REF { get; set; }
        public virtual ICollection<FILA_CADASTRO> FILA_CADASTRO { get; set; }
        public virtual ICollection<FRANQUIA> FRANQUIA { get; set; }
        public virtual ICollection<IMPORTACAO_RESULTADO_RODIZIO> IMPORTACAO_RESULTADO_RODIZIO { get; set; }
        public virtual ICollection<IMPORTACAO_SUSPECT> IMPORTACAO_SUSPECT { get; set; }
        public virtual ICollection<MUNICIPIO> MUNICIPIO { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM { get; set; }
        public virtual ICollection<PRIORIDADE_ATENDIMENTO> PRIORIDADE_ATENDIMENTO { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
        public virtual ICollection<REGIAO_TABELA_PRECO> REGIAO_TABELA_PRECO { get; set; }
        public virtual UEN UEN { get; set; }
        public virtual ICollection<REPRESENTANTE> REPRESENTANTE { get; set; }
        public virtual ICollection<UF> UF { get; set; }
    }
}
