//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGIAO_TABELA_PRECO
    {
        public REGIAO_TABELA_PRECO()
        {
            this.ITEM_PEDIDO = new HashSet<ITEM_PEDIDO>();
        }
    
        public int TP_ID { get; set; }
        public int RG_ID { get; set; }
        public Nullable<decimal> RTP_PRECO_VENDA { get; set; }
        public Nullable<System.DateTime> RTP_DATA_ASSOCIACAO { get; set; }
        public Nullable<System.DateTime> RTP_DATA_EXCLUSAO { get; set; }
    
        public virtual ICollection<ITEM_PEDIDO> ITEM_PEDIDO { get; set; }
        public virtual REGIAO REGIAO { get; set; }
        public virtual TABELA_PRECO TABELA_PRECO { get; set; }
    }
}
