//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATORIO_OPERADOR_CONDICIONAL
    {
        public RELATORIO_OPERADOR_CONDICIONAL()
        {
            this.RELATORIO_CONDICAO_RELATORIO_OPERADOR_CONDICIONAL = new HashSet<RELATORIO_CONDICAO_RELATORIO_OPERADOR_CONDICIONAL>();
        }
    
        public int ROC_ID { get; set; }
        public string ROC_DESCRICAO { get; set; }
    
        public virtual ICollection<RELATORIO_CONDICAO_RELATORIO_OPERADOR_CONDICIONAL> RELATORIO_CONDICAO_RELATORIO_OPERADOR_CONDICIONAL { get; set; }
    }
}
