//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPRESENTANTE
    {
        public REPRESENTANTE()
        {
            this.AGENDAMENTO = new HashSet<AGENDAMENTO>();
            this.APURACAO_PREMIACAO_MENSAL = new HashSet<APURACAO_PREMIACAO_MENSAL>();
            this.APURACAO_PREMIACAO_SEMANA = new HashSet<APURACAO_PREMIACAO_SEMANA>();
            this.AREA_CONSULTORIA_REPRESENTANTE = new HashSet<AREA_CONSULTORIA_REPRESENTANTE>();
            this.CARTEIRA_REPRESENTANTE = new HashSet<CARTEIRA_REPRESENTANTE>();
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.FILA_CADASTRO = new HashSet<FILA_CADASTRO>();
            this.HISTORICO_ATENDIMENTO = new HashSet<HISTORICO_ATENDIMENTO>();
            this.HISTORICO_PEDIDO = new HashSet<HISTORICO_PEDIDO>();
            this.IMPORTACAO_HISTORICO = new HashSet<IMPORTACAO_HISTORICO>();
            this.IMPORTACAO_RESULTADO_RODIZIO = new HashSet<IMPORTACAO_RESULTADO_RODIZIO>();
            this.NOTIFICACOES = new HashSet<NOTIFICACOES>();
            this.PEDIDO_CRM = new HashSet<PEDIDO_CRM>();
            this.PEDIDO_CRM1 = new HashSet<PEDIDO_CRM>();
            this.PRIORIDADE_ATENDIMENTO = new HashSet<PRIORIDADE_ATENDIMENTO>();
            this.PRIORIDADE_ATENDIMENTO1 = new HashSet<PRIORIDADE_ATENDIMENTO>();
            this.PROPOSTA = new HashSet<PROPOSTA>();
            this.PROPOSTA1 = new HashSet<PROPOSTA>();
            this.REGISTRO_FATURAMENTO = new HashSet<REGISTRO_FATURAMENTO>();
            this.REGISTRO_LIBERACAO = new HashSet<REGISTRO_LIBERACAO>();
            this.RELATORIO_PERSONALIZADO = new HashSet<RELATORIO_PERSONALIZADO>();
            this.REPRESENTANTE_META = new HashSet<REPRESENTANTE_META>();
            this.SEMANA_PREMIACAO_REPR = new HashSet<SEMANA_PREMIACAO_REPR>();
        }
    
        public int REP_ID { get; set; }
        public string REP_NOME { get; set; }
        public string REP_MATRICULA { get; set; }
        public Nullable<int> REP_ATIVO { get; set; }
        public int REP_VARIAS_CARTEIRAS { get; set; }
        public Nullable<int> UEN_ID { get; set; }
        public Nullable<int> CODIGO_ANTIGO { get; set; }
        public Nullable<int> REGIAO_ID_ANTIGO { get; set; }
        public Nullable<int> RG_ID { get; set; }
        public Nullable<bool> REP_GERENTE { get; set; }
        public Nullable<bool> REP_ADMINISTRATIVO { get; set; }
        public string REP_COD_CARTEIRA_ANTIGO { get; set; }
        public Nullable<int> NRP_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string REGIAO_UF { get; set; }
        public string REP_EMAIL { get; set; }
        public string REP_RAMAL { get; set; }
        public string REP_DDD_TELEFONE { get; set; }
        public string REP_TELEFONE { get; set; }
        public string REP_DDD_TELEFONE2 { get; set; }
        public string REP_TELEFONE2 { get; set; }
        public Nullable<int> REP_ID_SUPERVISOR { get; set; }
        public Nullable<bool> REP_SUPERVISOR { get; set; }
        public Nullable<bool> REP_INATIVO_RODIZIO_IMP { get; set; }
    
        public virtual ICollection<AGENDAMENTO> AGENDAMENTO { get; set; }
        public virtual ICollection<APURACAO_PREMIACAO_MENSAL> APURACAO_PREMIACAO_MENSAL { get; set; }
        public virtual ICollection<APURACAO_PREMIACAO_SEMANA> APURACAO_PREMIACAO_SEMANA { get; set; }
        public virtual ICollection<AREA_CONSULTORIA_REPRESENTANTE> AREA_CONSULTORIA_REPRESENTANTE { get; set; }
        public virtual ICollection<CARTEIRA_REPRESENTANTE> CARTEIRA_REPRESENTANTE { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual EMPRESA_REF EMPRESA_REF { get; set; }
        public virtual ICollection<FILA_CADASTRO> FILA_CADASTRO { get; set; }
        public virtual ICollection<HISTORICO_ATENDIMENTO> HISTORICO_ATENDIMENTO { get; set; }
        public virtual ICollection<HISTORICO_PEDIDO> HISTORICO_PEDIDO { get; set; }
        public virtual ICollection<IMPORTACAO_HISTORICO> IMPORTACAO_HISTORICO { get; set; }
        public virtual ICollection<IMPORTACAO_RESULTADO_RODIZIO> IMPORTACAO_RESULTADO_RODIZIO { get; set; }
        public virtual NIVEL_REPRESENTANTE NIVEL_REPRESENTANTE { get; set; }
        public virtual ICollection<NOTIFICACOES> NOTIFICACOES { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM1 { get; set; }
        public virtual ICollection<PRIORIDADE_ATENDIMENTO> PRIORIDADE_ATENDIMENTO { get; set; }
        public virtual ICollection<PRIORIDADE_ATENDIMENTO> PRIORIDADE_ATENDIMENTO1 { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA1 { get; set; }
        public virtual REGIAO REGIAO { get; set; }
        public virtual ICollection<REGISTRO_FATURAMENTO> REGISTRO_FATURAMENTO { get; set; }
        public virtual ICollection<REGISTRO_LIBERACAO> REGISTRO_LIBERACAO { get; set; }
        public virtual ICollection<RELATORIO_PERSONALIZADO> RELATORIO_PERSONALIZADO { get; set; }
        public virtual ICollection<REPRESENTANTE_META> REPRESENTANTE_META { get; set; }
        public virtual UEN UEN { get; set; }
        public virtual UF UF { get; set; }
        public virtual ICollection<SEMANA_PREMIACAO_REPR> SEMANA_PREMIACAO_REPR { get; set; }
    }
}
