//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELA_PRECO_TIPO_PAGAMENTO
    {
        public int TP_ID { get; set; }
        public int TPG_ID { get; set; }
        public Nullable<System.DateTime> DATA_ASSOCIACAO { get; set; }
    
        public virtual TABELA_PRECO TABELA_PRECO { get; set; }
        public virtual TIPO_PAGAMENTO TIPO_PAGAMENTO { get; set; }
    }
}
