//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELA_PRECO
    {
        public TABELA_PRECO()
        {
            this.REGIAO_TABELA_PRECO = new HashSet<REGIAO_TABELA_PRECO>();
            this.TABELA_PRECO_TIPO_PAGAMENTO = new HashSet<TABELA_PRECO_TIPO_PAGAMENTO>();
        }
    
        public int TP_ID { get; set; }
        public int CMP_ID { get; set; }
        public Nullable<int> TP_MARGEM_NEGOCIACAO { get; set; }
        public Nullable<int> TP_MARGEM_LUCRO { get; set; }
        public Nullable<decimal> TP_PRECO_VENDA { get; set; }
        public Nullable<int> TP_NUM_PARCELAS_MIN { get; set; }
        public Nullable<int> TP_NUM_PARCELAS_MAX { get; set; }
        public string TP_DESCRICAO { get; set; }
        public Nullable<int> TTP_ID { get; set; }
        public Nullable<System.DateTime> TP_DATA_EXCLUSAO { get; set; }
        public Nullable<decimal> TP_PORCENTAGEM_SERVICO { get; set; }
        public Nullable<bool> TP_PERMITIR_CORTESIA_PRIMEIRA_PARCELA { get; set; }
    
        public virtual PRODUTO_COMPOSICAO PRODUTO_COMPOSICAO { get; set; }
        public virtual ICollection<REGIAO_TABELA_PRECO> REGIAO_TABELA_PRECO { get; set; }
        public virtual ICollection<TABELA_PRECO_TIPO_PAGAMENTO> TABELA_PRECO_TIPO_PAGAMENTO { get; set; }
        public virtual TIPO_PERIODO TIPO_PERIODO { get; set; }
    }
}
