//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ENDERECO
    {
        public TIPO_ENDERECO()
        {
            this.CLIENTES_ENDERECO = new HashSet<CLIENTES_ENDERECO>();
        }
    
        public int TP_END_ID { get; set; }
        public string TP_END_DESCRICAO { get; set; }
    
        public virtual ICollection<CLIENTES_ENDERECO> CLIENTES_ENDERECO { get; set; }
    }
}
