//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ATENDIMENTO
    {
        public TIPO_ATENDIMENTO()
        {
            this.HISTORICO_ATENDIMENTO = new HashSet<HISTORICO_ATENDIMENTO>();
        }
    
        public int TIP_ATEND_ID { get; set; }
        public string TIP_ATEND_DESCRICAO { get; set; }
        public string TIP_ATEND_GRUPO { get; set; }
        public Nullable<int> CLA_ATEND_ID { get; set; }
        public Nullable<bool> TIP_EMITE_ETIQUETA { get; set; }
    
        public virtual CLASSIFICACAO_ATENDIMENTO CLASSIFICACAO_ATENDIMENTO { get; set; }
        public virtual ICollection<HISTORICO_ATENDIMENTO> HISTORICO_ATENDIMENTO { get; set; }
    }
}
