//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class UEN
    {
        public UEN()
        {
            this.ASSINATURA = new HashSet<ASSINATURA>();
            this.CARTEIRA = new HashSet<CARTEIRA>();
            this.HISTORICO_ATENDIMENTO = new HashSet<HISTORICO_ATENDIMENTO>();
            this.PEDIDO_CRM = new HashSet<PEDIDO_CRM>();
            this.PROPOSTA = new HashSet<PROPOSTA>();
            this.REGIAO = new HashSet<REGIAO>();
            this.REPRESENTANTE = new HashSet<REPRESENTANTE>();
        }
    
        public int UEN_ID { get; set; }
        public string UEN_DESCRICAO { get; set; }
    
        public virtual ICollection<ASSINATURA> ASSINATURA { get; set; }
        public virtual ICollection<CARTEIRA> CARTEIRA { get; set; }
        public virtual ICollection<HISTORICO_ATENDIMENTO> HISTORICO_ATENDIMENTO { get; set; }
        public virtual ICollection<PEDIDO_CRM> PEDIDO_CRM { get; set; }
        public virtual ICollection<PROPOSTA> PROPOSTA { get; set; }
        public virtual ICollection<REGIAO> REGIAO { get; set; }
        public virtual ICollection<REPRESENTANTE> REPRESENTANTE { get; set; }
    }
}
