//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class URA
    {
        public URA()
        {
            this.HIST_ATEND_URA = new HashSet<HIST_ATEND_URA>();
            this.URA_COAD = new HashSet<URA_COAD>();
            this.URA_CONFIG = new HashSet<URA_CONFIG>();
            this.URA_LOG = new HashSet<URA_LOG>();
            this.URA_PRODUTO = new HashSet<URA_PRODUTO>();
        }
    
        public string URA_ID { get; set; }
        public Nullable<int> URA_STATUS { get; set; }
        public string UF_SIGLA { get; set; }
        public string URA_CONNECTION_STRING { get; set; }
        public Nullable<System.DateTime> URA_DATA_ATUALIZACAO { get; set; }
        public Nullable<int> URA_TIPO_ID { get; set; }
    
        public virtual ICollection<HIST_ATEND_URA> HIST_ATEND_URA { get; set; }
        public virtual UF UF { get; set; }
        public virtual ICollection<URA_COAD> URA_COAD { get; set; }
        public virtual ICollection<URA_CONFIG> URA_CONFIG { get; set; }
        public virtual ICollection<URA_LOG> URA_LOG { get; set; }
        public virtual ICollection<URA_PRODUTO> URA_PRODUTO { get; set; }
        public virtual URA_TIPO URA_TIPO { get; set; }
    }
}
