//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class URA_TP_ATU
    {
        public URA_TP_ATU()
        {
            this.URA_LOG = new HashSet<URA_LOG>();
        }
    
        public int URA_TP_ATU_ID { get; set; }
        public string URA_TP_ATU_DESCRICAO { get; set; }
    
        public virtual ICollection<URA_LOG> URA_LOG { get; set; }
    }
}
