//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class URA_TIPO
    {
        public URA_TIPO()
        {
            this.URA = new HashSet<URA>();
        }
    
        public int URA_TIPO_ID { get; set; }
        public string URA_TIPO_DESCRICAO { get; set; }
    
        public virtual ICollection<URA> URA { get; set; }
    }
}
