//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class URA_CONFIG
    {
        public URA_CONFIG()
        {
            this.URA_PRODUTO_AREA = new HashSet<URA_PRODUTO_AREA>();
        }
    
        public string URA_ID { get; set; }
        public int PRO_ID { get; set; }
        public string UF_SIGLA_ACESSO { get; set; }
        public Nullable<int> URA_ACESSO { get; set; }
    
        public virtual URA URA { get; set; }
        public virtual URA_PRODUTO URA_PRODUTO { get; set; }
        public virtual ICollection<URA_PRODUTO_AREA> URA_PRODUTO_AREA { get; set; }
    }
}
