//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class URGENCIA_NOTIFICACAO
    {
        public URGENCIA_NOTIFICACAO()
        {
            this.NOTIFICACOES = new HashSet<NOTIFICACOES>();
        }
    
        public string URG_NTF_ID { get; set; }
        public string URG_NTF_DESCRICAO { get; set; }
    
        public virtual ICollection<NOTIFICACOES> NOTIFICACOES { get; set; }
    }
}
