//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TITULOS_EM_ATRASO
    {
        public string ASN_NUM_ASSINATURA { get; set; }
        public string CTR_NUM_CONTRATO { get; set; }
        public string PAR_NUM_PARCELA { get; set; }
        public string CLI_NOME { get; set; }
        public System.DateTime PAR_DATA_VENCTO { get; set; }
        public Nullable<decimal> PAR_VLR_PARCELA { get; set; }
        public string ASN_A_C { get; set; }
        public string BAN_ID { get; set; }
        public int CLI_ID { get; set; }
        public Nullable<int> DIAS_ATRASO { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<bool> PAR_PRIMEIRA_PARCELA { get; set; }
        public string PAR_SITUACAO { get; set; }
    }
}
