//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.LEGADO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILS
    {
        public string ASSINATURA { get; set; }
        public string E_MAIL { get; set; }
        public string PRINCIPAL_SN { get; set; }
        public string DT_LISTAGEM_CONF { get; set; }
        public int AUTOID { get; set; }
        public string DH_SUBIR { get; set; }
        public string DH_SUBIU { get; set; }
        public string SETOR { get; set; }
        public string DECISOR { get; set; }
        public Nullable<System.DateTime> DATA_INSERT { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
    }
}
