//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.LEGADO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIST_ATEND
    {
        public System.DateTime DATA_SOLIC { get; set; }
        public string ASSINATURA { get; set; }
        public string HISTORICO { get; set; }
        public string SOLICITANTE { get; set; }
        public string ACAO { get; set; }
        public Nullable<System.DateTime> DATA_RESOLUCAO { get; set; }
        public Nullable<int> GRUPO { get; set; }
        public Nullable<System.DateTime> DATA_EMISSAO_FICHA { get; set; }
        public string DH_SUBIR { get; set; }
        public string DH_SUBIU { get; set; }
        public Nullable<int> SAC_TIPO_ID { get; set; }
    }
}
