//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_FISCAL_TRANSPORTADOR
    {
        public int NFT_ID { get; set; }
        public int NF_TIPO { get; set; }
        public int NF_NUMERO { get; set; }
        public string NF_SERIE { get; set; }
        public Nullable<int> NFT_FRETE_TIPO { get; set; }
        public string NFT_RNTRC { get; set; }
        public string NFT_PLACA { get; set; }
        public Nullable<decimal> NFT_QTDE { get; set; }
        public string NFT_ESPECIE { get; set; }
        public string NFT_MARCA { get; set; }
        public Nullable<decimal> NFT_PESO_BRUTO { get; set; }
        public Nullable<decimal> NFT_PESO_LIQUIDO { get; set; }
        public Nullable<int> TRA_ID { get; set; }
    
        public virtual FORNECECEDOR FORNECECEDOR { get; set; }
    }
}
