//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.CORPORATIVO.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PAGAMENTO_ITEM
    {
        public int EMP_ID { get; set; }
        public int PRE_PEDIDO_ID { get; set; }
        public int PGT_PED_ID { get; set; }
        public int PED_NUM_PEDIDO { get; set; }
        public Nullable<int> PGT_CONFIRMADO { get; set; }
    
        public virtual PEDIDO_PAGAMENTO PEDIDO_PAGAMENTO { get; set; }
    }
}
