
BEGIN TRANSACTION TX1

declare @login varchar(50)
SET @login = 'vpoliceno';



DELETE FROM [dbo].[LOG_OCORRENCIA]
WHERE USU_LOGIN = @login

DELETE FROM [dbo].[PERFIL_USUARIO]
WHERE USU_LOGIN = @login

DELETE FROM [dbo].[USUARIO] 
WHERE USU_LOGIN = @login

COMMIT TRANSACTION TX1

--ROLLBACK TRANSACTION TX1
