/*USE [COADSYS]

ALTER TABLE EMPRESA
ADD EMP_APARECE_PRE_PEDIDO [BIT] NOT NULL DEFAULT 0

GO*/

USE [COADCORP]
ALTER TABLE [REPRESENTANTE]
DROP CONSTRAINT FK_REPRESENTANTE_CARTEIRA

USE [COADCORP]
GO

/****** Object:  Table [dbo].[CARTEIRA_REPRESENTANTE]    Script Date: 07/16/2015 15:50:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CARTEIRA_REPRESENTANTE](
	[CAR_ID] [char](7) NOT NULL,
	[REP_ID] [int] NOT NULL,
	[DATA_ASSOCIACAO] [datetime] NULL,
 CONSTRAINT [PK_REPRESENTANTE_CARTEIRA] PRIMARY KEY CLUSTERED 
(
	[CAR_ID] ASC,
	[REP_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CARTEIRA_REPRESENTANTE]  WITH CHECK ADD  CONSTRAINT [FK_CARTEIRA_REPRESENTANTE_CARTEIRA] FOREIGN KEY([CAR_ID])
REFERENCES [dbo].[CARTEIRA] ([CAR_ID])
GO

ALTER TABLE [dbo].[CARTEIRA_REPRESENTANTE] CHECK CONSTRAINT [FK_CARTEIRA_REPRESENTANTE_CARTEIRA]
GO

ALTER TABLE [dbo].[CARTEIRA_REPRESENTANTE]  WITH CHECK ADD  CONSTRAINT [FK_CARTEIRA_REPRESENTANTE_REPRESENTANTE] FOREIGN KEY([REP_ID])
REFERENCES [dbo].[REPRESENTANTE] ([REP_ID])
GO

ALTER TABLE [dbo].[CARTEIRA_REPRESENTANTE] CHECK CONSTRAINT [FK_CARTEIRA_REPRESENTANTE_REPRESENTANTE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE INSERIR_REPRESENTANTE_CARTEIRA2
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	INSERT INTO [dbo].[CARTEIRA_REPRESENTANTE]
	(REP_ID,CAR_ID, DATA_ASSOCIACAO)
	(SELECT 
		REP_ID,
		CAR_ID,
		GETDATE()
		 FROM 
		 [dbo].[REPRESENTANTE] rep)
		 
END
GO

ALTER TABLE [dbo].[CARTEIRA]
ADD CAR_VARIOS_REPRESENTANTES INT NOT NULL DEFAULT 1
GO

ALTER TABLE [dbo].[REPRESENTANTE]
ADD REP_VARIAS_CARTEIRAS INT NOT NULL DEFAULT 1
GO
	

ALTER TABLE [dbo].[CARTEIRA]
	ADD EMP_ID INT NULL	
GO

ALTER TABLE [dbo].[CARTEIRA]
	 WITH CHECK ADD  CONSTRAINT [FK_CARTEIRA_EMPRESA] FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPRESA_REF] ([EMP_ID])
GO


ALTER TABLE [dbo].[PRE_PEDIDO]
	ADD CAR_ID char(7) NULL	
GO

ALTER TABLE [dbo].[PRE_PEDIDO]
	 WITH CHECK ADD  CONSTRAINT [FK_CARTEIRA_PRE_PEDIDO] FOREIGN KEY([CAR_ID])
REFERENCES [dbo].[CARTEIRA] ([CAR_ID])
GO


USE [COADCORP]
GO

/****** Object:  Table [dbo].[CLASSIFICACAO_CLIENTE]    Script Date: 07/23/2015 12:37:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [COADCORP]
GO

/****** Object:  Table [dbo].[TIPO_CLASSIFICACAO_CLIENTE]    Script Date: 07/23/2015 12:46:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIPO_CLASSIFICACAO_CLIENTE](
	[TP_CLA_ID] [int] IDENTITY(1,1) NOT NULL,
	[TP_CLA_DESCRICAO] [nvarchar](30) NULL,
 CONSTRAINT [PK_CLASSIFICACAO_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[TP_CLA_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



ALTER TABLE [dbo].[CLIENTES]
	ADD TP_CLA_ID int NULL	
GO

ALTER TABLE [dbo].[CLIENTES]
	 WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_TIPO_CLASSIFICACAO_CLIENTE] FOREIGN KEY([TP_CLA_ID])
REFERENCES [dbo].[TIPO_CLASSIFICACAO_CLIENTE] ([TP_CLA_ID])
GO

USE [COADCORP]
GO

/****** Object:  Table [dbo].[CLASSIFICACAO]    Script Date: 07/24/2015 10:30:55 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLASSIFICACAO]') AND type in (N'U'))

ALTER TABLE [dbo].[CLIENTES]
DROP CONSTRAINT "FK_CLIENTE_TIPO_CLASSIFICACAO_CLIENTE"
GO


ALTER TABLE [dbo].[CLIENTES]
DROP COLUMN TP_CLA_ID 
GO

ALTER TABLE [dbo].[CLIENTES]
ADD CLA_CLI_ID INT NULL
GO

DROP TABLE TIPO_CLASSIFICACAO_CLIENTE
GO 

USE [COADCORP]
GO

/****** Object:  Table [dbo].[TIPO_CLASSIFICACAO_CLIENTE]    Script Date: 07/23/2015 12:46:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLASSIFICACAO_CLIENTE](
	[CLA_CLI_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLA_CLI_DESCRICAO] [nvarchar](30) NULL,
 CONSTRAINT [PK_CLASSIFICACAO_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[CLA_CLI_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CLIENTES]
	 WITH CHECK ADD CONSTRAINT [FK_CLIENTE_CLASSIFICACAO_CLIENTE] FOREIGN KEY([CLA_CLI_ID])
REFERENCES [dbo].[CLASSIFICACAO_CLIENTE] ([CLA_CLI_ID])
GO

USE [COADCORP]
GO

/****** Object:  Table [dbo].[CARTEIRA_CLIENTE]    Script Date: 07/24/2015 11:53:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CARTEIRA_CLIENTE](
	[CAR_ID] [char](7) NULL,
	[CLI_ID] [int] NULL,
	[DATA_ASSOCIACAO] [datetime] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[CARTEIRA_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CARTEIRA_CLIENTE_CARTEIRA] FOREIGN KEY([CAR_ID])
REFERENCES [dbo].[CARTEIRA] ([CAR_ID])
GO

ALTER TABLE [dbo].[CARTEIRA_CLIENTE] CHECK CONSTRAINT [FK_CARTEIRA_CLIENTE_CARTEIRA]
GO

ALTER TABLE [dbo].[CARTEIRA_CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CARTEIRA_CLIENTE_CLIENTES] FOREIGN KEY([CLI_ID])
REFERENCES [dbo].[CLIENTES] ([CLI_ID])
GO

ALTER TABLE [dbo].[CARTEIRA_CLIENTE] CHECK CONSTRAINT [FK_CARTEIRA_CLIENTE_CLIENTES]
GO

ALTER TABLE [dbo].[CARTEIRA_CLIENTE] ADD  CONSTRAINT [DF_CARTEIRA_CLIENTE_DATA_ASSOCIACAO]  DEFAULT (getdate()) FOR [DATA_ASSOCIACAO]
GO


USE [COADCORP]
GO

ALTER TABLE ASSINATURA 
ADD [TP_ASS_ID] [INT] NULL

GO
/****** Object:  Table [dbo].[TIPO_PERIODO_ASSINATURA]    Script Date: 07/27/2015 13:58:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIPO_PERIODO_ASSINATURA](
	[TP_ASS_ID] [int] IDENTITY(1,1) NOT NULL,
	[TP_ASS_DESCRICAO] [nvarchar](50) NOT NULL,
	[TP_ASS_QTD_PERIODO] [int] NULL,
 CONSTRAINT [PK_TIPO_PERIODO_ASSINATURA_1] PRIMARY KEY CLUSTERED 
(
	[TP_ASS_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [dbo].[ASSINATURA]  WITH CHECK ADD  CONSTRAINT [FK_ASSINATURA_TIPO_PERIODO_ASSINATURA] FOREIGN KEY([TP_ASS_ID])
REFERENCES [dbo].[TIPO_PERIODO_ASSINATURA] ([TP_ASS_ID])
GO
