  

ALTER TABLE COADCORP_HOMOL.dbo.ITEM_PEDIDO
ADD IPE_DATA_PRODUCAO DATETIME NULL

GO

USE [COADSYS]
GO

/****** Object:  Table [dbo].[TIPO_FILTRO]    Script Date: 21/08/2017 11:50:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TIPO_FILTRO](
	[TFI_ID] [int] NOT NULL,
	[TFI_DESCRICAO] [varchar](200) NULL,
 CONSTRAINT [PK_TIPO_FILTRO] PRIMARY KEY CLUSTERED 
(
	[TFI_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [COADSYS]
GO

/****** Object:  Table [dbo].[CONFIG_PESQUISAS]    Script Date: 21/08/2017 11:51:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CONFIG_PESQUISAS](
	[CPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[CPE_DESCRICAO] [varchar](150) NULL,
	[CPE_REG_POR_PAGINA] [int] NULL,
 CONSTRAINT [PK_CONFIG_PESQUISAS] PRIMARY KEY CLUSTERED 
(
	[CPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [COADSYS]
GO

/****** Object:  Table [dbo].[PESQUISA_FILTRO]    Script Date: 21/08/2017 11:58:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PESQUISA_FILTRO](
	[PFI_ID] [int] NOT NULL,
	[CPE_ID] [int] NULL,
	[PFI_LABEL] [varchar](80) NULL,
	[TFI_ID] [int] NULL,
	[PFI_TM_COLUNA] [int] NULL,
	[PFI_TM_MAX_CAMPO] [int] NULL,
	[PFI_ORDEM] [int] NULL,
 CONSTRAINT [PK_PESQUISA_FILTRO] PRIMARY KEY CLUSTERED 
(
	[PFI_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PESQUISA_FILTRO]  WITH CHECK ADD  CONSTRAINT [FK_PESQUISA_FILTRO_CONFIG_PESQUISAS] FOREIGN KEY([CPE_ID])
REFERENCES [dbo].[CONFIG_PESQUISAS] ([CPE_ID])
GO

ALTER TABLE [dbo].[PESQUISA_FILTRO] CHECK CONSTRAINT [FK_PESQUISA_FILTRO_CONFIG_PESQUISAS]
GO

ALTER TABLE [dbo].[PESQUISA_FILTRO]  WITH CHECK ADD  CONSTRAINT [FK_PESQUISA_FILTRO_TIPO_FILTRO] FOREIGN KEY([TFI_ID])
REFERENCES [dbo].[TIPO_FILTRO] ([TFI_ID])
GO

ALTER TABLE [dbo].[PESQUISA_FILTRO] CHECK CONSTRAINT [FK_PESQUISA_FILTRO_TIPO_FILTRO]
GO


ALTER TABLE 
	prospectados.dbo.cart_coad
ALTER COLUMN MUNIC VARCHAR(60) NULL

GO

ALTER TABLE COADCORP.dbo.PROPOSTA_ITEM
ADD PPI_ASN_NUM_ASS_CANC VARCHAR(8)

GO

ALTER TABLE COADCORP.dbo.ITEM_PEDIDO
ADD IPE_ASN_NUM_ASS_CANC VARCHAR(8)

GO

ALTER TABLE [dbo].[PROPOSTA_ITEM]  WITH CHECK ADD  CONSTRAINT [FK_PROPOSTA_ITEM_ASSINATURA_CANC] FOREIGN KEY([PPI_ASN_NUM_ASS_CANC])
REFERENCES [dbo].[ASSINATURA] ([ASN_NUM_ASSINATURA])
GO

ALTER TABLE [dbo].[PROPOSTA_ITEM] CHECK CONSTRAINT [FK_PROPOSTA_ITEM_ASSINATURA_CANC]
GO

ALTER TABLE [dbo].[ITEM_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PEDIDO_ASSINATURA_CANC] FOREIGN KEY([IPE_ASN_NUM_ASS_CANC])
REFERENCES [dbo].[ASSINATURA] ([ASN_NUM_ASSINATURA])
GO

ALTER TABLE [dbo].[ITEM_PEDIDO] CHECK CONSTRAINT [FK_ITEM_PEDIDO_ASSINATURA_CANC]
GO

ALTER TABLE 
	[COADCORP].[dbo].[ASSINATURA_TRANSFERENCIA]
ADD ASN_TRANSF_CONTRATO_ORIGEM VARCHAR(6)

GO


ALTER TABLE 
	[COADCORP].[dbo].[ASSINATURA_TRANSFERENCIA]
ADD ASN_TRANSF_CONTRATO_GERADO VARCHAR(6)

GO

ALTER TABLE [dbo].[ASSINATURA_TRANSFERENCIA]  WITH CHECK ADD  CONSTRAINT [FK_ASSINATURA_TRANSFERENCIA_CONTRATO_ORIGEM] FOREIGN KEY([ASN_TRANSF_CONTRATO_ORIGEM])
REFERENCES [dbo].[CONTRATOS] ([CTR_NUM_CONTRATO])
GO

ALTER TABLE [dbo].[ASSINATURA_TRANSFERENCIA] CHECK CONSTRAINT [FK_ASSINATURA_TRANSFERENCIA_CONTRATO_ORIGEM]
GO


ALTER TABLE [dbo].[ASSINATURA_TRANSFERENCIA]  WITH CHECK ADD  CONSTRAINT [FK_ASSINATURA_TRANSFERENCIA_CONTRATO_GERADO] FOREIGN KEY([ASN_TRANSF_CONTRATO_GERADO])
REFERENCES [dbo].[CONTRATOS] ([CTR_NUM_CONTRATO])
GO

ALTER TABLE [dbo].[ASSINATURA_TRANSFERENCIA] CHECK CONSTRAINT [FK_ASSINATURA_TRANSFERENCIA_CONTRATO_GERADO]
GO

ALTER TABLE COADCORP.dbo.HISTORICO_ATENDIMENTO 
ADD ASN_NUM_ASSINATURA_ANT VARCHAR(8) NULL

GO

ALTER TABLE COADCORP.dbo.HISTORICO_ATENDIMENTO
ADD ASN_NUM_ASSINATURA_ATU VARCHAR(8) NULL

GO

ALTER TABLE [dbo].[HISTORICO_ATENDIMENTO]  WITH CHECK ADD  CONSTRAINT [FK_HISTORICO_ATENDIMENTO_ASSINATURA_TRANSFERENCIA] FOREIGN KEY([ASN_NUM_ASSINATURA_ANT], [ASN_NUM_ASSINATURA_ATU])
REFERENCES [dbo].[ASSINATURA_TRANSFERENCIA] ([ASN_NUM_ASSINATURA_ANT], [ASN_NUM_ASSINATURA_ATU])
GO

ALTER TABLE [dbo].[HISTORICO_ATENDIMENTO] CHECK CONSTRAINT [FK_HISTORICO_ATENDIMENTO_ASSINATURA_TRANSFERENCIA]
GO


ALTER TABLE COADCORP.dbo.HISTORICO_PEDIDO
ADD ASN_NUM_ASSINATURA_ANT VARCHAR(8) NULL

GO

ALTER TABLE COADCORP.dbo.HISTORICO_PEDIDO
ADD ASN_NUM_ASSINATURA_ATU VARCHAR(8) NULL

GO

ALTER TABLE [dbo].[HISTORICO_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_HISTORICO_PEDIDO_ASSINATURA_TRANSFERENCIA] FOREIGN KEY([ASN_NUM_ASSINATURA_ANT], [ASN_NUM_ASSINATURA_ATU])
REFERENCES [dbo].[ASSINATURA_TRANSFERENCIA] ([ASN_NUM_ASSINATURA_ANT], [ASN_NUM_ASSINATURA_ATU])
GO

ALTER TABLE [dbo].[HISTORICO_PEDIDO] CHECK CONSTRAINT [FK_HISTORICO_PEDIDO_ASSINATURA_TRANSFERENCIA]
GO

ALTER TABLE COADCORP.dbo.ASSINATURA
ADD ASN_NUM_ASS_TRANSFERIDA VARCHAR(8) NULL

GO

ALTER TABLE COADCORP.dbo.ASSINATURA
ADD ASN_TRANSFERIDA BIT NULL

GO

ALTER TABLE [dbo].[ASSINATURA]  WITH CHECK ADD  CONSTRAINT [FK_ASSINATURA_ASSINATURA_TRANSFERIDA] FOREIGN KEY([ASN_NUM_ASS_TRANSFERIDA])
REFERENCES [dbo].[ASSINATURA] ([ASN_NUM_ASSINATURA])
GO

ALTER TABLE [dbo].[ASSINATURA] CHECK CONSTRAINT [FK_ASSINATURA_ASSINATURA_TRANSFERIDA]
GO

ALTER TABLE COADCORP.dbo.ORIGEM_ACESSO
ADD LIN_PRO_ID INT NULL

GO

ALTER TABLE [dbo].[ORIGEM_ACESSO]  WITH CHECK ADD  CONSTRAINT [FK_ORIGEM_ACESSO_LINHA_PRODUTO] FOREIGN KEY([LIN_PRO_ID])
REFERENCES [dbo].[LINHA_PRODUTO] ([LIN_PRO_ID])
GO

ALTER TABLE [dbo].[ORIGEM_ACESSO] CHECK CONSTRAINT [FK_ORIGEM_ACESSO_LINHA_PRODUTO]
GO

ALTER TABLE COADCORP.dbo.RELATORIO_TABELA_COLUNAS
ADD REL_ID_GRUPO INT NULL

GO

ALTER TABLE [dbo].[RELATORIO_TABELA_COLUNAS]  WITH CHECK ADD  CONSTRAINT [FK_RELATORIO_TABELA_COLUNAS_RELATORIO_PERSONALIZADO_GRUPO] FOREIGN KEY([REL_ID_GRUPO])
REFERENCES [dbo].[RELATORIO_PERSONALIZADO] ([REL_ID])
GO

ALTER TABLE [dbo].[RELATORIO_TABELA_COLUNAS] CHECK CONSTRAINT [FK_RELATORIO_TABELA_COLUNAS_RELATORIO_PERSONALIZADO_GRUPO]
GO

GO
ALTER TABLE [dbo].[URA_COAD]  WITH CHECK ADD  CONSTRAINT [FK_URA_COAD_URA] FOREIGN KEY([URAID])
REFERENCES [dbo].[URA] ([URA_ID])
GO

ALTER TABLE [dbo].[URA_COAD] CHECK CONSTRAINT [FK_URA_COAD_URA]
GO
ALTER TABLE [dbo].CONSULTOR
ADD CONSTRAINT [PK_CONSULTOR] PRIMARY KEY CLUSTERED 
(
	[CON_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
 
GO


ALTER TABLE [dbo].[CONSULTOR]  WITH CHECK ADD  CONSTRAINT [FK_CONSULTOR_CONSULTOR] FOREIGN KEY([CON_ID_SUPREVISOR])
REFERENCES [dbo].[CONSULTOR] ([CON_ID])
GO

ALTER TABLE [dbo].[CONSULTOR] CHECK CONSTRAINT [FK_CONSULTOR_CONSULTOR]
GO


INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (0, N'0', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (9, N'9', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (53, N'53', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (112, N'112', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (114, N'114', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (164, N'164', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (165, N'165', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (196, N'196', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (204, N'204', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (231, N'231', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (256, N'256', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (283, N'283', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (344, N'344', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (350, N'350', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (362, N'362', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (369, N'369', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (374, N'374', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (383, N'383', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (409, N'409', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (418, N'418', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (424, N'424', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (427, N'427', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (428, N'428', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (431, N'431', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (435, N'435', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (443, N'443', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (453, N'453', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (454, N'454', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (455, N'455', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (456, N'456', NULL, NULL, NULL, NULL)

go
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (145, N'145', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (468, N'468', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (477, N'477', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (478, N'478', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (484, N'484', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (496, N'496', NULL, NULL, NULL, NULL)

GO

INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (470, N'470', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (458, N'458', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (473, N'473', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (485, N'485', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (479, N'479', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (480, N'480', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (377, N'377', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (471, N'471', NULL, NULL, NULL, NULL)
INSERT [dbo].[CONSULTOR] ([CON_ID], [CON_NOME], [CON_TIPO], [CON_SUPERVISOR], [USU_LOGIN], [CON_ID_SUPREVISOR]) VALUES (469, N'469', NULL, NULL, NULL, NULL)

GO

ALTER TABLE [dbo].[HIST_ATEND_EMAIL]  WITH CHECK ADD  CONSTRAINT [FK_HIST_ATEND_EMAIL_CONSULTOR] FOREIGN KEY([CON_ID])
REFERENCES [dbo].[CONSULTOR] ([CON_ID])
GO

ALTER TABLE [dbo].[HIST_ATEND_EMAIL] CHECK CONSTRAINT [FK_HIST_ATEND_EMAIL_CONSULTOR]
GO

ALTER TABLE [dbo].[HIST_ATEND_EMAIL]  WITH CHECK ADD  CONSTRAINT [FK_HIST_ATEND_EMAIL_CONSULTOR1] FOREIGN KEY([CON_ID_SUPERVISOR])
REFERENCES [dbo].[CONSULTOR] ([CON_ID])
GO

ALTER TABLE [dbo].[HIST_ATEND_EMAIL] CHECK CONSTRAINT [FK_HIST_ATEND_EMAIL_CONSULTOR1]
GO

ALTER TABLE [dbo].[AGENDA_COBRANCA] CHECK CONSTRAINT [FK_AGENDA_COBRANCA_ASSINATURA]
GO

ALTER TABLE [dbo].[AGENDA_COBRANCA]  WITH CHECK ADD  CONSTRAINT [FK_AGENDA_COBRANCA_PARCELAS] FOREIGN KEY([PAR_NUM_PARCELA])
REFERENCES [dbo].[PARCELAS] ([PAR_NUM_PARCELA])
GO


ALTER TABLE [dbo].[URA_CONFIG]  WITH CHECK ADD  CONSTRAINT [FK_URA_CONFIG_URA] FOREIGN KEY([URA_ID])
REFERENCES [dbo].[URA] ([URA_ID])
GO

ALTER TABLE [dbo].[URA_CONFIG] CHECK CONSTRAINT [FK_URA_CONFIG_URA]
GO


ALTER TABLE [dbo].[PARCELA_LIQUIDACAO]  WITH CHECK ADD  CONSTRAINT [FK_PARCELA_LIQUIDACAO_DOC_LIQUIDACAO] FOREIGN KEY([PLI_TIPO_DOC])
REFERENCES [dbo].[DOC_LIQUIDACAO] ([DLI_SIGLA])
GO

ALTER TABLE [dbo].[PARCELA_LIQUIDACAO] CHECK CONSTRAINT [FK_PARCELA_LIQUIDACAO_DOC_LIQUIDACAO]
GO

ALTER TABLE 
	[dbo].[NFE_XML]
ADD NFX_DATA_EMI_NOTA DATETIME NULL

GO

USE [COADSYS_HOMOL]
GO

/****** Object:  Table [dbo].[TIPO_JOB]    Script Date: 24/10/2017 15:03:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TIPO_JOB](
	[TPJ_ID] [int] NOT NULL,
	[TPJ_DESCRICAO] [varchar](50) NULL,
 CONSTRAINT [PK_TIPO_JOB] PRIMARY KEY CLUSTERED 
(
	[TPJ_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[HISTORICO_EXECUCAO]
ADD HIE_CORREU_ERRO BIT NULL

GO

ALTER TABLE [dbo].[HISTORICO_EXECUCAO]
ADD TPJ_ID INT NULL

GO

ALTER TABLE [dbo].[HISTORICO_EXECUCAO]
ADD HIE_ID_REF INT NULL

GO


ALTER TABLE [dbo].[HISTORICO_EXECUCAO]
ADD HIE_ID_STR_REF VARCHAR(20) NULL

GO

ALTER TABLE [dbo].[HISTORICO_EXECUCAO]
ADD HIE_ID_DESC VARCHAR(70) NULL

GO


ALTER TABLE [dbo].[HISTORICO_EXECUCAO]  WITH CHECK ADD  CONSTRAINT [FK_HISTORICO_EXECUCAO_TIPO_JOB] FOREIGN KEY([TPJ_ID])
REFERENCES [dbo].[TIPO_JOB] ([TPJ_ID])
GO

ALTER TABLE [dbo].[HISTORICO_EXECUCAO] CHECK CONSTRAINT [FK_HISTORICO_EXECUCAO_TIPO_JOB]
GO

INSERT INTO dbo.TIPO_JOB (TPJ_ID, TPJ_DESCRICAO)
VALUES (1, 'Email')

GO

INSERT INTO dbo.TIPO_JOB (TPJ_ID, TPJ_DESCRICAO)
VALUES (2, 'Baixa de Parcela')

GO

INSERT INTO dbo.TIPO_JOB (TPJ_ID, TPJ_DESCRICAO)
VALUES (3, 'Lote de Nota Fiscal')

GO

INSERT INTO dbo.TIPO_JOB (TPJ_ID, TPJ_DESCRICAO)
VALUES (4, 'Download Lote de Nota Fiscal')

GO

INSERT INTO dbo.TIPO_JOB (TPJ_ID, TPJ_DESCRICAO)
VALUES (5, 'Notificação de Proposta Paga')

GO

 UPDATE
	con 
  SET
	con.CTR_GERA_NOTA_FISCAL = 1
  FROM 
	dbo.CONTRATOS con INNER JOIN
	dbo.ITEM_PEDIDO ipe ON con.IPE_ID = ipe.IPE_ID INNER JOIN
	dbo.NFE_XML nfx ON ipe.IPE_ID = nfx.NFX_ID
  WHERE 
	  con.CTR_GERA_NOTA_FISCAL IS NULL OR 
	  con.CTR_GERA_NOTA_FISCAL <> 1
GO


  SET IDENTITY_INSERT [dbo].[TIPO_NOTIFICACAO] ON
	INSERT INTO [dbo].[TIPO_NOTIFICACAO]
		(TP_NTF_ID, TP_NTF_DESCRICAO) VALUES (6, 'Pagamento Proposta/Pedido')
  SET IDENTITY_INSERT [dbo].[TIPO_NOTIFICACAO] OFF

GO

ALTER TABLE 
	dbo.NFE_XML 
ADD NFX_DATA_EXCLUSAO DATETIME NULL

GO

ALTER TABLE 
	dbo.NFE_XML 
ADD NFX_DATA_EXCLUSAO DATETIME NULL

GO

ALTER TABLE 
	dbo.NFE_XML 
ADD NFX_NUM_EXTORNADO BIT NULL

GO
-- Executado em produção até aqui
USE [COADCORP]
GO

/****** Object:  Table [dbo].[BANDEIRA_CARTAO]    Script Date: 09/11/2017 11:39:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BANDEIRA_CARTAO](
	[BAC_ID] [int] IDENTITY(1,1) NOT NULL,
	[BAC_DESCRICAO] [varchar](150) NULL,
 CONSTRAINT [PK_BANDEIRA_CARTAO] PRIMARY KEY CLUSTERED 
(
	[BAC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE 
	dbo.[PROPOSTA_ITEM_COMPROVANTE]
ADD BAN_ID CHAR(3) NULL

GO

ALTER TABLE 
	dbo.[PROPOSTA_ITEM_COMPROVANTE]
ADD PIC_VENC_CARTAO DATETIME NULL

GO

ALTER TABLE 
	dbo.[PROPOSTA_ITEM_COMPROVANTE]
ADD PIC_NUMERO_DOCUMENTO varchar(50) NULL

GO

ALTER TABLE 
	dbo.[PROPOSTA_ITEM_COMPROVANTE]
ADD PIC_CHEQUE_BOM_PARA DATETIME NULL

GO

ALTER TABLE 
	dbo.[PROPOSTA_ITEM_COMPROVANTE]
ADD BAC_ID INT NULL

GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE]  WITH CHECK ADD  CONSTRAINT [FK_PROPOSTA_ITEM_COMPROVANTE_BANDEIRA_CARTAO] FOREIGN KEY([BAC_ID])
REFERENCES [dbo].[BANDEIRA_CARTAO] ([BAC_ID])
GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE] CHECK CONSTRAINT [FK_PROPOSTA_ITEM_COMPROVANTE_BANDEIRA_CARTAO]
GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE]  WITH CHECK ADD  CONSTRAINT [FK_PROPOSTA_ITEM_COMPROVANTE_BANCOS] FOREIGN KEY([BAN_ID])
REFERENCES [dbo].[BANCOS] ([BAN_ID])
GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE] CHECK CONSTRAINT [FK_PROPOSTA_ITEM_COMPROVANTE_BANCOS]

GO

ALTER TABLE 
	dbo.PROPOSTA_ITEM_COMPROVANTE
ADD PIC_NUMERO_CARTAO varchar(50) NULL

GO
ALTER TABLE dbo.PROPOSTA_ITEM_COMPROVANTE
ADD TPG_ID INT NULL

GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE]  WITH CHECK ADD  CONSTRAINT [FK_PROPOSTA_ITEM_COMPROVANTE_TIPO_PAGAMENTO] FOREIGN KEY([TPG_ID])
REFERENCES [dbo].[TIPO_PAGAMENTO] ([TPG_ID])
GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE] CHECK CONSTRAINT [FK_PROPOSTA_ITEM_COMPROVANTE_TIPO_PAGAMENTO]

GO


SET IDENTITY_INSERT [dbo].[BANDEIRA_CARTAO] ON
INSERT INTO [dbo].[BANDEIRA_CARTAO] (BAC_ID, BAC_DESCRICAO)
VALUES (1, 'Visa')

INSERT INTO [dbo].[BANDEIRA_CARTAO] (BAC_ID, BAC_DESCRICAO)
VALUES (2, 'MasterCard')

INSERT INTO [dbo].[BANDEIRA_CARTAO] (BAC_ID, BAC_DESCRICAO)
VALUES (3, 'ELO')

INSERT INTO [dbo].[BANDEIRA_CARTAO] (BAC_ID, BAC_DESCRICAO)
VALUES (4, 'AMEX')


SET IDENTITY_INSERT [dbo].[BANDEIRA_CARTAO] OFF

GO

ALTER TABLE 
	dbo.[PROPOSTA_ITEM_COMPROVANTE]
ADD UF_SIGLA char(2)

GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE]  WITH CHECK ADD  CONSTRAINT [FK_UF_TIPO_PAGAMENTO] FOREIGN KEY([UF_SIGLA])
REFERENCES [dbo].[UF] ([UF_SIGLA])
GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE] CHECK CONSTRAINT [FK_UF_TIPO_PAGAMENTO]

GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE]
  ADD IPE_ID INT NULL
GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PROPOSTA_COMPROVANTE_x_ITEM_PEDIDO] FOREIGN KEY([IPE_ID])
REFERENCES [dbo].[ITEM_PEDIDO] ([IPE_ID])
GO

ALTER TABLE [dbo].[PROPOSTA_ITEM_COMPROVANTE] CHECK CONSTRAINT [FK_ITEM_PROPOSTA_COMPROVANTE_x_ITEM_PEDIDO]

GO

ALTER TABLE dbo.ITEM_PEDIDO 
	ADD TPG_ID INT NULL
GO

ALTER TABLE [dbo].[ITEM_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PEDIDO_TIPO_PAGAMENTO] FOREIGN KEY([TPG_ID])
REFERENCES [dbo].[TIPO_PAGAMENTO] ([TPG_ID])
GO

ALTER TABLE [dbo].[ITEM_PEDIDO] CHECK CONSTRAINT [FK_ITEM_PEDIDO_TIPO_PAGAMENTO]

GO

-- Atualiza o tipo de pagamento de acordo com a proposta
UPDATE ITM
SET TPG_ID = PPI.TPG_ID 
FROM 
	dbo.ITEM_PEDIDO ITM INNER JOIN 
	dbo.PROPOSTA_ITEM PPI ON ITM.PPI_ID = PPI.PPI_ID
WHERE ITM.TPG_ID IS NULL

GO

--Atualiza o tipo de pagamento de acordo com o pedido pagamento à vista
UPDATE IT_PED
SET TPG_ID = T1.TIPO_PAGAMENTO
FROM 
	dbo.ITEM_PEDIDO IT_PED INNER JOIN
(SELECT ITM.IPE_ID, 
(	
	SELECT TOP 1 
		PGT.TPG_ID
	FROM 
		dbo.ITEM_PEDIDO_PEDIDO_PAGAMENTO IT_PA INNER JOIN 
		dbo.PEDIDO_PAGAMENTO PGT ON IT_PA.PGT_ID = PGT.PGT_ID
	WHERE 
		IT_PA.IPE_ID = ITM.IPE_ID) AS TIPO_PAGAMENTO
FROM 
	dbo.ITEM_PEDIDO ITM
WHERE 
	ITM.TPG_ID IS NULL AND ( 
	SELECT COUNT(*) FROM dbo.ITEM_PEDIDO_PEDIDO_PAGAMENTO IT_PA WHERE IT_PA.IPE_ID = ITM.IPE_ID) = 1
	) AS T1 ON T1.IPE_ID = IT_PED.IPE_ID

-- Realiza a atualização dos tipos de pagamento compostos
DECLARE @TIPOS TABLE(IPE_ID INT, ENTRADA INT, RESTANTE INT)

INSERT INTO @TIPOS (IPE_ID, ENTRADA, RESTANTE)
SELECT
	 
	 ITM.IPE_ID,
	 (
		SELECT PED_PAG1.TPG_ID
		FROM 
		dbo.PEDIDO_PAGAMENTO PED_PAG1 
		WHERE PED_PAG1.PGT_ID = Min(PAG.PGT_ID) 
	) AS ENTRADA,
	 (
	 SELECT PED_PAG2.TPG_ID
		FROM 
		dbo.PEDIDO_PAGAMENTO PED_PAG2 
		WHERE PED_PAG2.PGT_ID =  Max(PAG.PGT_ID) ) AS RESTANTE
FROM 
	dbo.ITEM_PEDIDO ITM INNER JOIN
	dbo.ITEM_PEDIDO_PEDIDO_PAGAMENTO IT_PG ON ITM.IPE_ID = IT_PG.IPE_ID INNER JOIN
	dbo.PEDIDO_PAGAMENTO PAG ON PAG.PGT_ID = IT_PG.PGT_ID
WHERE 
	ITM.TPG_ID IS NULL AND ( 
	SELECT COUNT(*) FROM dbo.ITEM_PEDIDO_PEDIDO_PAGAMENTO IT_PA WHERE IT_PA.IPE_ID = ITM.IPE_ID) > 1
	GROUP BY ITM.IPE_ID



UPDATE ITM
SET TPG_ID = T1.CODIGO_CORRETO
FROM 
	dbo.ITEM_PEDIDO 
ITM INNER JOIN
(
SELECT 
TIP_CER.TPG_ID CODIGO_CORRETO,
TP_VAR_ENTR.IPE_ID AS IPE_ID_1,
TP_VAR_RES.IPE_ID AS IPE_ID_2
FROM 
	dbo.TIPO_PAGAMENTO_COMPOSICAO TCM_ENT INNER JOIN 
	@TIPOS TP_VAR_ENTR ON (TCM_ENT.TPC_ORDEM = 0 AND TCM_ENT.TPG_ID_FILHO = TP_VAR_ENTR.ENTRADA),
	dbo.TIPO_PAGAMENTO_COMPOSICAO TCM_RES INNER JOIN 
	@TIPOS TP_VAR_RES  ON (TCM_RES.TPC_ORDEM = 1 AND TCM_RES.TPG_ID_FILHO = TP_VAR_RES.RESTANTE ),
	dbo.TIPO_PAGAMENTO TIP_CER 
WHERE 
	TIP_CER.TPG_ID = TCM_ENT.TPG_ID_PAI AND 
	TIP_CER.TPG_ID = TCM_RES.TPG_ID_PAI AND 
	TP_VAR_ENTR.IPE_ID = TP_VAR_RES.IPE_ID
) AS T1 ON  ITM.IPE_ID = T1.IPE_ID_2	
WHERE ITM.TPG_ID IS NULL


ALTER TABLE dbo.PROPOSTA_ITEM
ADD PPI_GERA_NOTA BIT NULL

GO

ALTER TABLE dbo.ITEM_PEDIDO
ADD IPE_GERA_NOTA BIT NULL

GO
