//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA_EMAIL_PERFIL_COLEC
    {
        public string PC_ID { get; set; }
        public int COLEC_ID { get; set; }
    
        public virtual CONSULTA_EMAIL_COLECIONADOR CONSULTA_EMAIL_COLECIONADOR { get; set; }
    }
}
