//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNDAMENTACAO
    {
        public int FUN_ID { get; set; }
        public int MAI_ID { get; set; }
        public string USU_LOGIN { get; set; }
        public System.DateTime DATA_INSERT { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public Nullable<int> TIP_ATO_ID { get; set; }
        public Nullable<int> MAI_NUMERO_ATO { get; set; }
        public string MAI_DATA_ATO { get; set; }
        public Nullable<int> ORG_ID { get; set; }
        public string MAI_NUMERO_ARTIGO { get; set; }
        public Nullable<int> FUN_NUM_PARAGRAFO { get; set; }
        public string FUN_INCISO { get; set; }
    
        public virtual MANUAL_DP_ITEM MANUAL_DP_ITEM { get; set; }
    }
}
