//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMATIVO
    {
        public INFORMATIVO()
        {
            this.PUBLICACAO_UF = new HashSet<PUBLICACAO_UF>();
        }
    
        public string INF_ANO { get; set; }
        public int INF_NUMERO { get; set; }
        public Nullable<System.DateTime> INF_DATA_INICIO { get; set; }
        public Nullable<System.DateTime> INF_DATA_FINAL { get; set; }
        public Nullable<System.DateTime> INF_DATA_PREV_POSTAGEM { get; set; }
        public Nullable<System.DateTime> INF_DATA_POSTAGEM { get; set; }
        public Nullable<int> INF_ATIVO { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual ICollection<PUBLICACAO_UF> PUBLICACAO_UF { get; set; }
    }
}
