//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public NEWS()
        {
            this.AREAS_CONSULTORIA_NEWS = new HashSet<AREAS_CONSULTORIA_NEWS>();
        }
    
        public int NEWS_ID { get; set; }
        public Nullable<int> SEC_ID { get; set; }
        public Nullable<int> LBL_ID { get; set; }
        public string NEWS_DESCRICAO { get; set; }
        public byte[] NEWS_TEXTO { get; set; }
        public Nullable<System.DateTime> NEWS_DATA_PUB { get; set; }
        public Nullable<System.DateTime> NEWS_DATA_ENVIO { get; set; }
        public Nullable<bool> NEWS_ATIVO { get; set; }
    
        public virtual ICollection<AREAS_CONSULTORIA_NEWS> AREAS_CONSULTORIA_NEWS { get; set; }
    }
}
