//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIA_GRUPO
    {
        public NOTICIA_GRUPO()
        {
            this.NOTICIA = new HashSet<NOTICIA>();
            this.NOTICIA_GRUPO_LINHA_PROD = new HashSet<NOTICIA_GRUPO_LINHA_PROD>();
        }
    
        public int NGR_ID { get; set; }
        public string NGR_DESCRICAO { get; set; }
    
        public virtual ICollection<NOTICIA> NOTICIA { get; set; }
        public virtual ICollection<NOTICIA_GRUPO_LINHA_PROD> NOTICIA_GRUPO_LINHA_PROD { get; set; }
    }
}
