//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIA
    {
        public NOTICIA()
        {
            this.LOG_ACESSO_PORTAL = new HashSet<LOG_ACESSO_PORTAL>();
        }
    
        public int NOT_ID { get; set; }
        public string NOT_MANCHETE { get; set; }
        public string NOT_TEXTO { get; set; }
        public Nullable<bool> NOT_DESTAQUE_HOME { get; set; }
        public Nullable<bool> NOT_DESTAQUE_PERFIL { get; set; }
        public Nullable<int> NGR_ID { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public Nullable<int> TIT_ID { get; set; }
        public Nullable<int> PUB_ID { get; set; }
        public Nullable<System.DateTime> DATA_PUBLICACAO { get; set; }
        public string USU_LOGIN_PUB { get; set; }
        public Nullable<bool> NEWSLETTER { get; set; }
    
        public virtual ICollection<LOG_ACESSO_PORTAL> LOG_ACESSO_PORTAL { get; set; }
        public virtual NOTICIA_GRUPO NOTICIA_GRUPO { get; set; }
        public virtual PUBLICACAO PUBLICACAO { get; set; }
        public virtual TITULACAO TITULACAO { get; set; }
    }
}
