//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACAO_CONFIG
    {
        public int PCF_ID { get; set; }
        public Nullable<int> PUB_ID { get; set; }
        public Nullable<int> ARE_CONS_ID { get; set; }
        public Nullable<int> PCF_TIPO_ALTERACAO { get; set; }
        public Nullable<int> PCF_INDICE_ALFA { get; set; }
        public Nullable<int> PCF_INDICE_NUM { get; set; }
        public Nullable<int> PCF_INDICE_REVOGADO { get; set; }
        public Nullable<int> PCF_PUB_WEB { get; set; }
        public Nullable<int> PCF_PUB_IMPRESSO { get; set; }
        public Nullable<int> PCF_PUB_NEWS { get; set; }
        public Nullable<int> PCF_PUB_MOBILE { get; set; }
        public Nullable<int> PCF_PUB_CONSULTORIA { get; set; }
        public Nullable<int> PCF_PUB_WEBSERVICE { get; set; }
        public Nullable<System.DateTime> PCF_DATA_PUB_WEB { get; set; }
        public Nullable<System.DateTime> PCF_DATA_PUB_IMPRESSO { get; set; }
        public Nullable<System.DateTime> PCF_DATA_PUB_NEWS { get; set; }
        public Nullable<System.DateTime> PCF_DATA_PUB_MOBILE { get; set; }
        public Nullable<System.DateTime> PCF_DATA_PUB_CONSULTORIA { get; set; }
        public Nullable<System.DateTime> PCF_DATA_PUB_WEBSERVICE { get; set; }
        public Nullable<System.DateTime> PCF_DATA_PUB_MANCHETE { get; set; }
        public Nullable<System.DateTime> PCF_DATA_PUB_EMENTA { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual PUBLICACAO_AREAS_CONSULTORIA PUBLICACAO_AREAS_CONSULTORIA { get; set; }
    }
}
