//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACAO_UF
    {
        public int PUB_ID { get; set; }
        public int ARE_CONS_ID { get; set; }
        public string UF_ID { get; set; }
        public string INF_ANO { get; set; }
        public Nullable<int> INF_NUMERO { get; set; }
        public Nullable<bool> PUB_ATIVO { get; set; }
    
        public virtual INFORMATIVO INFORMATIVO { get; set; }
        public virtual PUBLICACAO_AREAS_CONSULTORIA PUBLICACAO_AREAS_CONSULTORIA { get; set; }
        public virtual UF_REF UF_REF { get; set; }
    }
}
