//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACAO_vw
    {
        public int PUB_ID { get; set; }
        public Nullable<int> TIP_MAT_ID { get; set; }
        public Nullable<int> TIP_ATO_ID { get; set; }
        public string PUB_NUMERO_ATO { get; set; }
        public Nullable<int> TVI_ID { get; set; }
        public Nullable<int> ORG_ID { get; set; }
        public string PUB_CONTEUDO_RESENHA { get; set; }
        public string PUB_CONTEUDO { get; set; }
        public Nullable<int> SEC_ID { get; set; }
        public Nullable<int> LBL_ID { get; set; }
        public string PUB_OBS { get; set; }
        public Nullable<System.DateTime> PUB_DATA_ATO { get; set; }
        public Nullable<System.DateTime> PUB_DATA_PUB_ATO { get; set; }
        public string PUB_DESCRICAO_NEWS { get; set; }
        public string PUB_COMPL_VEICULO { get; set; }
        public Nullable<int> PUB_ATIVO { get; set; }
        public Nullable<int> FLU_ID { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string USU_LOGIN { get; set; }
    }
}
