//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_DINAMICA_ORIGEM
    {
        public int OAC_ID { get; set; }
        public string TDC_ID { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string USU_LOGIN { get; set; }
    
        public virtual ORIGEM_ACESSO_REF ORIGEM_ACESSO_REF { get; set; }
        public virtual TAB_DINAMICA_CONFIG TAB_DINAMICA_CONFIG { get; set; }
    }
}
