//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_DINAMICA_CONFIG_ITEM
    {
        public string TDC_ID { get; set; }
        public int TCI_ID { get; set; }
        public string TCI_TIPO_CAMPO { get; set; }
        public Nullable<int> TCI_TAMANHO_CAMPO { get; set; }
        public string TCI_ALINHAMENTO_CAMPO { get; set; }
        public int TCI_ORDEM_APRESENTACAO { get; set; }
        public string TCI_VALOR_PADRAO { get; set; }
        public string TCI_VALOR_ESPERADO { get; set; }
        public string TCI_NOME_CAMPODB { get; set; }
        public string TCI_NOME_CAMPO { get; set; }
        public string TCI_FORMULA { get; set; }
        public string USU_LOGIN { get; set; }
        public string TCI_TEXTO_HELP { get; set; }
        public string TDC_ID_TAB_REF { get; set; }
        public Nullable<bool> TCI_TEXTO_HELP_LINK { get; set; }
        public string TCI_PATH_HELP_LINK { get; set; }
        public string TCI_TARGET { get; set; }
        public Nullable<bool> TCI_CAMPO_PESQUISA { get; set; }
        public Nullable<bool> TCI_CAMPO_VISIVEL { get; set; }
        public Nullable<bool> TCI_CAMPO_CHAVE { get; set; }
        public Nullable<bool> TCI_CAMPO_LISTA { get; set; }
        public string TCI_NOME_CHAVEDB { get; set; }
        public string TCI_NOME_LISTADB { get; set; }
        public Nullable<int> TCI_DECIMAIS { get; set; }
        public string TCI_NOME_CAMPO_AUX { get; set; }
    
        public virtual TAB_DINAMICA_CONFIG TAB_DINAMICA_CONFIG { get; set; }
    }
}
