//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_DINAMICA_GRUPO
    {
        public TAB_DINAMICA_GRUPO()
        {
            this.TAB_DINAMICA_CONFIG = new HashSet<TAB_DINAMICA_CONFIG>();
        }
    
        public int TGR_ID { get; set; }
        public string TGR_DESCRICAO { get; set; }
        public Nullable<int> TGR_TIPO { get; set; }
    
        public virtual ICollection<TAB_DINAMICA_CONFIG> TAB_DINAMICA_CONFIG { get; set; }
    }
}
