//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_DINAMICA_PUBLICACAO
    {
        public int TPU_ID { get; set; }
        public string TDC_ID { get; set; }
        public string USU_LOGIN { get; set; }
        public string USU_LOGIN_APROV { get; set; }
        public Nullable<System.DateTime> TPU_DATA_LANC { get; set; }
        public Nullable<System.DateTime> TPU_DATA_APROV { get; set; }
        public string TPU_OBS { get; set; }
        public string TPU_STATUS { get; set; }
    
        public virtual TAB_DINAMICA_CONFIG TAB_DINAMICA_CONFIG { get; set; }
    }
}
