//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_DINAMICA
    {
        public TAB_DINAMICA()
        {
            this.TAB_DINAMICA_ITEM = new HashSet<TAB_DINAMICA_ITEM>();
        }
    
        public string TDC_ID { get; set; }
        public string TAB_DESCRICAO { get; set; }
        public string TAB_INTRODUCAO { get; set; }
        public string TAB_OBS_LAYOUT { get; set; }
        public string TAB_LEGENDA_LAYOUT { get; set; }
        public string TAB_INF_PREENCHIMENTO { get; set; }
        public string TAB_INF_GERAIS { get; set; }
        public Nullable<System.DateTime> TAB_DATA_ALTERA { get; set; }
        public Nullable<System.DateTime> TAB_DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
        public string TAB_ERRO_MSG { get; set; }
    
        public virtual ICollection<TAB_DINAMICA_ITEM> TAB_DINAMICA_ITEM { get; set; }
        public virtual TAB_DINAMICA_CONFIG TAB_DINAMICA_CONFIG { get; set; }
    }
}
