//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_DINAMICA_CONFIG
    {
        public TAB_DINAMICA_CONFIG()
        {
            this.TAB_DINAMICA_CONFIG_ITEM = new HashSet<TAB_DINAMICA_CONFIG_ITEM>();
            this.TAB_DINAMICA_CONFIG1 = new HashSet<TAB_DINAMICA_CONFIG>();
            this.TAB_DINAMICA_LINK = new HashSet<TAB_DINAMICA_LINK>();
            this.TAB_DINAMICA_ORIGEM = new HashSet<TAB_DINAMICA_ORIGEM>();
            this.TAB_DINAMICA_PUBLICACAO = new HashSet<TAB_DINAMICA_PUBLICACAO>();
        }
    
        public string TDC_ID { get; set; }
        public bool TDC_INTRODUCAO { get; set; }
        public bool TDC_OBS_LAYOUT { get; set; }
        public bool TDC_LEGENDA_LAYOUT { get; set; }
        public bool TDC_INF_PREENCHIMENTO { get; set; }
        public bool TDC_INF_GERAIS { get; set; }
        public Nullable<System.DateTime> TDC_DATA_ALTERA { get; set; }
        public Nullable<System.DateTime> TDC_DATA_INCLUSAO { get; set; }
        public string USU_LOGIN { get; set; }
        public string TDC_NOME_TABELA { get; set; }
        public Nullable<int> TDC_TIPO { get; set; }
        public string TDC_ID_TAB_REF { get; set; }
        public Nullable<System.DateTime> TDC_DATA_PUBLICACAO { get; set; }
        public Nullable<int> TGR_ID { get; set; }
        public Nullable<int> TTA_ID { get; set; }
        public Nullable<int> TIT_ID { get; set; }
        public string TDC_LAYOUT_TABELA { get; set; }
        public Nullable<bool> TDC_PALAVRA_CHAVE { get; set; }
        public string USU_LOGIN_PUB { get; set; }
        public string TDC_NOME_CHAVEDB { get; set; }
        public string TDC_NOME_LISTADB { get; set; }
        public string TDC_NOME_OBS { get; set; }
        public Nullable<int> TDC_DECIMAIS { get; set; }
        public string TDC_NOME_IDENTIFICADOR { get; set; }
    
        public virtual TAB_DINAMICA TAB_DINAMICA { get; set; }
        public virtual ICollection<TAB_DINAMICA_CONFIG_ITEM> TAB_DINAMICA_CONFIG_ITEM { get; set; }
        public virtual ICollection<TAB_DINAMICA_CONFIG> TAB_DINAMICA_CONFIG1 { get; set; }
        public virtual TAB_DINAMICA_CONFIG TAB_DINAMICA_CONFIG2 { get; set; }
        public virtual TAB_DINAMICA_GRUPO TAB_DINAMICA_GRUPO { get; set; }
        public virtual ICollection<TAB_DINAMICA_LINK> TAB_DINAMICA_LINK { get; set; }
        public virtual TITULACAO TITULACAO { get; set; }
        public virtual ICollection<TAB_DINAMICA_ORIGEM> TAB_DINAMICA_ORIGEM { get; set; }
        public virtual ICollection<TAB_DINAMICA_PUBLICACAO> TAB_DINAMICA_PUBLICACAO { get; set; }
    }
}
