//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABELA_CEST_VW
    {
        public Nullable<decimal> id { get; set; }
        public string codigo_cest { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> id_item_cest_pai { get; set; }
        public string ncm { get; set; }
    }
}
