//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_MATERIA
    {
        public TIPO_MATERIA()
        {
            this.PUBLICACAO = new HashSet<PUBLICACAO>();
        }
    
        public int TIP_MAT_ID { get; set; }
        public string TIP_MAT_DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<int> TIP_MAT_ATIVO { get; set; }
        public string ARE_CABECA_MATERIA { get; set; }
    
        public virtual ICollection<PUBLICACAO> PUBLICACAO { get; set; }
    }
}
