//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.COADGED.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO
    {
        public VEICULO()
        {
            this.PUBLICACAO = new HashSet<PUBLICACAO>();
        }
    
        public int TVI_ID { get; set; }
        public string TVI_DESCRICAO { get; set; }
        public Nullable<int> PRD_ID { get; set; }
        public Nullable<System.DateTime> DATA_ALTERA { get; set; }
        public string USU_LOGIN { get; set; }
        public Nullable<int> TVI_ATIVO { get; set; }
    
        public virtual PERIODICIDADE PERIODICIDADE { get; set; }
        public virtual ICollection<PUBLICACAO> PUBLICACAO { get; set; }
    }
}
