//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.RM.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFPERFFCOMPL
    {
        public short CODCOLIGADA { get; set; }
        public string CHAPA { get; set; }
        public short ANOCOMP { get; set; }
        public short MESCOMP { get; set; }
        public short NROPERIODO { get; set; }
        public Nullable<short> MESCAIXACOMUM { get; set; }
        public Nullable<short> VALORESFORCADOS { get; set; }
        public Nullable<short> MOVIMPORTADO { get; set; }
        public Nullable<short> EDITADO { get; set; }
        public Nullable<short> ALTERADO { get; set; }
        public Nullable<decimal> SALCOMISSAO { get; set; }
        public Nullable<decimal> FERIASMES { get; set; }
        public Nullable<decimal> BASEINSS { get; set; }
        public Nullable<decimal> BASEINSSOUTROEMP { get; set; }
        public Nullable<decimal> INSS { get; set; }
        public Nullable<decimal> INSSFERIAS { get; set; }
        public Nullable<decimal> INSSOUTROEMP { get; set; }
        public Nullable<decimal> BASEINSS13 { get; set; }
        public Nullable<decimal> BASEINSS13OUTRO { get; set; }
        public Nullable<decimal> INSS13 { get; set; }
        public Nullable<decimal> BASESALFAMILIA { get; set; }
        public Nullable<decimal> SALFAMILIA { get; set; }
        public Nullable<decimal> BASEVALETRANSP { get; set; }
        public Nullable<decimal> VALETRANSPENTR { get; set; }
        public Nullable<decimal> VALETRANSPDESC { get; set; }
        public Nullable<decimal> BASEIRRF { get; set; }
        public Nullable<decimal> IRRF { get; set; }
        public Nullable<decimal> INSSCAIXA { get; set; }
        public Nullable<decimal> DEDUTIVELIRRF { get; set; }
        public Nullable<decimal> BASEIRRFPART { get; set; }
        public Nullable<decimal> IRRFPART { get; set; }
        public Nullable<decimal> BASEIRRFFERIAS { get; set; }
        public Nullable<decimal> IRRFFERIAS { get; set; }
        public Nullable<decimal> INSSCOMCPMF { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<decimal> BASEFGTS { get; set; }
        public Nullable<decimal> BASEFGTS13 { get; set; }
        public Nullable<decimal> SALARIOPAGO { get; set; }
        public Nullable<short> STATUSCCUSTO { get; set; }
        public Nullable<decimal> BASEIRRF13 { get; set; }
        public Nullable<decimal> SALARIODECALCULO { get; set; }
        public Nullable<decimal> IRRF13 { get; set; }
        public Nullable<decimal> INSSFERIASCOMCPMF { get; set; }
        public Nullable<decimal> INSSCALCUSUARIO { get; set; }
        public Nullable<decimal> BASEFGTSDIFSAL { get; set; }
        public Nullable<decimal> INSSDIFSAL { get; set; }
        public Nullable<decimal> INSSDIFSAL13 { get; set; }
        public Nullable<decimal> INSSDIFSALFER { get; set; }
        public string EXECID { get; set; }
        public string RECCREATEDBY { get; set; }
        public Nullable<System.DateTime> RECCREATEDON { get; set; }
        public string RECMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> RECMODIFIEDON { get; set; }
        public Nullable<short> NRODEPENDIRRF { get; set; }
        public Nullable<decimal> LIQUIDO { get; set; }
        public Nullable<short> NRODEPENDSALFAMILIA { get; set; }
        public Nullable<short> IDDADOSRESID { get; set; }
    
        public virtual PFUNC PFUNC { get; set; }
    }
}
