//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.RM.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFUNCAO
    {
        public PFUNCAO()
        {
            this.PFUNC = new HashSet<PFUNC>();
            this.PFUNC1 = new HashSet<PFUNC>();
        }
    
        public short CODCOLIGADA { get; set; }
        public string CODIGO { get; set; }
        public string NOME { get; set; }
        public Nullable<decimal> NUMPONTOS { get; set; }
        public string CBO { get; set; }
        public string CARGO { get; set; }
        public Nullable<short> INATIVA { get; set; }
        public Nullable<short> ATIVTRANSP { get; set; }
        public string DESCRICAO { get; set; }
        public string FAIXASALARIAL { get; set; }
        public Nullable<int> LIMITEFUNC { get; set; }
        public Nullable<decimal> VERBAQUADROVAGAS { get; set; }
        public Nullable<decimal> PERCQUADROVAGAS { get; set; }
        public Nullable<System.DateTime> DATAULTIMAREVISAO { get; set; }
        public string NUMREVISAO { get; set; }
        public string CBO2002 { get; set; }
        public string CODTABELA { get; set; }
        public string CODPERFILCAND { get; set; }
        public int ID { get; set; }
        public Nullable<int> BENEFPONTOS { get; set; }
        public string OBJETIVO { get; set; }
        public string DESCRICAOPPP { get; set; }
        public string EXIBEORGANOGRAMA { get; set; }
        public string CODFUNCAOCHEFIA { get; set; }
        public Nullable<decimal> JORNADAREF { get; set; }
        public string RECCREATEDBY { get; set; }
        public Nullable<System.DateTime> RECCREATEDON { get; set; }
        public string RECMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> RECMODIFIEDON { get; set; }
        public string CODTIPOFUNCAO { get; set; }
        public string SIGLA { get; set; }
        public Nullable<short> ESOCIALFUNCAOCONF { get; set; }
    
        public virtual ICollection<PFUNC> PFUNC { get; set; }
        public virtual ICollection<PFUNC> PFUNC1 { get; set; }
    }
}
