//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.FISCAL.CadConsultaCadastro4SVRS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", ConfigurationName="CadConsultaCadastro4SVRS.CadConsultaCadastro4Soap")]
    public interface CadConsultaCadastro4Soap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do conteúdo (nfeResultMsg) da mensagem consultaCadastroResponse não corresponde ao valor padrão (consultaCadastro)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro", ReplyAction="*")]
        COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroResponse consultaCadastro(COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro", ReplyAction="*")]
        System.Threading.Tasks.Task<COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroResponse> consultaCadastroAsync(COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaCadastro", WrapperNamespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", IsWrapped=true)]
    public partial class consultaCadastroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", Order=0)]
        public System.Xml.Linq.XElement nfeDadosMsg;
        
        public consultaCadastroRequest() {
        }
        
        public consultaCadastroRequest(System.Xml.Linq.XElement nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="nfeResultMsg", WrapperNamespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", IsWrapped=true)]
    public partial class consultaCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", Order=0)]
        public System.Xml.Linq.XElement consultaCadastroResult;
        
        public consultaCadastroResponse() {
        }
        
        public consultaCadastroResponse(System.Xml.Linq.XElement consultaCadastroResult) {
            this.consultaCadastroResult = consultaCadastroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CadConsultaCadastro4SoapChannel : COAD.FISCAL.CadConsultaCadastro4SVRS.CadConsultaCadastro4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CadConsultaCadastro4SoapClient : System.ServiceModel.ClientBase<COAD.FISCAL.CadConsultaCadastro4SVRS.CadConsultaCadastro4Soap>, COAD.FISCAL.CadConsultaCadastro4SVRS.CadConsultaCadastro4Soap {
        
        public CadConsultaCadastro4SoapClient() {
        }
        
        public CadConsultaCadastro4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CadConsultaCadastro4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadConsultaCadastro4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadConsultaCadastro4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroResponse COAD.FISCAL.CadConsultaCadastro4SVRS.CadConsultaCadastro4Soap.consultaCadastro(COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroRequest request) {
            return base.Channel.consultaCadastro(request);
        }
        
        public System.Xml.Linq.XElement consultaCadastro(System.Xml.Linq.XElement nfeDadosMsg) {
            COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroRequest inValue = new COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroResponse retVal = ((COAD.FISCAL.CadConsultaCadastro4SVRS.CadConsultaCadastro4Soap)(this)).consultaCadastro(inValue);
            return retVal.consultaCadastroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroResponse> COAD.FISCAL.CadConsultaCadastro4SVRS.CadConsultaCadastro4Soap.consultaCadastroAsync(COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroRequest request) {
            return base.Channel.consultaCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroResponse> consultaCadastroAsync(System.Xml.Linq.XElement nfeDadosMsg) {
            COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroRequest inValue = new COAD.FISCAL.CadConsultaCadastro4SVRS.consultaCadastroRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((COAD.FISCAL.CadConsultaCadastro4SVRS.CadConsultaCadastro4Soap)(this)).consultaCadastroAsync(inValue);
        }
    }
}
