//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_menu
    {
        public long id_REF { get; set; }
        public string id_categoria_REF { get; set; }
        public string nome_TXT { get; set; }
        public string link_TXT { get; set; }
        public string area_TXT { get; set; }
    }
}
