//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class busca_completa_tributario
    {
        public int id { get; set; }
        public int id_conteudo { get; set; }
        public int id_tipo_conteudo { get; set; }
        public Nullable<int> id_perfil { get; set; }
        public Nullable<System.DateTime> data_conteudo { get; set; }
        public string palavras_indexadas { get; set; }
        public Nullable<int> idGED { get; set; }
    }
}
