//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class calend
    {
        public long id { get; set; }
        public string area { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string obrigacao { get; set; }
        public string pobrigadas { get; set; }
        public string fgerador { get; set; }
        public string aliquota { get; set; }
        public string codrecolhimento { get; set; }
        public string obs { get; set; }
        public string penalidade { get; set; }
        public string cc_url { get; set; }
    }
}
