//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class campanha_concurso_cultural
    {
        public int id { get; set; }
        public Nullable<int> sn_cliente { get; set; }
        public Nullable<int> cliente_id { get; set; }
        public Nullable<int> curso_id { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string cpf { get; set; }
        public string profissao { get; set; }
        public string mensagem { get; set; }
        public Nullable<System.DateTime> log_dt_cadastro { get; set; }
    }
}
