//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class campanha_contador_respostas_old
    {
        public campanha_contador_respostas_old()
        {
            this.campanha_contador_comentarios_old = new HashSet<campanha_contador_comentarios_old>();
        }
    
        public int id { get; set; }
        public Nullable<int> campanha_contador_perguntas_id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string profissao { get; set; }
        public Nullable<int> cliente { get; set; }
        public string resposta { get; set; }
        public Nullable<int> ativo { get; set; }
        public Nullable<int> premiado { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
    
        public virtual ICollection<campanha_contador_comentarios_old> campanha_contador_comentarios_old { get; set; }
        public virtual campanha_contador_perguntas_old campanha_contador_perguntas_old { get; set; }
    }
}
