//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class campanha_contador_perguntas_old
    {
        public campanha_contador_perguntas_old()
        {
            this.campanha_contador_respostas_old = new HashSet<campanha_contador_respostas_old>();
        }
    
        public int id { get; set; }
        public string pergunta { get; set; }
        public string autor { get; set; }
        public Nullable<int> ativo { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
    
        public virtual ICollection<campanha_contador_respostas_old> campanha_contador_respostas_old { get; set; }
    }
}
