//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes_senhas
    {
        public int id { get; set; }
        public string cnpj_cpf { get; set; }
        public string contrato { get; set; }
        public string produto { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public System.DateTime log_dt_cadastro { get; set; }
        public Nullable<int> log_usuario_id { get; set; }
    }
}
