//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes_login_ext
    {
        public int id { get; set; }
        public string cpf_cnpj { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
