//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_AREAS
    {
        public CO_AREAS()
        {
            this.CO_OBRIGACOES = new HashSet<CO_OBRIGACOES>();
        }
    
        public string COD_AREA { get; set; }
        public string NOME_AREA { get; set; }
        public string ABRANGENCIA { get; set; }
        public Nullable<short> HABILITADO { get; set; }
    
        public virtual ICollection<CO_OBRIGACOES> CO_OBRIGACOES { get; set; }
    }
}
