//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_CALENDARIO
    {
        public long NUM_CALENDARIO { get; set; }
        public long NUM_OBRIGACAO { get; set; }
        public System.DateTime DTReferencia { get; set; }
        public string TXT_REFERENCIA { get; set; }
        public Nullable<short> HABILITADO { get; set; }
        public Nullable<System.DateTime> CriadoEmDT { get; set; }
        public Nullable<System.DateTime> AtualizadoEmDT { get; set; }
        public string CriadoPor { get; set; }
        public string AtualizadoPor { get; set; }
    
        public virtual CO_OBRIGACOES CO_OBRIGACOES { get; set; }
    }
}
