//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursos_minas_contatos
    {
        public int id { get; set; }
        public Nullable<int> cursos_minas_id { get; set; }
        public Nullable<int> contato_minas_id { get; set; }
    }
}
