//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class destaque_adv
    {
        public int id { get; set; }
        public string manchete { get; set; }
        public string titulo { get; set; }
        public string verbete { get; set; }
        public Nullable<int> id_cadastro { get; set; }
        public string conteudo { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public string status { get; set; }
    }
}
