//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class estacio_users
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public int ddd { get; set; }
        public string instituicao { get; set; }
        public string inicio { get; set; }
        public string conclusao { get; set; }
        public string ultimo { get; set; }
        public string area { get; set; }
        public int id_tipo { get; set; }
        public string curso { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
    }
}
