//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class int_enquetes
    {
        public int id { get; set; }
        public string palavras_chave { get; set; }
        public string titulo { get; set; }
        public System.DateTime data_cadastro { get; set; }
    }
}
