//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_item
    {
        public int menu_item_id { get; set; }
        public Nullable<int> menu_item_secao_id { get; set; }
        public Nullable<int> menu_item_pai_id { get; set; }
        public Nullable<int> menu_item_order { get; set; }
        public string menu_item_nome { get; set; }
        public Nullable<int> menu_item_nivel { get; set; }
        public Nullable<int> menu_item_exibicao_tipo { get; set; }
        public string menu_item_url_externa { get; set; }
        public string menu_item_url_interna { get; set; }
        public Nullable<int> menu_item_arquivo_id { get; set; }
        public string menu_item_texto { get; set; }
        public string menu_item_url_filtro_tab_nome { get; set; }
        public string menu_item_url_filtro_tab_campo_data { get; set; }
        public string menu_item_filtro_query_automatica { get; set; }
        public string menu_item_filtro_query_manual { get; set; }
        public Nullable<int> menu_item_flag_ambiente_homologacao { get; set; }
        public Nullable<int> menu_item_flag_ambiente_producao { get; set; }
        public Nullable<int> menu_item_flag_protocolo { get; set; }
        public string data_atualizacao { get; set; }
    }
}
