//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_item_campo_exibicao
    {
        public int menu_item_campo_exibicao_id { get; set; }
        public string campo_exibicao_nome { get; set; }
        public Nullable<int> campo_exibicao_ordem { get; set; }
        public string campo_exibicao_caption { get; set; }
        public Nullable<int> menu_item_id { get; set; }
    }
}
