//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_item_arquivo_scribd
    {
        public int id { get; set; }
        public Nullable<int> menu_item_arquivo_id { get; set; }
        public Nullable<int> scribd_doc_id { get; set; }
        public string scribd_access_key { get; set; }
        public string scribd_secret_password { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
    }
}
