//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_item_arquivo
    {
        public int menu_item_arquivo_id { get; set; }
        public string menu_item_arquivo_nome_fisico { get; set; }
        public string menu_item_arquivo_nome_display { get; set; }
        public Nullable<int> menu_item_arquivo_tamanho { get; set; }
        public Nullable<System.DateTime> menu_item_arquivo_data_cadastro { get; set; }
    }
}
