//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuNovo
    {
        public int id_menu { get; set; }
        public string nome { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> cadastro_data { get; set; }
        public Nullable<int> cadastro_por { get; set; }
    }
}
