//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class consultoriaEntities : DbContext
    {
        public consultoriaEntities()
            : base("name=consultoriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<arquivos> arquivos { get; set; }
        public DbSet<colecionadores> colecionadores { get; set; }
        public DbSet<consultores> consultores { get; set; }
        public DbSet<consultoria> consultoria { get; set; }
        public DbSet<consultoria_bkp> consultoria_bkp { get; set; }
        public DbSet<consultoria_busca_nao_encontrada> consultoria_busca_nao_encontrada { get; set; }
        public DbSet<titulos_pesquisa> titulos_pesquisa { get; set; }
        public DbSet<consultoria_log_update> consultoria_log_update { get; set; }
    }
}
