//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_niver_coad_historias
    {
        public int id { get; set; }
        public Nullable<int> clientes_id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string cpf_cnpj { get; set; }
        public string profissao { get; set; }
        public string historia { get; set; }
        public Nullable<int> aprovada { get; set; }
        public Nullable<int> respondida { get; set; }
        public int classificacao { get; set; }
        public int contador { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
    }
}
