//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public int id { get; set; }
        public string cli_id { get; set; }
        public string session1 { get; set; }
        public string pesquisa { get; set; }
        public System.DateTime DATA { get; set; }
    }
}
