//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class supersimples_conteudo
    {
        public int id_REF { get; set; }
        public Nullable<int> categoria_SEL { get; set; }
        public string link_TXT { get; set; }
        public string titulo_TXT { get; set; }
        public string texto_ARA { get; set; }
        public string ordem_TXT { get; set; }
    }
}
