//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_1039_verbetes
    {
        public int id { get; set; }
        public Nullable<int> dired_verbetes_id { get; set; }
        public Nullable<int> tab_1039_id { get; set; }
    }
}
