//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_1034
    {
        public int id_juridico { get; set; }
        public string manchete { get; set; }
        public string destaque { get; set; }
        public string alfa { get; set; }
        public string grupo { get; set; }
        public string titulo { get; set; }
        public string exp_latina { get; set; }
        public string texto { get; set; }
        public System.DateTime data { get; set; }
    }
}
