//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_42
    {
        public int id { get; set; }
        public string manchete { get; set; }
        public string destaque { get; set; }
        public bool destaque_fixo_perfil { get; set; }
        public int id_ramo_direito { get; set; }
        public int id_verbete { get; set; }
        public int id_subverbete { get; set; }
        public string no_autor { get; set; }
        public string autor_qualif { get; set; }
        public string no_subverbete2 { get; set; }
        public string no_subverbete3 { get; set; }
        public string tp_doutrina { get; set; }
        public string titulo_doutrina { get; set; }
        public string nr_doutrina_antiga { get; set; }
        public string tx_sumario { get; set; }
        public string tx_doutrina { get; set; }
        public string tx_palavra_chave { get; set; }
        public string incluir_manual { get; set; }
        public System.DateTime dt_cadastro { get; set; }
        public string home_juridico { get; set; }
        public string destaque_home { get; set; }
    }
}
