//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_30
    {
        public int id { get; set; }
        public string colec { get; set; }
        public string gg { get; set; }
        public string vb { get; set; }
        public string svb { get; set; }
        public string complemento { get; set; }
        public string tipo_materia { get; set; }
        public string expressao_ato { get; set; }
        public string num { get; set; }
        public string org { get; set; }
        public Nullable<int> pagina { get; set; }
        public string informativo { get; set; }
        public string ano { get; set; }
        public string modulo { get; set; }
        public string titulo { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public Nullable<int> idGED { get; set; }
        public string GED_revoga_altera { get; set; }
    }
}
