//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_1039_destaques
    {
        public int id { get; set; }
        public Nullable<int> DIRED_verbetes_id { get; set; }
        public string termos_busca { get; set; }
        public Nullable<int> ordem { get; set; }
        public string tp_destaque { get; set; }
        public Nullable<int> consulta_id1 { get; set; }
        public Nullable<int> consulta_id2 { get; set; }
        public Nullable<int> consulta_id3 { get; set; }
        public Nullable<int> consulta_id4 { get; set; }
        public Nullable<int> consulta_id5 { get; set; }
        public Nullable<int> consulta_id6 { get; set; }
        public Nullable<int> consulta_id7 { get; set; }
        public Nullable<int> consulta_id8 { get; set; }
        public Nullable<int> consulta_id9 { get; set; }
        public Nullable<int> consulta_id10 { get; set; }
        public string link_materia1 { get; set; }
        public string link_materia2 { get; set; }
        public string link_materia3 { get; set; }
        public string link_materia4 { get; set; }
        public string link_materia5 { get; set; }
        public string link_materia6 { get; set; }
        public string link_materia7 { get; set; }
        public string link_materia8 { get; set; }
        public string link_materia9 { get; set; }
        public string link_materia10 { get; set; }
        public Nullable<int> log_usuario_id { get; set; }
        public Nullable<System.DateTime> log_dt_cadastro { get; set; }
        public Nullable<int> deletado { get; set; }
    }
}
