//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_05
    {
        public int id { get; set; }
        public string colec { get; set; }
        public string gg { get; set; }
        public string vb { get; set; }
        public string svb { get; set; }
        public string complemento { get; set; }
        public string complemento_extra { get; set; }
        public string nota { get; set; }
        public string num { get; set; }
        public string texto { get; set; }
        public string indice { get; set; }
        public string jurisprudencia { get; set; }
        public System.DateTime dataCadastro { get; set; }
    }
}
