//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_100
    {
        public int id { get; set; }
        public int num { get; set; }
        public string sessao { get; set; }
        public string vb { get; set; }
        public string svb { get; set; }
        public string titulo { get; set; }
        public string tribunal { get; set; }
        public string unanime { get; set; }
        public string recurso { get; set; }
        public string relator { get; set; }
        public string partes { get; set; }
        public string advogado { get; set; }
        public string ementa { get; set; }
        public Nullable<int> ano { get; set; }
        public System.DateTime dataCadastro { get; set; }
    }
}
