//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_1026_noticias
    {
        public int id { get; set; }
        public Nullable<int> tab_1026_news_id { get; set; }
        public Nullable<int> secoes_id { get; set; }
        public Nullable<int> verbetes_id { get; set; }
        public Nullable<int> subverbetes_id { get; set; }
        public string manchete { get; set; }
        public string ementa { get; set; }
        public string link { get; set; }
        public string palavras_chave { get; set; }
        public string texto { get; set; }
        public string newsletter { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
    
        public virtual secoes secoes { get; set; }
        public virtual tab_1026_news tab_1026_news { get; set; }
        public virtual verbetes verbetes { get; set; }
        public virtual verbetes verbetes1 { get; set; }
    }
}
