//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_31_xml
    {
        public int id { get; set; }
        public string colec { get; set; }
        public string gg { get; set; }
        public string vb { get; set; }
        public string svb { get; set; }
        public string complemento { get; set; }
        public string tipo_materia { get; set; }
        public string expressao_ato { get; set; }
        public string num { get; set; }
        public string org { get; set; }
        public Nullable<int> pagina { get; set; }
        public string informativo { get; set; }
        public string ano { get; set; }
        public string modulo { get; set; }
        public System.DateTime dataCadastro { get; set; }
    }
}
