//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_1001
    {
        public int id { get; set; }
        public Nullable<int> id_modulo { get; set; }
        public string temas { get; set; }
        public string texto { get; set; }
        public string edicao { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public string palavra_chave { get; set; }
    }
}
