//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_1025_noticias
    {
        public int id { get; set; }
        public int id_tipo { get; set; }
        public int id_assunto { get; set; }
        public int id_verbete { get; set; }
        public int id_estado { get; set; }
        public string newsletter { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public string tp_ato { get; set; }
        public string nr_ato { get; set; }
        public string nr_ementa_adv { get; set; }
        public System.DateTime dt_ato { get; set; }
        public string tx_manchete { get; set; }
        public string tx_submanchete { get; set; }
        public string tx_palavra_chave { get; set; }
        public string tx_newsletter { get; set; }
        public int nr_newsletter { get; set; }
        public string ano { get; set; }
        public string ds_link { get; set; }
    }
}
