//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_95
    {
        public int id { get; set; }
        public string tit { get; set; }
        public string tit_vb { get; set; }
        public string cap { get; set; }
        public string cap_vb { get; set; }
        public string sec { get; set; }
        public string sec_vb { get; set; }
        public string subsec { get; set; }
        public string subsec_vb { get; set; }
        public string texto { get; set; }
        public string arquivo { get; set; }
    }
}
