//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COAD.PORTAL.Repositorios.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tema_verbete_sub_verbete_conteudo_link
    {
        public int id { get; set; }
        public string link { get; set; }
        public int tabela_id { get; set; }
        public int conteudo_tabela_id { get; set; }
        public Nullable<int> conteudo_id { get; set; }
        public System.DateTime data_registro { get; set; }
        public int contador { get; set; }
    }
}
